refactor: migrated feedback forms to svelte 5
containers/podman-desktop pull request #10000
Opened 2024-11-20 07:23 UTC by gastoner

### What does this PR do?
Migrates feedback forms to svelte5

### What issues does this PR fix or reference?
Part of #9192 

- [ ] Tests are covering the bug fix or the new feature

2024-11-20 08:03 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +$effect(() => {
Issue: looks ks like it's more a $derived state than effect

2024-11-20 08:03 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.spec.ts
> +    value: openExternalMock,
issue: AFAIK we don't need to have this change

vi.mocked(window.openExternal) gives you access to the mock

2024-11-20 08:03 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +let issueValidaionError = $state('');
maybe you can in a previous commit fix the name of this variable

2024-11-20 08:05 UTC, axel7083 reviewed
Thanks for taking the time to do the migration :+1: really appreciate 😃

I noted some small changes

2024-11-20 08:05 UTC, axel7083 commented on packages/renderer/src/lib/feedback/SendFeedback.svelte
> +  <Modal name="Share your feedback" onclose={hideModal}>
Not sure this is supported, Modal is our custom component.. not sure Svelte do the migration for us here

2024-11-20 08:05 UTC, axel7083 commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.spec.ts
> +const sendFeedbackMock = vi.fn();
Why declaring them on top? 

It should be avoid in favour of `vi.mocked(window.sendFeedback).mock....`

2024-11-20 08:05 UTC, axel7083 commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +});
I think this effect could be placed inside a derived by state :thinking:

2024-11-20 08:58 UTC, axel7083 commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +let { onCloseForm = () => {} }: Props = $props();
In the Props interface onCloseForm is not optional, the default value is not needed.

You may keep the default value and change the Props to something like 

```ts
interface Props {
  onCloseForm?: () => void;
}
```

2024-11-20 08:59 UTC, axel7083 commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +let { onCloseForm = () => {} }: Props = $props();
same remark, default not needed if onCloseForm is mandatory

2024-11-20 08:59 UTC, axel7083 commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +$effect(() => {
See https://svelte.dev/docs/svelte/$derived#$derived.by

2024-11-20 09:16 UTC, gastoner commented
@axel7083 switched to derived and removed default value

2024-11-20 10:13 UTC, axel7083 approved these changes
LGTM

2024-11-20 14:56 UTC, benoitf requested changes
it does not work

you can't click on the buttons

2024-11-20 14:56 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +let { onCloseForm }: Props = $props();
I think it needs to have a default value if not specified

```suggestion
let { onCloseForm = () => {} }: Props = $props();
```

2024-11-20 14:56 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +let { onCloseForm }: Props = $props();
same remark there

2024-11-20 14:56 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +    <Button aria-label="Preview on GitHub" onclick={() => openGitHubIssues()} disabled={!issueTitle || !issueDescription}>Preview on GitHub</Button>
AFAIK you can't change on:click to onclick as the component is still expecting an event, not a callback

2024-11-20 14:58 UTC, benoitf commented
https://github.com/user-attachments/assets/2992b713-a398-4924-96f6-8853c1eb479f

2024-11-21 09:40 UTC, gastoner commented
@axel7083 I've rebased due to some conflicts. Can you check again? Thanks 🙏

2024-11-21 09:52 UTC, benoitf approved these changes
please revert the .?() call on onCloseForm before merging

2024-11-21 09:52 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +  onCloseForm?.();
revert
```suggestion
  onCloseForm();
```

2024-11-21 09:52 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/DevelopersFeedback.svelte
> +  onCloseForm?.();
revert
```suggestion
  onCloseForm();
```

2024-11-21 09:52 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +  onCloseForm?.();
revert
```suggestion
  onCloseForm();
```

2024-11-21 09:52 UTC, benoitf commented on packages/renderer/src/lib/feedback/feedbackForms/GitHubIssueFeedback.svelte
> +    <Button class="underline" type="link" aria-label="Cancel" on:click={() => onCloseForm?.()}>Cancel</Button>
revert
```suggestion
    <Button class="underline" type="link" aria-label="Cancel" on:click={() => onCloseForm()}>Cancel</Button>
```

2024-11-22 10:02 UTC, axel7083 approved these changes
LGTM

2024-11-22 15:23 UTC, merged