docs(website): added documentation about applying a yaml manifest
containers/podman-desktop pull request #10324
Opened 2024-12-12 10:46 UTC by shipsing

### What does this PR do?
Adds documentation about applying a YAML manifest
### Screenshot / video of UI

### What issues does this PR fix or reference?
https://github.com/podman-desktop/podman-desktop/issues/10096

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-12-16 19:34 UTC, cdrage requested changes

2024-12-16 19:34 UTC, cdrage commented on website/docs/kubernetes/applying-a-yaml-manifest.md
> +Based on your needs, you can apply a YAML manifest to create a Kubernetes object, such as `Node`, `Deployment`, `Service`, `PersistentVolumeClaim`, and others. For example, a Kubernetes deployment th
```suggestion
You can deploy a YAML manifest to create a Kubernetes object, such as `Node`, `Deployment`, `Service`, `PersistentVolumeClaim`, and others. For example, a Kubernetes deployment that requires sensitive data storage, you can apply a YAML manifest to create a `Secret` object.
```

"Based on your needs" is kinda odd IMO

2024-12-16 19:35 UTC, cdrage commented
Very small change, but otherwise LGTM!

2024-12-17 09:05 UTC, Firewall approved these changes
Awesome 👍

2024-12-18 06:07 UTC, shipsing commented
@cdrage, Could you please verify the PR and confirm? Thanks

2024-12-18 11:27 UTC, cdrage approved these changes

2024-12-19 05:21 UTC, merged