fix: building image without name should have a correct task title
containers/podman-desktop pull request #10321
Opened 2024-12-12 10:27 UTC by jeffmaury

Fixes #10078

### What does this PR do?

Ensure the task title is correct if no image name is given

### Screenshot / video of UI

![unamed](https://github.com/user-attachments/assets/6ddf67cd-6769-4806-86dc-d9e6abb85258)

### What issues does this PR fix or reference?

### How to test this PR?

1. Build an image without the image name
2. Check the task title

- [x] Tests are covering the bug fix or the new feature

2024-12-13 01:02 UTC, dgolovin requested changes
There is another occurrence of 'undefined'. It is in the build log.

![image](https://github.com/user-attachments/assets/aa9cd394-1199-4d4b-ad5a-cb2394aeda89)

2024-12-13 01:05 UTC, dgolovin commented on packages/main/src/plugin/index.ts
> +          title: `Building ${imageName ?? 'unnamed image'}`,
IMO: `Building image` better that `Building unnamed image`
```suggestion
          title: `Building image ${imageName ?? ''}`,
```

2024-12-13 15:07 UTC, gastoner approved these changes
![image](https://github.com/user-attachments/assets/aee2a019-5f51-4c7f-9cba-1b8c11414441)
On Windows

2024-12-16 17:57 UTC, dgolovin approved these changes

2024-12-16 17:57 UTC, merged