refactor: adding a check for the KUBECONFIG variable
containers/podman-desktop pull request #10331
Opened 2024-12-12 14:30 UTC by AlexonOliveiraRH

### What does this PR do?

This validation of the existence of the KUBECONFIG variable set in the operating system aims to inform the use through the console that this could lead to an unexpected behavior in some scenarios, like trying to install a Kubernetes cluster and failing because Podman Desktop cannot use or update the default ~/.kube/config file.  Although this not correct the variable value, at least informs the user of its value, allowing the user to take the proper action to fix it.

### Screenshot / video of UI

### What issues does this PR fix or reference?

The issue #9983 describes this better with an example of such situation. Closes #9983.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2025-01-28 11:06 UTC, benoitf requested changes
this PR is not mergeable as PR checks are in error state

2025-02-04 08:52 UTC, benoitf commented
setting to draft as not updated

2025-03-14 09:30 UTC, benoitf commented
outdated

2025-03-14 09:30 UTC, closed without merging

2025-03-14 17:10 UTC, AlexonOliveiraRH commented
@benoitf thank you for your help, but @odockal got this covered in another [Issue](https://github.com/podman-desktop/podman-desktop/issues/10367) and [PR](https://github.com/podman-desktop/podman-desktop/pull/10905)