chore(test): extract cluster-related operations to a dedicated utility file
containers/podman-desktop pull request #10390
Opened 2024-12-16 20:36 UTC by amisskii

Signed-off-by: Anton Misskii <amisskii@redhat.com>

### What does this PR do?

extracts cluster-related operations to a dedicated utility file

### What issues does this PR fix or reference?

https://github.com/podman-desktop/podman-desktop/issues/10389
### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-12-17 09:29 UTC, odockal requested changes

2024-12-17 09:29 UTC, odockal commented on tests/playwright/src/utility/cluster-operations.ts
> +  return test.step('Delete Kind cluster', async () => {
make cluster name parametrized -> resourceName.

2024-12-17 09:29 UTC, odockal commented on tests/playwright/src/utility/cluster-operations.ts
> +  page: Page,
please change to perform one particular action, ie defined by ResourceElementAction (maybe change name to resourceConnectionActions?) and check for expected state.

2024-12-17 09:29 UTC, odockal commented on tests/playwright/src/utility/cluster-operations.ts
> +  return test.step('Check resources added with cluster', async () => {
please add containerName into step string.

2024-12-17 09:29 UTC, odockal commented on tests/playwright/src/specs/kind.spec.ts
> +    test('Check resources added with the Kind cluster', async ({ page }) => {
please keep test method for each operation.

2025-01-07 12:45 UTC, amisskii commented
workflow run: https://github.com/podman-desktop/e2e/actions/runs/12651098063

2025-01-08 11:51 UTC, odockal requested changes

2025-01-08 11:51 UTC, odockal commented on tests/playwright/src/utility/cluster-operations.ts
> +  return test.step('Perform resource connection action', async () => {
would be nice to include params into step description - performs START action, expects "Running" state, something like that.

2025-01-08 11:51 UTC, odockal commented on tests/playwright/src/utility/cluster-operations.ts
> +    const volumeName = await getVolumeNameForContainer(page, containerName);
What if volume name differs from container name? Should we make it a parameter?

2025-01-08 12:18 UTC, amisskii commented on tests/playwright/src/utility/cluster-operations.ts
> +    const volumeName = await getVolumeNameForContainer(page, containerName);
This method should retrieve the details of all active volumes and check whether any of these volumes are being used by a specific container, whose name is passed as a method parameter.

2025-01-09 15:32 UTC, odockal approved these changes

2025-01-10 09:14 UTC, merged