chore: update filesize to v10
containers/podman-desktop pull request #1044
Opened 2022-12-15 14:48 UTC by benoitf

### What does this PR do?
update filesize from v8 to v10
we need to change how we're importing/using the library

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

related to a dependabot issue that doesn't work out of the box
https://github.com/containers/podman-desktop/pull/1024

### How to test this PR?

I've added unit tests
but you may check were we display some size units.

Change-Id: I68fe64c411e566d56a17f606e8ffa2286c742bd2
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

2022-12-15 14:50 UTC, cdrage approved these changes

2022-12-15 14:51 UTC, cdrage commented
`yarn:test` is failing?

2022-12-15 14:52 UTC, cdrage requested changes
```
 FAIL  src/lib/image/image-utils.spec.ts [ src/lib/image/image-utils.spec.ts ]
 FAIL  src/lib/volume/volume-utils.spec.ts [ src/lib/volume/volume-utils.spec.ts ]
 FAIL  src/lib/container/container-utils.spec.ts [ src/lib/container/container-utils.spec.ts ]
SyntaxError: Unexpected token 'export'
Module /Users/cdrage/syncthing/dev/electron/podman-desktop/node_modules/moment/dist/moment.js:5677 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "moment" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "moment"
      ]
    }
  }
}
```

Tests are currently failing locally and on CI

2022-12-15 14:56 UTC, benoitf commented
yes it should be fixed now

2022-12-19 21:02 UTC, cdrage approved these changes
LGTM, tests pass now!

2022-12-19 21:02 UTC, merged