Make getProxySettingsFromSystem() work on FreeBSD
containers/podman-desktop pull request #10463
Opened 2024-12-22 18:17 UTC by arrowd

2024-12-23 11:01 UTC, jeffmaury requested changes
Core cannot call code from an extension. The isLinux method to be called is located in util.ts

2024-12-23 11:14 UTC, arrowd commented
Ok, will do. Should I also remove the code I added to `os.ts`?

2025-01-15 05:56 UTC, arrowd commented
Can we get this in?

2025-01-28 11:08 UTC, benoitf requested changes, later dismissed
@arrowd are you running Podman Desktop on FreeBSD ?

note: the change in extensions/compose should be removed

2025-01-28 13:11 UTC, benoitf commented
FYI you'll need to edit the commit to be compliant with https://www.conventionalcommits.org/en/v1.0.0/

2025-01-28 13:12 UTC, benoitf commented
semantic PR check is failing for now

2025-01-28 13:14 UTC, arrowd commented
> @arrowd are you running Podman Desktop on FreeBSD ?

Yes, at least I'm trying to do so. I had some success with previous version - the app started, but there was nothing useful that can be done there, because our Podman implementation is missing `podman machine *` subcommands family.

Now this version doesn't start due to that proxy engine error, whcih I'm hoping to fix.

2025-01-28 13:26 UTC, arrowd commented
It seems I still fail to please the "Semantic PR" check. Do I have to create issues for both of my commits?

2025-01-28 13:34 UTC, benoitf commented
you could edit your history and only keep one

but they need to follow the convention like

`chore: make getProxySettingsFromSystem() work on FreeBSD` and the same for the PR's title

note that other checks are also failing

2025-01-28 13:52 UTC, benoitf reviewed
will need a ✅ on all PR checks to be able to merge

2025-01-28 13:53 UTC, benoitf commented
@arrowd also if you can apply the official template in the PR as tools are searching for the correct format
https://raw.githubusercontent.com/podman-desktop/podman-desktop/refs/heads/main/.github/PULL_REQUEST_TEMPLATE.md

2025-01-28 13:58 UTC, arrowd commented
Thanks for guiding me through the submission!

2025-01-28 17:01 UTC, benoitf approved these changes

2025-02-04 13:33 UTC, jeffmaury approved these changes
LGTM

2025-02-11 13:30 UTC, arrowd commented
So, can we get this in?

2025-02-11 14:12 UTC, merged

2025-02-11 14:13 UTC, arrowd commented
Great, thank you. Can I expect this change to be present in the upcoming release (1.16.2 or whatever it is) ?