website: the linux binary is not a source, it should be promoted as source file
containers/podman-desktop pull request #1133
Opened 2023-01-06 15:41 UTC by benoitf

### What does this PR do?
alternate file for linux is not called 'binary' so people might think there is only a flatpak version

### Screenshot/screencast of this PR
![image](https://user-images.githubusercontent.com/436777/211046032-30f63419-acdb-44b6-a991-7e975dab81c9.png)

N/A 

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/1132

### How to test this PR?

Look at netlify rendering

Change-Id: I4c3414c5dace72a90095239015f20157dbea12c4
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

2023-01-06 15:53 UTC, Drugoy commented
You've got a typo in this ticket's header:
website: the linux binary is not a source, it should be promoted as source file
->
website: the linux binary is not a source, it should be promoted as a **binary** file

2023-01-06 16:25 UTC, cdrage requested changes

2023-01-06 16:25 UTC, cdrage commented on website/src/pages/downloads/linux.tsx
> +              Amd64 binary (.tgz)
```suggestion
              AMD64 binary (.tgz)
```

2023-01-09 08:05 UTC, benoitf commented
@Drugoy your comments are fixed in this PR

2023-01-09 08:10 UTC, themr0c commented on website/src/pages/index.tsx
> +                <p className="text-base text-center">flatpak or AMD64 binary (tar.gz)</p>
```suggestion
                <p className="text-base text-center">Flatpak or AMD64 binary (tar.gz)</p>
```

2023-01-09 08:11 UTC, benoitf commented on website/src/pages/index.tsx
> +                <p className="text-base text-center">flatpak or AMD64 binary (tar.gz)</p>
fixed

2023-01-09 08:12 UTC, themr0c approved these changes

2023-01-09 08:17 UTC, themr0c commented
We probably have to reflect that back in the docs :). Should we call the binary in the .tar.gz a static binary?

2023-01-09 08:35 UTC, slemeur commented
@themr0c : **binary** is enough.

2023-01-09 08:35 UTC, slemeur approved these changes
LGTM

2023-01-09 20:46 UTC, Drugoy commented
@cdrage's requested changes need to somehow be marked as obsolete because currently github blocks merging because of that request.

2023-01-09 21:14 UTC, benoitf commented
probably he'll amend the review tomorrow 👍

2023-01-10 20:56 UTC, cdrage approved these changes

2023-01-10 20:56 UTC, merged