fix: Improve action consistency
containers/podman-desktop pull request #1225
Opened 2023-01-23 17:14 UTC by deboer-tim

### What does this PR do?

This commit improves consistency and fixes a couple minor UI issues:
- Moves Image > Push and > Show History to kebab menu, making Image list page actions consistent with other pages.
- Adds support for disabled actions in ListItemButtonIcon.
- Makes Image > Delete action disabled (vs missing) so that actions line up and don't change position in the list of images.
- Makes Container Details > Open Browser action disabled (vs missing) so that actions don't change position when container starts.
- Nit: fix imagesUnsubscribe typo in ImagesList

### Screenshot/screencast of this PR

<img width="781" alt="Screenshot 2023-01-23 at 12 11 55 PM" src="https://user-images.githubusercontent.com/19958075/214104678-2d4148d7-484e-41f9-9da9-aecee328ae2b.png">

<img width="781" alt="Screenshot 2023-01-23 at 12 09 40 PM" src="https://user-images.githubusercontent.com/19958075/214104663-64fa0601-bb79-49bf-8226-6a78a88d3622.png">

### What issues does this PR fix or reference?

N/A

2023-01-23 17:25 UTC, benoitf commented
it would be nice to have separate commits for all the changes

2023-01-25 19:59 UTC, cdrage requested changes
Very small nitpick, otherwise this LGTM! Thanks for the changes. I agree having the button disabled looks better for consistency as well as tells the user "hey, the feature is there, but you can't use it yet unless X happens".

2023-01-25 19:59 UTC, cdrage commented on packages/renderer/src/lib/ImagesList.svelte
> +            <td class="pl-6 text-right whitespace-nowrap rounded-tr-lg rounded-br-lg">
Good catch! I believe you'll have to modify it too for VolumeList and remove the pr-1? I saw in ContainerList and PodsList we don't use this class, and it's simply a div that floats to the right (maybe we can replace it with: `<div class="text-right w-full">` instead and see if it works?

Just a thought!

2023-01-25 19:59 UTC, cdrage commented
![Screenshot 2023-01-25 at 2 55 04 PM](https://user-images.githubusercontent.com/6422176/214676045-9724ba74-e5de-4de0-a245-b3da2826c578.png)
![Screenshot 2023-01-25 at 2 54 57 PM](https://user-images.githubusercontent.com/6422176/214676046-c584ea55-64cc-472e-9dfa-190592c7c204.png)

LGTM for testing it out

2023-01-25 21:49 UTC, deboer-tim commented on packages/renderer/src/lib/ImagesList.svelte
> +            <td class="pl-6 text-right whitespace-nowrap rounded-tr-lg rounded-br-lg">
Good catch on the volume alignment, I've removed the pr-1 to make add pages aligned. I would prefer not to do the div change as it was already commented that this PR is too big :) and it looks like the container/pod list have actually added two divs to insert in additional status - i.e. we should copy this, but not until we'd put something in the extra div or we do some code consistency cleanup.

2023-01-27 21:23 UTC, cdrage approved these changes

2023-01-30 12:54 UTC, benoitf commented
FYI you're not required to rebase/merge from main branch before merging especially when there is no library change
if there are conflicts, it's reported

2023-01-30 13:01 UTC, deboer-tim commented
When you do a merge from the web and your account has more than 1 email it prompts which of your addresses to use to sign off the commit. Last time I tried it used a different one anyway and failed DCO. Haven't found any way to configure this or a GitHub bug, so was just going with the safer option for now...

2023-01-30 13:04 UTC, benoitf commented
I think the best way is to rebase instead of merge (only if there is a conflict else you don't need to rebase)
and use the squash into one

2023-01-30 13:09 UTC, deboer-tim commented
👍🏼 I'll take a better look at the options next time, just got spooked by the "I can't trust which 'me' it's going to use".

2023-01-30 13:39 UTC, merged