docs: add release document
containers/podman-desktop pull request #1501
Opened 2023-02-16 17:05 UTC by benoitf

### What does this PR do?
Document process to cut a release

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1497

### How to test this PR?

Change-Id: Ic19eb6323d2dc95e66f3c2046bf1f36512847654

2023-02-22 00:46 UTC, cdrage requested changes
Honestly these changes are minor as this is more of an internal document / not really public facing. So I'm good with no grammatical changes / etc.

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +- Make sure everything that needs to be in the release is there.
```suggestion
- Make sure everything that needs to be in the release is there
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +- Check PR for Release Notes is almost complete
```suggestion
- Check that the PR for Release Notes is almost completed by PM
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. specify the branch to use for the release. It's main for all major releases. For a bugfix release
```suggestion
1. Specify the branch to use for the release. It's main for all major releases. For a bugfix release
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. edit the version the milestone going to https://github.com/containers/podman-desktop/milestones and select the date and then it `Close milestone`
```suggestion
1. Edit the version the milestone going to https://github.com/containers/podman-desktop/milestones and select the date and then it `Close milestone`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +## package manager workflow
```suggestion
## Package manager workflow
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. select the release version like `0.12.0` and click `Run workflow`
```suggestion
1. Select the release version like `0.12.0` and click `Run workflow`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. select the release version like `0.12.0` and click `Run workflow`
```suggestion
1. Select the release version like `0.12.0` and click `Run workflow`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. select the release version like `0.12.0` and click `Run workflow`
```suggestion
1. Select the release version like `0.12.0` and click `Run workflow`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. copy the file `$(pwd)/podman-desktop-0.12.0/generated-sources.json` to `generated-sources.json`
```suggestion
1. Copy the file `$(pwd)/podman-desktop-0.12.0/generated-sources.json` to `generated-sources.json`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. commit the files `generated-sources.json` and `io.podman_desktop.PodmanDesktop.yml` and create a PR to the repository with a title like `feat: bump to v0.11.0`
```suggestion
1. Commit the files `generated-sources.json` and `io.podman_desktop.PodmanDesktop.yml` and create a PR to the repository with a title like `feat: bump to v0.11.0`
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. If PR is successful, merge the PR
```suggestion
1. If the PR is successful, merge the PR
```

2023-02-22 00:46 UTC, cdrage commented on RELEASE.md
> +1. title : Podman Desktop v0.12.0
```suggestion
1. Title : Podman Desktop v0.12.0
```

2023-02-22 13:29 UTC, jeffmaury approved these changes
LGTM

2023-02-23 14:26 UTC, benoitf commented
suggestions applied

2023-02-23 19:06 UTC, cdrage approved these changes

2023-02-23 19:07 UTC, merged