docs: add compose spec doc, fix podman compose doc
containers/podman-desktop pull request #1550
Opened 2023-02-23 19:43 UTC by cdrage

docs: add compose spec doc, fix podman compose doc

### What does this PR do?

* Removes redundant information / cleans up the document we had
  regarding Podman Compose
* Adds a Podman spec document that outlines how we currently support it

### Screenshot/screencast of this PR

See Netlify preview

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/1451

### How to test this PR?

`yarn website:dev` or netlify preview

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-03-02 13:16 UTC, benoitf commented on website/docs/compose/podman-compose.md
> +[Podman Compose](https://github.com/containers/podman-compose#readme) is a community-driven tool that allows developers to use the [Compose Spec](https://compose-sec.io) to run multiple containers at
```suggestion
[Podman Compose](https://github.com/containers/podman-compose#readme) is a community-driven tool that allows developers to use the [Compose Spec](https://compose-spec.io) to run multiple containers at the same time and facilitate communication between them. Podman Compose requires a [Compose YAML](https://compose-spec.io/) file with definitions about the containers that need to communicate.
```

2023-03-10 09:38 UTC, lstocchi requested changes

2023-03-10 09:38 UTC, lstocchi commented on website/docs/compose/podman-compose.md
> +[Podman Compose](https://github.com/containers/podman-compose#readme) is a community-driven tool that allows developers to use the [Compose spec](https://compose-sec.io) to run many containers at the
`https://compose-sec.io` -> `https://compose-spec.io`

2023-03-17 13:01 UTC, lstocchi approved these changes
LGTM, just a verb missing

2023-03-17 13:01 UTC, lstocchi commented on website/docs/compose/podman-compose.md
> +To confirm if the containers are running, open Podman Desktop and click on the ‘Containers’ option on the left side of the application. You will the containers bundled together under a Pod named `fla
Missing verb, `you will ... the containers bundle`

2023-03-21 13:17 UTC, cdrage commented
I'm going to just merge this as-is as we've had 2 reviews and this PR has been opened a for a month. We can make some edits / changes after when @themr0c is back

2023-03-21 13:17 UTC, merged