fix: scan plugins-scanning directory at startup as well
containers/podman-desktop pull request #1840
Opened 2023-03-27 14:28 UTC by benoitf

### What does this PR do?
scan the directory at startup and not only when there are changes on the folder

Also add unit tests

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/1681

### How to test this PR?

1. copy a .cdix (extension file) after startup in `plugins-scanning` folder
2. check extension is loaded
3. restart Podman Desktop and check extension is loaded again

Change-Id: I22dd380c79f9b6c3e66467f36a328896ab665e44

2023-03-27 14:43 UTC, jeffmaury requested changes
Seems the expect import is missing in the unit test

2023-03-27 14:48 UTC, benoitf commented
@jeffmaury fixed

2023-03-27 14:55 UTC, jeffmaury requested changes
Tests are failing on Windows due to path conversions

2023-03-27 15:03 UTC, benoitf commented
@jeffmaury ok, I tried something different, let me know

2023-03-27 15:52 UTC, jeffmaury commented
> @jeffmaury ok, I tried something different, let me know

Stlll have 1 error:

![image](https://user-images.githubusercontent.com/695993/227995229-9619648d-2739-48c3-acb0-d54044b7acbc.png)

2023-03-27 16:08 UTC, benoitf commented
@jeffmaury ok, I tried something..I'm like in the dark

2023-03-28 09:28 UTC, jeffmaury commented on packages/main/src/plugin/extension-loader.spec.ts
> +  expect(loadPackagedFileMock).toBeCalledWith(path.join(rootedFakeDirectory, 'foo.cdix'));
```suggestion
  expect(loadPackagedFileMock).toBeCalledWith(path.join(fakeDirectory, 'foo.cdix'));
```

Fix Windows test failure

2023-03-28 09:37 UTC, benoitf commented
suggestion applied

2023-03-28 09:42 UTC, benoitf commented on packages/main/src/plugin/extension-loader.spec.ts
> +  const rootedFakeDirectory = path.resolve(fakeDirectory);
```suggestion

```

2023-03-28 09:45 UTC, jeffmaury approved these changes
LGTM

2023-03-28 10:05 UTC, merged