feat: add actions to kind clusters in resources page (#1953)
containers/podman-desktop pull request #2008
Opened 2023-04-10 19:28 UTC by lstocchi

### What does this PR do?

Adds start, restart, stop, delete actions to kind cluster in resources page

### Screenshot/screencast of this PR

![start-stop-delete-kind](https://user-images.githubusercontent.com/49404737/230980659-8ec3a978-60d2-43da-b03c-0f651769bf7d.gif)

### What issues does this PR fix or reference?

it resolves #1953

### How to test this PR?

1. settings -> resources -> start, stop, delete a kind cluster

In Draft as i need to add some tests and verify a couple of things

2023-04-10 21:44 UTC, benoitf commented on extensions/kind/src/extension.ts
> +            await extensionApi.containerEngine.startContainer(cluster.engineId, cluster.id);
it can't be containerEngine. We register kube objects

Kubernetes connections are different than containers

2023-04-11 12:40 UTC, jeffmaury requested changes

2023-04-11 12:40 UTC, jeffmaury commented on extensions/kind/src/util.ts
> +    if (result.exitCode === 0) {
Useless test

2023-04-11 12:40 UTC, jeffmaury commented on extensions/kind/src/util.ts
> +        resolve({ exitCode, stdOut, stdErr, error: err });
exitCode is not useful anymore and thus must be removed

2023-04-11 12:40 UTC, jeffmaury commented on extensions/kind/src/util.ts
>        if (result.exitCode === 0) {
Useless test

2023-04-12 06:57 UTC, benoitf commented on extensions/kind/src/util.ts
> +      // ignore
should probably log the error

2023-04-12 07:12 UTC, benoitf approved these changes
I was able to create/stop/start/restart/delete

https://user-images.githubusercontent.com/436777/231380022-369d0fc0-0b69-42be-b835-c88b41b824ae.mp4

2023-04-12 08:59 UTC, benoitf commented
@jeffmaury it seems you requested changes but it looks like it has been addressed

2023-04-12 13:51 UTC, jeffmaury reviewed
Deleting a cluster after being stopped never ends for me

2023-04-12 13:55 UTC, lstocchi commented
> Deleting a cluster after being stopped never ends for me

Do you see any error if you try to run the command from the terminal?

2023-04-12 13:57 UTC, jeffmaury commented
> > Deleting a cluster after being stopped never ends for me
> 
> Do you see any error if you try to run the command from the terminal?

No and the problem is that it never ends

2023-04-12 13:59 UTC, lstocchi commented
> No and the problem is that it never ends

I mean if you run `kind delete clusters <clusterName>` does it work? or is it stuck as well?

2023-04-12 15:35 UTC, jeffmaury approved these changes
LGTM. Delete is ok now

2023-04-12 15:54 UTC, cdrage approved these changes
I tested this on Windows as well as Mac M1 and was able to stop / start / delete the Kind cluster fine.

 I did not encounter any deletion issues that @jeffmaury experienced. Worked perfect on Windows 10 + Mac.

2023-04-12 16:06 UTC, merged