feat: add dialog to set currently running podman machine to default
containers/podman-desktop pull request #2205
Opened 2023-04-24 17:20 UTC by cdrage

feat: add dialog to set currently running podman machine to default

### What does this PR do?

* Creates a dialog / notification that informs the user that the
  currently running podman machine is not set as the default and CLI
  commands will not work with Podman.
* Add buttons to ignore / cancel the notification as well.

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/1322

### How to test this PR?

See video. Otherwise, you can do:

```
podman machine create test-vm
podman system connection default test-vm
# you should see pop up on podman desktop
# to set the default
# use list to see the changes
podman system connection list
```

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-04-26 10:05 UTC, lstocchi approved these changes
Tested, works fine. LGTM

2023-04-26 10:05 UTC, lstocchi commented on extensions/podman/src/extension.ts
> +      // Check that it's still the default machine, if not, we should tell the user to update their CLI.
to be removed?

2023-05-02 17:29 UTC, cdrage commented
@jeffmaury @benoitf need 1 more review :)

2023-05-03 07:45 UTC, benoitf commented
it works but I assume it should notify me if I change the machine even without restarting Podman Desktop

but it should prompt me again only if the default connection is being changed again

2023-05-03 07:48 UTC, benoitf commented
it's also missing a unit test

2023-05-03 14:57 UTC, cdrage commented
> it works but I assume it should notify me if I change the machine even without restarting Podman Desktop
> 
> but it should prompt me again only if the default connection is being changed again

Yup! The check is part of updateMachines, so it'll be done very 5 seconds. 

```
async function monitorMachines(provider: extensionApi.Provider) {
  // call us again
  if (!stopLoop) {
    try {
      await updateMachines(provider);
    } catch (error) {
      // ignore the update of machines
    }
    await timeout(5000);
    monitorMachines(provider);
  }
}
```

If you change the default while on the command line, you'll get the notification again (unless you press "ignore" to dismiss it completely).

2023-05-03 14:57 UTC, cdrage commented
I've gone ahead and added some simple tests for the functionality. 💯

2023-05-04 06:12 UTC, jeffmaury requested changes, later dismissed

2023-05-04 06:12 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +  console.log('defaultMachineNotify: ', defaultMachineNotify);
Should be removed, logs is now full of messages

2023-05-04 14:18 UTC, cdrage commented on extensions/podman/src/extension.ts
> +  console.log('defaultMachineNotify: ', defaultMachineNotify);
Woops! Removed.

2023-05-08 13:43 UTC, cdrage commented
@deboer-tim @benoitf Need 1 more review :)

2023-05-10 19:59 UTC, benoitf approved these changes

2023-05-10 20:06 UTC, benoitf commented
@cdrage if you can fix the conflict

2023-05-11 12:45 UTC, cdrage commented
@benoitf updated the conflict 👍

2023-05-11 14:14 UTC, merged