docs: added _Viewing and selecting the current Kubernetes context_
containers/podman-desktop pull request #2303
Opened 2023-05-02 13:52 UTC by themr0c

refs: https://github.com/containers/podman-desktop/issues/1449

2023-05-03 06:08 UTC, jeffmaury reviewed
Should'nt we have a Windows version of the images and also document how to access the Podman Desktop tray ?

2023-05-08 13:44 UTC, cdrage requested changes, later dismissed

2023-05-08 13:44 UTC, cdrage commented on website/docs/kubernetes/viewing-and-selecting-current-kubernete-context.md
> +- You registered the Kubernetes cluster in your kubeconfig file: _<your_kubernetes_cluster>_. For example, [Creating a kind cluster](kind/creating-a-kind-cluster).
This is a bit confusing? Couldn't we say something like: "You have a Kubernetes context configured within `~/.kube/config` ?

2023-05-10 11:07 UTC, themr0c commented
I wish we would continue beautifying the screenshots in a next iteration.

2023-05-10 18:02 UTC, jeffmaury reviewed
What if the user has no current Kubernetes context. We should add this use case from my POV

2023-05-11 06:57 UTC, themr0c commented
> What if the user has no current Kubernetes context. We should add this use case from my POV

See the prerequisites.

2023-05-11 07:14 UTC, jeffmaury commented
> > What if the user has no current Kubernetes context. We should add this use case from my POV
> 
> See the prerequisites.

The prequisites are also my concern

2023-05-15 09:25 UTC, themr0c commented
> The prequisites are also my concern

Do you mean: we need another procedure: registering a Kubernetes cluster?

2023-05-15 12:41 UTC, jeffmaury approved these changes
After reflection and re reading the title, this use case should be part of another doc

2023-05-15 12:41 UTC, merged