website: intro punchline
containers/podman-desktop pull request #2583
Opened 2023-05-22 12:15 UTC by themr0c

### What does this PR do?

Website intro punchlines.

### Screenshot/screencast of this PR

![Screenshot from 2023-05-22 14:15:28 Selection 783x334 01](https://github.com/containers/podman-desktop/assets/243761/5d917f53-3e86-455e-8c08-9cbd281ad5a7)

### What issues does this PR fix or reference?

### How to test this PR?

2023-05-22 13:27 UTC, deboer-tim requested changes
TBH I prefer the original text. I'm not opposed to rewording, but I think we should keep it to a tagline vs multiple bullets.

2023-05-22 13:27 UTC, deboer-tim commented on website/src/pages/index.tsx
> +            <p className="text-base md:text-lg">Your simplistic onboarding to go from containers up to Kubernetes.</p>
'Simplistic' has the connotation of being overly simplified or naive, would prefer not to use it.

2023-05-22 13:27 UTC, deboer-tim commented on website/src/pages/index.tsx
> +            <p>On your developer environment</p>
Not clear what this means, did you mean 'developer machine'?

2023-05-22 13:27 UTC, deboer-tim commented on website/src/pages/index.tsx
> +            <p>Abstracting away container and Kubernetes tooling configuration</p>
Maybe just 'tool' in this context? Or remove it entirely?

2023-05-22 19:17 UTC, benoitf commented
I don't like as well the 'bullet without bullets' style

2023-05-23 01:30 UTC, mairin commented
(grain of salt: I am not an SEO person at all)

The current slug under the headline is "Podman Desktop is an open source graphical tool enabling you to seamlessly work with containers and Kubernetes from your local environment." I think this is a good approach because the headline is a bit more abstract and high level (containers to kubernetes), and the slug under says what it actually is ("an open source graphical tool")

The new suggestion has this but repeats the headline in different language first, then talks about it being an open source graphical tool. When I first saw it, it just seemed like an overwhelming amount of text - so I think to go with the suggested language changes might require a different layout.

@themr0c is there a specific goal or goals you're trying to target with the suggested changes on this? (for example, SEO :) ) it could help me figure out a potentially better layout. here is an example of how it could be laid out (i made some changes to the text tho so the layout would work and tried to account for @deboer-tim 's feedback)

(I worry about this one though because doesnt state clearly upfront what Podman Desktop is)
![Screenshot from 2023-05-22 21-19-30](https://github.com/containers/podman-desktop/assets/799683/ac7e7ff3-283e-450c-aa2e-726ae115cfe9)

2023-06-12 07:38 UTC, benoitf commented
closing due to lack of activity, could be reopened

2023-06-12 07:38 UTC, closed without merging