feat: Add Minikube documentation
containers/podman-desktop pull request #2694
Opened 2023-05-30 21:00 UTC by afbjorklund

### What does this PR do?

This is the documentation for the minikube extension. It is rather similar to the "kind" extension.

Both Kubernetes extensions share a lot of concepts, even though the commands differ slightly.

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

* #2610

### How to test this PR?

* #2646

Note for reviewer: this "minikube" documentation should be compared with the existing "kind" documentation:

* https://podman-desktop.io/docs/kubernetes/kind

2023-05-31 15:17 UTC, benoitf commented
cc @themr0c

2023-06-02 19:10 UTC, benoitf commented
would be nice if we could merge some items to maybe avoid duplication but can be done as a next thing once it'll be merged. 
Need to have the extension in its own repository before merging here

2023-06-08 16:59 UTC, afbjorklund commented
Now available:

`ghcr.io/containers/podman-desktop-extension-minikube`

2023-06-09 14:10 UTC, cdrage requested changes
Thanks for the awesome documentation! I only have a few comments.

Also, minikube on all official documentation (github, https://minikube.sigs.k8s.io/docs/) is stylized as lowercase `minikube` not `Minikube`. 

Unsure of the english on it, but I think minikube should be lowercase on all references? Just a small nitpick. I just remember docs teams sometimes being very specific on whether or not something is capitalized. Like how crc is not Crc and minishift is Minishift, and then microshift is MicroShift. Just a thought

2023-06-09 14:10 UTC, cdrage commented on website/docs/kubernetes/minikube/configuring-podman-for-minikube-on-windows.md
> +- Requires the rootful machine.
```suggestion
- Requires a rootful machine.
```

2023-06-09 14:10 UTC, cdrage commented on website/docs/kubernetes/minikube/pushing-an-image-to-minikube.md
> +You can also create a Pod that uses the loaded image.
```suggestion
You can also create a Pod that uses the loaded image:
```

2023-06-09 14:10 UTC, cdrage commented on website/docs/kubernetes/minikube/restarting-your-minikube-cluster.md
> +Therefore, Podman Desktop stops the Minikube cluster, starts it again, and hopes for the best.
Should we remove the "hopes for the best" part?

2023-06-09 14:10 UTC, cdrage commented on website/docs/kubernetes/minikube/restarting-your-minikube-cluster.md
> +Therefore, Podman Desktop stops the Minikube cluster, starts it again, and hopes for the best.
The three sentences can be "Minikube has no command to restart a cluster, so you can: blahblah"

2023-06-10 07:37 UTC, afbjorklund commented
I think it used to be a thing also in minikube, but I'm not sure it actually matters to anyone anymore...

Trying to spell things like CRC or CRI-O seem to always end up failing anyway.

2023-06-10 07:46 UTC, afbjorklund commented
> Thanks for the awesome documentation! I only have a few comments.

Note that since most of this Kubernetes documentation has been duplicated from the Kind-specific section, most of the things being addressed applies also to _that_ original documentation. Maybe they could be merged, in the future?

 
Example:
```diff
-# Configuring Podman for Kind on Windows Subsystem for Linux (WSL)
+# Configuring Podman for Minikube on Windows Subsystem for Linux (WSL)
 
 When you create a Podman machine, Podman creates the machine in rootless mode.
 
-With a Podman machine running on WSL, Kind:
+With a Podman machine running on WSL, Minikube:
 
 - Requires the rootful machine.
 ```

2023-06-12 07:44 UTC, benoitf approved these changes

2023-06-12 07:44 UTC, merged

2023-06-12 09:17 UTC, afbjorklund commented
@benoitf : thanks, will you add some instructions on how to install the minikube extension ?

https://podman-desktop.io/docs/extensions/install

2023-06-12 09:29 UTC, benoitf commented
@afbjorklund we could replace the placeholder on https://podman-desktop.io/docs/extensions/install being quay.io/fbenoit/my-first-extension by the minikube extension
but we're still missing in extension page the list of ALL extensions, not only featured extensions

2023-06-12 09:44 UTC, afbjorklund commented
I was thinking there needs to be a link from the minikube docs, until the featured (or catalog) is in place

2023-06-12 09:48 UTC, benoitf commented
@afbjorklund yes it does not prevent to have links