feat(tests): add navigation bar e2e tests
containers/podman-desktop pull request #2950
Opened 2023-06-21 16:05 UTC by odockal

### What does this PR do?
Adds new e2e tests - navigation bar tests.
Next steps are to divide tests into separate files and make sure that we can have various suites - smoke/full.
### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?
remove `settings.json` or `telemetry.*` and `welcome.version` keys
settings file is in `~/.local/share/containers/podman-desktop/configuration`
```
yarn install
yarn run test:e2e:smoke
```

2023-06-21 18:23 UTC, cdrage approved these changes
LGTM! Thanks for adding more tests. Was able to run this locally and it passed + this also is passing on CI.

2023-06-21 18:54 UTC, benoitf requested changes
need to use roles/aria labels

2023-06-21 18:54 UTC, benoitf commented on tests/src/e2e.spec.ts
> +    test('Verify are present in Navigation Bar', async () => {
Is a word missing like 'verify entries'

2023-06-21 18:54 UTC, benoitf commented on tests/src/e2e.spec.ts
> +      const navBar = page.locator('nav[aria-label="Global"]');
we need a proper role here, this on is too fragile

2023-06-21 18:54 UTC, benoitf commented on tests/src/e2e.spec.ts
> +        const locator = navBar.locator(`a[aria-label="${item}"]`);
locator is too fragile

2023-06-21 19:49 UTC, odockal commented on tests/src/e2e.spec.ts
> +      const navBar = page.locator('nav[aria-label="Global"]');
I think that by definition this is a proper role, moreover denoted by aria-label attribute. You can have an HTML element with concrete aria based attribute, ie: `<span role="link">` or preferred way: `<a ...>`. HTML 5 based elements should be already accepted as ARIA supported elements. Both should be searchable by using `page.getByRole()`, although I am not sure about what exactly is constructed in the selector here (`page.locator(selector)`), that is true, will need to dig more.

2023-06-21 19:59 UTC, benoitf commented on tests/src/e2e.spec.ts
> +      const navBar = page.locator('nav[aria-label="Global"]');
let's rename aria-label "Global" into AppNavigation in AppNavigation.svelte and "Global" from PreferencesNavigation.svelte to "PreferencesNavigation"

then you could do just page.getByRole('navigation', {name: "AppNavigation"}); I suppose

2023-06-21 19:59 UTC, benoitf commented on tests/src/e2e.spec.ts
> +        const locator = navBar.locator(`a[aria-label="${item}"]`);
should be a 'link' role with name being the name of the aria-label (like Containers)

2023-06-22 04:27 UTC, odockal commented on tests/src/e2e.spec.ts
> +      const navBar = page.locator('nav[aria-label="Global"]');
Sure thing.

2023-06-22 11:30 UTC, odockal commented on tests/src/e2e.spec.ts
> +      const navBar = page.locator('nav[aria-label="Global"]');
https://github.com/containers/podman-desktop/pull/2968

2023-06-22 15:24 UTC, odockal commented
@benoitf rebase and changed after linked PR was merged.

2023-06-22 15:27 UTC, benoitf approved these changes
👍

2023-06-22 19:34 UTC, merged