fix: update nodejs version to 18 in .nvmrc to fix yarn install failure
containers/podman-desktop pull request #2989
Opened 2023-06-23 17:26 UTC by dgolovin

### What does this PR do?

Fixing `yarn install` error:

```
eskimo@mac1 podman-desktop % nvm use 
Found '/Users/eskimo/Sources/podman-desktop/.nvmrc' with version <16>
Now using node v16.19.0 (npm v9.6.7)
eskimo@degolovi-mac podman-desktop % yarn install
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "trim@0.0.3" is incompatible with requested version "trim@0.0.1"
[3/5] 🚚  Fetching packages...
warning compose@0.0.1: The engine "podman-desktop" appears to be invalid.
warning docker@0.0.1: The engine "podman-desktop" appears to be invalid.
warning kind@0.0.1: The engine "podman-desktop" appears to be invalid.
warning kube-context@0.0.1: The engine "podman-desktop" appears to be invalid.
warning lima@0.0.1: The engine "podman-desktop" appears to be invalid.
warning podman@0.0.1: The engine "podman-desktop" appears to be invalid.
warning registries@0.0.1: The engine "podman-desktop" appears to be invalid.
error @octokit/graphql@6.0.1: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Run commands below

```
1. cd podman-desktop
2. nvm use
3. yarn install
```

2023-06-23 17:53 UTC, deboer-tim approved these changes

2023-06-23 18:46 UTC, benoitf commented
Issue is https://github.com/containers/podman-desktop/issues/2955
I think package.json should be updated as well

2023-06-26 07:05 UTC, benoitf requested changes
thanks @dgolovin 🎉 if you could fix the line in package.json as well

2023-06-26 19:25 UTC, benoitf approved these changes
thanks @dgolovin

2023-06-26 22:14 UTC, merged