feat: added e2e test for pulling the podman hello image
containers/podman-desktop pull request #3006
Opened 2023-06-26 13:01 UTC by themr0c

### What does this PR do?

feat: added e2e test for pulling the podman hello image

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?

1. Test is passing:

```
$ xvfb-maybe  vitest run tests/src/e2e.pull-the-podman-hello-image.spec.ts

RUN  v0.32.2 /home/ffloreth/src/gh/themr0c/podman-desktop

stdout | unknown test
Cleaning up output folder...

 ✓ tests/src/e2e.pull-the-podman-hello-image.spec.ts (12) 29690ms

 Test Files  1 passed (1)
      Tests  12 passed (12)
   Start at  14:56:05
   Duration  33.24s (transform 318ms, setup 0ms, collect 510ms, tests 29.69s, environment 779ms, prepare 508ms)
```

2. Screenshots and videos of the test results are generated in the `tests/output/pull-the-podman-hello-image/ directory.

```
ls tests/output/pull-the-podman-hello-image/ -1
3f3f326725e509b3dd29aa016e94fa02.webm
60963c839fb2d19febe5d1e7bd8139b9.webm
screenshot-dashboard.png
screenshot-image-details-inspect.png
screenshot-image-details-summary.png
screenshot-images-found-quay-io-podman-hello.png
screenshot-images.png
screenshot-images-pulled.png
screenshot-pull-image-from-a-registry.png
screenshot-pull-quay-io-podman-hello-image-from-a-registry.png
```

2023-06-26 13:55 UTC, benoitf reviewed
as reported on many e2e tests, the locators need to be robust/strong to really find the element and not another element.

Then, it should almost all the time use the 'roles' to ensure we have proper a11y and they lead to less changes across multiple revisions

2023-06-26 13:56 UTC, benoitf requested changes
tests may be executed on fresh install so there is a welcome page

2023-06-26 14:17 UTC, themr0c commented
> tests may be executed on fresh install so there is a welcome page

Can it be invoked as a dependency? "the welcome page test has been run before, therefore the welcome page does not appear again"?

2023-06-26 14:36 UTC, odockal commented
> > tests may be executed on fresh install so there is a welcome page
> 
> Can it be invoked as a dependency? "the welcome page test has been run before, therefore the welcome page does not appear again"?

You can add simple workaround that will work out if there is welcome page , something like [here].

[here]: https://github.com/containers/podman-desktop/pull/3008/files#diff-7458643ba52cac7fef38261b84b9ef3027b0be64930943538b96d989dd1a604cR36

Once we have mutliple such requirement, we can extract them into more proper place, requirements or utils or something similar.

2023-06-27 07:12 UTC, odockal commented
@benoitf  @themr0c  I would suggest to start with https://github.com/containers/podman-desktop/pull/3008 first. We then can add another type of suite for this kind of tests.

2023-07-14 12:54 UTC, closed without merging