docs: update system requirements
containers/podman-desktop pull request #3089
Opened 2023-07-03 10:04 UTC by themr0c

### What does this PR do?

Updated outdated in the troubleshooting guide. Set a minimal version for Podman.

Note: I chose 4.1 because it is the first version fixing the mentioned issue. It might require an update to a newer version.

### What issues does this PR fix or reference?

refs: #3045

2023-07-03 10:08 UTC, benoitf commented on website/docs/troubleshooting.md
> +- Use Podman version 4.1 or greater.
you can't remove from one side without adding it at another side I would say

the information `On Windows, the named pipe is `//./pipe/docker_engine` when Docker Desktop is not installed` is really important, so people can check if it exists, etc

2023-07-03 10:11 UTC, themr0c commented on website/docs/troubleshooting.md
> +- Use Podman version 4.1 or greater.
Do the user need to know and care now that the issue is solved?

2023-07-03 14:53 UTC, afbjorklund commented
What are the major blockers for running with Podman v3 ?

2023-07-06 07:06 UTC, benoitf commented on website/docs/troubleshooting.md
> +- Use Podman version 4.1 or greater.
so as a user you may not care about how the issue is solved but you're interested in knowing which npipe is used

2023-07-06 07:07 UTC, benoitf commented
I think there is no blocker for podman v3 as long as you're on Linux and don't use machines. (I would say most of Linux users don't use podman machines)
Most of the required changes have been done on the 'machine side'

2023-07-13 08:33 UTC, jeffmaury requested changes

2023-07-13 08:33 UTC, jeffmaury commented on website/docs/troubleshooting.md
> +- Use Podman version 4.1 or greater.
Agree we should either document if user has Podman >= 4.0.2 and < 4.1 that Docker Desktop should be started (rather that installed) or switch to Podman 4.1+

2023-07-14 12:55 UTC, closed without merging