nit: change wording from started to enabled / etc.
containers/podman-desktop pull request #3100
Opened 2023-07-04 15:36 UTC by cdrage

nit: change wording from started to enabled / etc.

### What does this PR do?

For providers it makes sense to have starting / stopping / stopped.

For extensions, it should be enable / disable / enabling / disabling
since they are extensions that you turn off and on, not something that
is "running" in the background.

Using the starting / stopping / stopped terms for extensions is
confusing.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/e8914923-e19b-4dd2-bad7-ab35dd7251fe

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/2534
Closes https://github.com/containers/podman-desktop/issues/2379

### How to test this PR?

Go to extensions page, you should now see enable / disable rather that
start / stop.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-07-04 15:37 UTC, cdrage commented
NOTE:

This does NOT change the underlying statuses "starting / stopping / started / stopped" because it is used a lot within the code.

This only changes the UI / GUI aspect so it makes more sense for extensions to be using enabled / disabled rather than start / stop similar to providers.

2023-07-05 10:13 UTC, jeffmaury requested changes
Still have an issue for provider as ConnectionStatus is shared

![image](https://github.com/containers/podman-desktop/assets/695993/a3099eee-7851-4ef5-a417-b388dbfae829)

2023-07-05 16:21 UTC, cdrage commented
> Still have an issue for provider as ConnectionStatus is shared
> 
> ![image](https://user-images.githubusercontent.com/695993/251117460-a3099eee-7851-4ef5-a417-b388dbfae829.png)

Ah, you are right. I thought it wouldn't change.

I've updated the PR with a new file called ExtensionStatus that we can use instead for the Extensions section, but the provider section will stay the same.

2023-07-06 07:26 UTC, jeffmaury approved these changes
LGTM

2023-07-10 13:11 UTC, cdrage commented
Going to merge this in as there's been a LGTM and it's a small change!

2023-07-10 13:11 UTC, merged