feat: Close details page if object is deleted
containers/podman-desktop pull request #3228
Opened 2023-07-14 15:00 UTC by deboer-tim

### What does this PR do?

Automatically closes a details page when the object you're looking at gets deleted.

Added a close() function on DetailsPage so that child pages do not need to import lastPage and router. This means they do need to bind DetailsPage, but that seemed like simpler logic/less dependencies to me.

Each page just checks if they had the object before and can no longer find it. If it is gone, close the page.

This change was meant to handle external deletion, but once it is in there is no longer a need for any of the delete actions to call router.goto() when the user triggers deletion, so these can be removed. If the user triggers the action from a page like Images the goto wasn't doing anything, and if they are in Image Details this new mechanism will do the same thing and revert to the previous page.

The pods page was unsubscribing the listener, but I've switched it to return the unsubscribe so the destroy is handled by Svelte - no need for onDestroy() or imports. The other three pages weren't unsubscribing the listener, so I've fixed that by adding a return statement.

The redirectAfterDelete from PR #2963 can also be cleaned up. Plus, we get a minor bug fix b/c if you went from Containers > Pod Details and delete the pod it will now correctly go back to Containers instead of Pods.

The PodActions test will fail because it is checking for the explicit redirect when a pod (that's not registered) gets deleted. Putting this up to start review of the rest and decide if we just delete the test or these is something else I can do.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #3217.

### How to test this PR?

Create and delete lots of things! Take various paths in the UI, try deleting from the lists or details page, and try deleting from the command line as well.

2023-07-17 08:01 UTC, jeffmaury requested changes, later dismissed
Seems unit test needs an update

2023-07-18 10:17 UTC, benoitf reviewed
it looks like there are no tests that check the page is closed if store is being updated and object is missing ?

we apply the pattern if (!data && !newData && detailsPage) on every component and need to keep a new value

I am wondering if we could not have a generic way instead of copying/pasting the same logic across all items ?

like we provide the item to detailsPage or the updated list and it's the detailsPage widget that check if item is gone and perform the close

2023-07-20 12:55 UTC, deboer-tim commented
Rebased and pushed simpler logic for each of the *Details.svelte pages. We can't bind a variable b/c the page doesn't exist during onMount, and use of `{#if volume}` means the component is removed before bindings update, but I think this is simpler and avoids use of `if (!data && !newData ...)`.

2023-07-20 14:06 UTC, benoitf approved these changes

2023-07-20 18:25 UTC, cdrage approved these changes
Tested, works, code LGTM!

2023-07-24 07:32 UTC, benoitf commented
@jeffmaury could you check if you required changes have been fixed ?

2023-07-26 07:29 UTC, benoitf commented
@deboer-tim it seems one test is not passing

2023-07-26 20:17 UTC, deboer-tim commented
> @deboer-tim it seems one test is not passing

The existing test was checking that the action triggered the router (when it is configured to do it). Now that this would be handled via the event, I haven't found any way to easily mock being on different UI screens and having the delete trigger an event to confirm whether the router was triggered... so for now, I've just removed the invalid part of the test.

2023-07-26 20:24 UTC, benoitf commented
I still believe we need a test to ensure that we're redirected so it works as expected
else it can be easily broken.
I could check how we could do mocks

2023-07-30 18:21 UTC, benoitf commented
@deboer-tim I've added a test for removing pod in this PR

https://github.com/containers/podman-desktop/pull/3228/commits/dffed05d4db1678b192b697c0af1f343a2384f20

I think you can mimic that and add tests for other pages `ContainerDetails` , `ImagesDetails` and `VolumeDetails`

2023-07-31 16:20 UTC, deboer-tim commented
Thanks @benoitf ! That is beyond what I understood how to mock and much appreciated.

I've added corresponding tests for volume, image, and container details following the same pattern.

2023-07-31 16:21 UTC, benoitf approved these changes

2023-07-31 18:12 UTC, merged