chore: make contour file available offline
containers/podman-desktop pull request #3452
Opened 2023-08-08 08:37 UTC by odockal

### What does this PR do?
Includes option to use locally stored contour.yaml file using env. var when building kind extension.
### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
#2248 

### How to test this PR?
`CONTOUR_SKIP_DOWNLOAD=true yarn build:extensions:kind`
Check that file exists on path `extensions/kind/src-generated`
`yarn test:extensions:kind`

One could also try to build kind locally to get file downloaded from github, rename it and then build locally using env. var and compare such file with previously downloaded one.

2023-08-08 08:42 UTC, benoitf commented
Might be easier to just have the file there, not download it each time. And the script to fetch it/update it (like dependabot/renovate to update the file when there is a new contour version)

b/c here I don't see the benefit of downloading it ?

@jeffmaury what is your feedback ?

2023-08-08 09:31 UTC, jeffmaury requested changes
Seems to me that your changed the location of the contour.yaml file but the code has not been updated

2023-08-08 10:53 UTC, odockal commented
@jeffmaury The local yaml file is decoded and saved to the same location as when downloading. So the location does not change at that end, I also do not have to change vite config module '@gen' this way.

2023-08-08 13:14 UTC, jeffmaury commented
After discussion with @benoitf this PR should be rewritten so that:

- contour file is now part of the source tree and code should be updated so use that file (moved from src-generated to src)
- download script should be updated so that it is now used to update the file in the source tree
- download script should not be called automatically
- src-generated should be removed

2023-08-09 11:07 UTC, odockal commented
@jeffmaury @benoitf I have updated the PR and also a PR description -> should have updated steps to verify. I would also like to test the actual functionality of the contour ingress node by building app locally and testing it with a deployment of some app but my laptop is somehow messed today - so I only get too many open files on the log of the app deployed to the kind cluster and cannot check app is available on the `localhost:9090`.

2023-08-09 16:14 UTC, jeffmaury requested changes
.gitignore should be deleted

2023-08-10 07:19 UTC, jeffmaury approved these changes
LGTM

2023-08-10 07:51 UTC, benoitf commented
FYI @dgolovin @cdrage I don't know who will do the release but with that PR being merged

https://github.com/flathub/io.podman_desktop.PodmanDesktop/blob/master/io.podman_desktop.PodmanDesktop.yml#L65-L66

and https://github.com/flathub/io.podman_desktop.PodmanDesktop/tree/master/patches folder will need to be removed when updating flatpak repository for cutting the flatpak release.

2023-08-10 07:52 UTC, benoitf commented on extensions/kind/scripts/download.ts
> +// partiullar contour file should be manually added to the repo once downloaded
```suggestion
// particular contour file should be manually added to the repo once downloaded
```

2023-08-10 07:53 UTC, benoitf approved these changes
there is a typo but it does not prevent the approval

2023-08-10 09:43 UTC, odockal commented
@benoitf @jeffmaury thanks for review, I have enabled automerge and fixed typo by suggestion. thx

2023-08-10 10:16 UTC, merged