chore(tests): include junit,verbose reporters and junit report output…
containers/podman-desktop pull request #3453
Opened 2023-08-08 08:53 UTC by odockal

… file

### What does this PR do?
Adds new reporter (junit) and verbose one, which should mostly be valuable when there are tests failures. It also produces a junit report xml file under `tests/output`, it does not introduce any new location or anything. It can be processed on CI then.

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
#3292 

### How to test this PR?
`yarn test:e2e:smoke` -> there will be `tests/output/junit-results.xml` file with all test cases results.

2023-08-08 09:11 UTC, benoitf requested changes
the default reporter is much more easier for development as it collapse suites when they pass

I guess here it's a matter of personal preference 

I suspect we need to find a way to allow people choose their reporter without changing for all person

`yarn run test:e2e:smoke --reporter junit` is not working ?

2023-08-08 10:51 UTC, odockal commented
> the default reporter is much more easier for development as it collapse suites when they pass
> I guess here it's a matter of personal preference

Totally agree. I would just like to emphasize that we are talking only about e2e tests here.

Cli should work as well.

If we change reporters to 'default' and 'junit' with an outputfile definition for junit reporter, log output will stay the same and just junit file will be generated. 

so this one could be ok:
```
    reporters: ['default', 'junit'],
    outputFile: { junit: 'tests/output/junit-results.xml' },
```

Or this with a CI env. var taken into account:
```
    reporters: ['default', process.env.CI ? 'junit' : ''],
    outputFile: process.env.CI ? { junit: 'tests/output/junit-results.xml' } : {},
```

2023-08-08 11:19 UTC, benoitf commented
if you need these results only for CI, yes the later option seems to be the better

2023-08-08 12:46 UTC, benoitf commented on vitest.config.js
> +    reporters: ['default', process.env.CI ? 'junit' : ''],
does it work with an empty reporter ?

without ci it will do ['default', '']

2023-08-08 15:06 UTC, odockal commented on vitest.config.js
> +    reporters: ['default', process.env.CI ? 'junit' : ''],
Seems yes!
![Screenshot_20230808_165906](https://github.com/containers/podman-desktop/assets/19164299/f5c49525-d460-45d0-b6ea-e3c984e3c3f3)

But it does not look good, I agree. Changed to readable form without empty reporter.

2023-08-09 20:58 UTC, benoitf approved these changes

2023-08-09 20:58 UTC, benoitf commented
thanks

2023-08-09 21:26 UTC, odockal commented
@benoitf Hm, I was checking the file available on GHA, it contains totally unrelated test results. so I am back to investigate what is going on.

2023-08-09 21:56 UTC, odockal commented
@benoitf I have noticed two more issues with reporter and e2e tests config, first: `tools` folder was included in vitest.config and so I updated included files and second, there was same name for artifact saved for whole workflow file. Overlapping names. Will check results.

2023-08-10 06:04 UTC, odockal commented
@benoitf E2e test artifact archive now contains right junit.xml file. Contains just e2e test results.

2023-08-10 07:42 UTC, benoitf commented
There is now a unit-test artifact with 0 bytes so somehow either we need to publish something or we don't create the artifact ?

![Screenshot 2023-08-10 at 09 41 16](https://github.com/containers/podman-desktop/assets/436777/81c6607d-3e1d-4879-b996-520b2e3684ad)

2023-08-10 13:10 UTC, odockal commented
@benoitf true, removing unit tests archive artifacts step. For now I do not see a point why to store result from unit tests, wdyt?

2023-08-10 13:11 UTC, benoitf approved these changes

2023-08-10 13:37 UTC, merged