fix: only restart if a machine is running
containers/podman-desktop pull request #3491
Opened 2023-08-10 18:48 UTC by cdrage

fix: only restart if a machine is running

### What does this PR do?

No matter what, it would try to restart regardless if a machine was
running or not.

This is because the if statement was: `if (isRunning !== '')` which will
always return true even if isRunning was undefined.

The if statement has now been changes to `if (isRunning)` meaning it
will only run if isRunning is defined (not '').

### Screenshot/screencast of this PR

N/A. The prompt will not appear when trying to restart it if there is no
machine running.

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3321

### How to test this PR?

Click on Docker Compatibility with a Podman Machine stopped. You should
not get the prompt to restart the podman machine.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-08-10 20:29 UTC, deboer-tim commented
findRunningMachine() says it returns a boolean, maybe fix that too?

2023-08-11 15:48 UTC, cdrage commented
Ready for review! 💯 had to figure out what was happening inside the tests and then realized it wasn't being mocked correctly (even for an old test too).

Updated and ready 👍

2023-08-12 02:36 UTC, dgolovin approved these changes
Verified on mac and it works for me now. No requests to restart machine if it does not exist or is not started.

disable() and enable() functions can be improved (optional).

LGTM

2023-08-12 02:36 UTC, dgolovin commented on extensions/podman/src/compatibility-mode.ts
> +    if (isRunning) {
This is code duplication.

```
    const isRunning = await findRunningMachine();
    if (isRunning) {
      await this.promptRestart(isRunning);
    }

    return Promise.resolve();
```

Let's move check for machine name inside of promptRestart method.

After that we can rewrite the method as

```
  async enable(): Promise<void> {
    await this.runCommand('install', 'enabled')

    // Prompt the user to restart the podman machine if it's running
    return findRunningMachine().then(machine => this.promptRestart(machine));
  }
```

2023-08-12 02:36 UTC, dgolovin commented on extensions/podman/src/compatibility-mode.ts
> +    if (isRunning) {
Changes for enable() method can be applied to disable() method too.

2023-08-14 17:05 UTC, cdrage commented
Thank you for the suggestion @dgolovin ! Totally makes the code a lot cleaner. Pushed your suggestion 👍

2023-08-14 17:47 UTC, cdrage commented
@dgolovin 

Unfortunately `return findRunningMachine().then(machine => this.promptRestart(machine));` does not work compared to:

```
    const isRunning = await findRunningMachine();
    if (isRunning) {
      await this.promptRestart(isRunning);
    }

    return Promise.resolve();
```

As even when it returns undefined in findRunningMachine, promptRestart is still ran in the function: `return findRunningMachine().then(machine => this.promptRestart(machine));`

If you replace the code, you'll see that the tests now fail.

I've updated the code back to the previous change.

2023-08-14 23:21 UTC, dgolovin requested changes
@cdrage I was suggesting to do [this](https://github.com/cdrage/podman-desktop/pull/7/files) as a fix.

Please remove at least

```
return Promise.resolve();
```

it is not needed and result is going to be the same.

2023-08-15 00:01 UTC, cdrage commented
> @cdrage I was suggesting to do [this](https://github.com/cdrage/podman-desktop/pull/7/files) as a fix.
> 
> Please remove at least
> 
> ```
> return Promise.resolve();
> ```
> 
> it is not needed and result is going to be the same.

Hi, I commented on the PR. Bit confused on `return Promise.Resolve` suggestion, it's added to the tests in order to mock the functionality.

2023-08-15 15:40 UTC, cdrage commented
@dgolovin Ready for another review / I've pushed your changes! :)

2023-08-16 14:12 UTC, cdrage commented
Getting some weird errors with smoke testing @odockal @dgolovin any ideas? Rebased + it works fine with `yarn watch`, but unsure why it's causing these tests to fail.

2023-08-17 13:59 UTC, cdrage commented
Tests pass now 💯

2023-08-23 15:05 UTC, dgolovin approved these changes

2023-08-29 14:11 UTC, merged