feat: adding kind.cluster.creation.image configuration property for kind cluster
containers/podman-desktop pull request #3508
Opened 2023-08-11 15:20 UTC by axel7083

### What does this PR do?

The node's container image can be used to specify the Kubernetes version used for the control-planed. For example using `kindest/node:v1.25.8` will create a cluster with Kubernetes 1.25.8.

### Screenshot/screencast of this PR

**Default creation page**

![image](https://github.com/containers/podman-desktop/assets/42176370/a70b79f9-278e-4f81-a5bc-0c34997110a7)

**Custom image creation page**

![image](https://github.com/containers/podman-desktop/assets/42176370/6486e0e2-49eb-4bc0-be00-9c0c43df2cfc)

**Custom image without sha256**

As explained in the official kind documentation
> You can set a specific Kubernetes version by setting the node’s container image. You can find available image tags on the [releases page](https://github.com/kubernetes-sigs/kind/releases). Please include the @sha256: [image digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier) from the image in the release notes

![image](https://github.com/containers/podman-desktop/assets/42176370/b2a63faf-629f-436d-8496-7c0cd8158679)

### What issues does this PR fix or reference?

Allows to create Kubernetes cluster with specific version.

### How to test this PR?

- [x]: added and changed unit tests for validating the changes.
- [x]: tested to created a cluster with `kindest/node:v1.27.2`

2023-08-11 15:23 UTC, benoitf commented
hello @axel7083 and thanks for the contribution

I'm wondering if instead of having to specify the image we could not specify the version with a dropdown ?

like 1.21, 1.22, ... 1.27 and then it's the extension that picks up the right image ?

2023-08-11 15:28 UTC, axel7083 commented
> hello @axel7083 and thanks for the contribution
> 
> I'm wondering if instead of having to specify the image we could not specify the version with a dropdown ?
> 
> like 1.21, 1.22, ... 1.27 and then it's the extension that picks up the right image ?

I was hesitant to do that instead, but maybe some people would want to use custom image, and making a dropdown force use to ask which version do we support ? How far do we go under the minor version ? Some version go from X.X.0 to X.X.11, that would be very long dropdown. If we select only major version, people could desire to have more control over the version used.

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/src/templates/create-cluster-conf.mustache
> +  {{{ extraConfig }}}
it's like a pandora box if it's extra config here

it should probably only insert the image field if it's defined.

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +  if (image !== undefined && image.length > 0) {
```suggestion
  if (image) {
```

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +    extraConfig = 'image: ' + image;
controllerPlaneImage = image (not a generic extraConfig as anyway it's extra only for the contro plane where you inserted it)

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/package.json
> +        "kind.cluster.creation.image": {
maybe name it controlPlaneImage

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +export function getKindClusterConfig(clusterName: string, httpHostPort: number, httpsHostPort: number, extraConfig: string) {
provides the controlPlaneImage field (not generic extra config)

2023-08-11 15:42 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +export async function connectionAuditor(provider: string, image?: string): Promise<AuditResult> {
I would pass all items as parameter but check only for a given parameter inside the function (so if someone need to verify another parameter we don't change the signature of the method)

2023-08-11 15:47 UTC, benoitf commented
> I was hesitant to do that instead, but maybe some people would want to use custom image, and making a dropdown force use to ask which version do we support ? How far do we go under the minor version ? Some version go from X.X.0 to X.X.11, that would be very long dropdown. If we select only major version, people could desire to have more control over the version used.

Yes there is simplicity over configurability here.

maybe 2 fields like one for the lazy people and another for the 'custom' value

one dropdown with `latest`, then some recent major versions like `1.27`, `1.26` and then you have `custom` where it'll use the field that you're using

it's not blocking the PR, just that I think from usability, just selecting `1.26` or `1.27` is easier than going to an external site, looking for a string, copy pasting and coming back to enter the value.

2023-08-11 15:50 UTC, benoitf submitted a review, later dismissed
thanks for the awesome contrib, if you could take some remarks (specific field for mustache template rather than extraConfig, all parameters in the audit function, and maybe prefix image by controlPlane

2023-08-11 15:57 UTC, axel7083 commented
> > I was hesitant to do that instead, but maybe some people would want to use custom image, and making a dropdown force use to ask which version do we support ? How far do we go under the minor version ? Some version go from X.X.0 to X.X.11, that would be very long dropdown. If we select only major version, people could desire to have more control over the version used.
> 
> Yes there is simplicity over configurability here.
> 
> maybe 2 fields like one for the lazy people and another for the 'custom' value
> 
> one dropdown with `latest`, then some recent major versions like `1.27`, `1.26` and then you have `custom` where it'll use the field that you're using
> 
> it's not blocking the PR, just that I think from usability, just selecting `1.26` or `1.27` is easier than going to an external site, looking for a string, copy pasting and coming back to enter the value.

I was not able to find a way to disable a field based on item value.
Based on your suggestion, a dropdown with major version, and a latest and custom. When custom is selected, having a text field shown or enable to let the user write in it. 

How to made such mechanism with the existing system ?

The configuration does not really allows some kind of conditions

https://github.com/containers/podman-desktop/blob/2dbcb14517e38f956ee3ee7b8599fb44a33bda25/packages/main/src/plugin/configuration-registry.ts#L51-L66

And I was not able to find a way to change dynamically those value. If you know any way of doing it I would appreciate !

2023-08-11 16:06 UTC, benoitf commented
for now you won't have a dynamic field that will be displayed (it will be like 2 fields)

select your version

If other, please specify the image name

(you can report error in the audit part like if I select latest but add an image in the other field)


this PR https://github.com/containers/podman-desktop/pull/3251/files will bring a when clause so it's nice to be able to show/hide fields

Maybe with that, we could have in the audit field, a set of a property that then display the field

you can also focus on the custom image in this PR and in a later PR (or not) have dropdown / when clause, etc.

2023-08-11 16:19 UTC, axel7083 commented
> for now you won't have a dynamic field that will be displayed (it will be like 2 fields)
> 
> select your version
> 
> If other, please specify the image name
> 
> (you can report error in the audit part like if I select latest but add an image in the other field)
> 
> this PR https://github.com/containers/podman-desktop/pull/3251/files will bring a when clause so it's nice to be able to show/hide fields
> 
> Maybe with that, we could have in the audit field, a set of a property that then display the field
> 
> you can also focus on the custom image in this PR and in a later PR (or not) have dropdown / when clause, etc.

Okey I would rather for this PR to focus on the  custom image and having a dropdown with some major version later when the PR about the when condition will be merged.

2023-08-11 16:21 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +export function getKindClusterConfig(clusterName: string, httpHostPort: number, httpsHostPort: number, controlPlaneImage: string | undefined) {
```suggestion
export function getKindClusterConfig(clusterName: string, httpHostPort: number, httpsHostPort: number, controlPlaneImage?: string) {
```

2023-08-11 16:22 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +  }
```suggestion
  const controlPlaneImage = params['kind.cluster.creation.controlPlaneImage'];
```

2023-08-11 16:26 UTC, benoitf commented
thanks @axel7083 it looks nice, I will do additional tests but I won't probably merge new stuff a late Friday :-)

2023-08-11 16:29 UTC, axel7083 commented
> thanks @axel7083 it looks nice, I will do additional tests but I won't probably merge new stuff a late Friday :-)

Yeah no worries

2023-08-11 16:35 UTC, benoitf commented
@axel7083 so it looks you'll need to tweak the code to match the styles (you can check that using yarn format:check and yarn lint:check (the PR check is failing)

these checks are also performed automatically when committing so you should have somehow them disabled :-)

2023-08-11 16:37 UTC, benoitf commented on extensions/kind/src/create-cluster.spec.ts
> +  const conf = getKindClusterConfig(null, null, null, '');
you need to use `undefined` instead of `null` we're blacklisting the usage of `null` in the codebase

2023-08-11 16:37 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +  if(image && !image.includes("@sha256:")) {
```suggestion
  if(image && !image.includes('@sha256:')) {
```

this kind of issue is solved running `format:fix` and `lint:fix` rules (yarn)

2023-08-11 17:06 UTC, benoitf commented
@axel7083 it's missing 'fotmat:fix'

do you have husky setting up properly the got hooks ? as you shouldn't be able to push commits without proper formatting

2023-08-14 11:14 UTC, benoitf commented on extensions/kind/src/create-cluster.ts
> +
we should add all records together and not return the first one available

something like
```ts
 const records: AuditRecord[] = [];
  const auditResult = {
    records: records,
  };
  const image = items['kind.cluster.creation.controlPlaneImage'];
  if (image && !image.includes('@sha256:')) {
    records.push({
          type: 'warning',
          record: 'It is recommend to include the @sha256:{image digest} for the image used.',
        });
  }

  const providerSocket = extensionApi.provider
    .getContainerConnections()
    .find(connection => connection.connection.type === provider);

  if (!providerSocket) {
    return auditResult;
  }

  const memTotal = await getMemTotalInfo(providerSocket.connection.endpoint.socketPath);

  // check if configured memory is less than 6GB
  if (memTotal < 6000000000) {
      records.push({
          type: 'info',
          record: 'It is recommend to install Kind on a virtual machine with at least 6GB of memory.',
      });
  }
  return auditResult;
```

2023-08-14 11:14 UTC, benoitf requested changes
on the audit check, it needs to be cumulative and not first is the winner

2023-08-14 13:26 UTC, axel7083 commented
@benoitf The `pr-check / smoke e2e tests (pull_request) ` failed, any idea why ?

2023-08-14 14:17 UTC, benoitf commented
@axel7083 a flaky test

2023-08-14 14:18 UTC, benoitf approved these changes

2023-08-14 14:19 UTC, merged

2023-08-14 14:19 UTC, benoitf commented
thanks @axel7083 for your PR

2023-08-14 14:25 UTC, axel7083 commented
> thanks @axel7083 for your PR

Thanks you for all of your comments and time ! :)