chore(tests): added coverage for image deletion and renamed image e2e test file
containers/podman-desktop pull request #3667
Opened 2023-08-25 09:39 UTC by xbabalov

### What does this PR do?
Implements test cases for deleting image. Renames the pull-image-smoke.spec.ts to image-smoke.spec.ts.

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/3552

### How to test this PR?
yarn test:e2e:smoke

2023-08-25 11:49 UTC, benoitf commented on tests/src/model/pages/images-page.ts
> +  async imageExists(name: string): Promise<boolean> {
please do not call this method, it was flagged as protected as it does not wait
`waitForImageExists` has to be used instead

2023-08-25 11:49 UTC, benoitf commented on tests/src/image-smoke.spec.ts
> +    const imageExists = await imagesPage.imageExists('quay.io/podman/hello');
```suggestion
    const imageExists = await imagesPage.waitForImageExists('quay.io/podman/hello');
```

2023-08-25 11:50 UTC, benoitf requested changes
need to use the waiting method for imageExists

2023-08-25 12:37 UTC, odockal requested changes

2023-08-25 12:37 UTC, odockal commented on tests/src/image-smoke.spec.ts
> +describe('Image delete verification', async () => {
We could probably change the first describe to a 'Image workflow verification', and then remove this, then unite two test methods into one?

2023-08-25 14:30 UTC, xbabalov commented
Thank you for the review @benoitf @odockal, everything requested should be fixed now.

2023-08-25 14:48 UTC, odockal approved these changes

2023-08-30 13:13 UTC, odockal commented
@xbabalov Please rebase, and if there are not objections I would merge the PR. All review comments were incorporate. @benoitf

2023-08-30 13:18 UTC, benoitf approved these changes
I confirm changes were handled

thanks

2023-08-30 13:19 UTC, merged