feat: send telemety when Create New connection requested
containers/podman-desktop pull request #3697
Opened 2023-08-29 02:40 UTC by dgolovin

### What does this PR do?

It adds telemetry reporting for the case when 'Create New' button creates new connection. When 'Create New' button sends provider installation request telemetry is handled on main side in installProvider method of ProviderRegistry.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/51

### How to test this PR?

N/A

2023-08-29 04:55 UTC, lstocchi approved these changes
LGTM

2023-08-29 06:31 UTC, benoitf requested changes
I think the event is misleading as we do not create anything, we're just redirected to the page of the creation

I would expect as name of the event something that say I want to go the "new resource" panel
`createNewPageRequested`, `createNewProviderDialog`, etc.

in provider registry there is event `createProviderConnection` (for containers, 
missing event for kubernetes)

2023-08-29 06:35 UTC, benoitf commented on packages/renderer/src/lib/preferences/PreferencesResourcesRendering.spec.ts
> +  (window as any).telemetryTrack = vi.fn();
there is no unit test checking the event being sent

2023-08-30 06:43 UTC, benoitf approved these changes
thanks for the test and the change of event name 👍

2023-08-30 17:49 UTC, merged