feat: send telemetry when creating new provider connection canceled
containers/podman-desktop pull request #3698
Opened 2023-08-29 02:58 UTC by dgolovin

### What does this PR do?

It adds telemetry reporting when 'Cancel' pressed in 'Create New Provider Connection' form 

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/51

### How to test this PR?

2023-08-29 04:54 UTC, lstocchi approved these changes
LGTM

2023-08-29 04:58 UTC, dgolovin commented
I also added telemetry for 'Close' button when form just closed without cancelling anything.

2023-08-29 06:41 UTC, benoitf requested changes
there is no unit test that is checking that we receive the events being added

I also think here that the name of the event could be more accurate to differentiate when we're aborting a display thing like 'dialog'/'page' and when aborting the process of creating a connection

so it could match new event title of https://github.com/containers/podman-desktop/pull/3697

`createNewProviderConnectionPageClosed` (or other names where we're sure that we're closing a display thing) `createNewProviderConnectionPageCloseRequest`, etc.

I would also use the event as a suffix like `createNewProviderConnectionUserCancelled`

2023-08-29 18:47 UTC, benoitf commented
@dgolovin if you can add a test checking those events and I think we're good to merge 👍

2023-08-30 00:41 UTC, dgolovin commented
Tests are added, but meantime I found couple issues:
1. I added telemetry for close button to close progress panel not the page itself (fixed)
2.  close function shadows window.close, so I did a little refactoring close -> closePanes and added closePage with router.goto and telemetry calls

2023-08-30 06:28 UTC, benoitf approved these changes
Glad you found issues while testing the component 🎉

2023-08-30 17:50 UTC, merged