docs: adds more information on how to use compose
containers/podman-desktop pull request #3716
Opened 2023-08-30 12:58 UTC by themr0c

### What does this PR do?

* Adds more information on the Compose specification Go implementation
* Adds compatibility steps for windows, linux and macOS
* Explains the .bat file which is an undocumented feature

### Screenshot/screencast of this PR

N/A, see website preview

### What issues does this PR fix or reference?

Closes #3615
Closes #3557

### How to test this PR?

View the site

Signed-off-by: Charlie Drage <charlie@charliedrage.com>### What does this PR do?

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?

2023-09-04 09:40 UTC, themr0c commented
Ready to merge, @cdrage and @benoitf ?

2023-09-06 15:26 UTC, cdrage requested changes

2023-09-06 15:26 UTC, cdrage commented on website/docs/compose/index.md
> +1. Podman Desktop detects the Compose labels, and displays the container group as a pod.
```suggestion
1. Podman Desktop detects the Compose labels, and displays the container group as a group of containers.
```

Avoid use of `pod` as a group of compose containers is just a group of containers. A pod is a different concept.

2023-09-06 15:26 UTC, cdrage commented on website/docs/compose/index.md
> +    Podman Desktop: Display pods
```suggestion
    Podman Desktop: Display multi-container applications
```

So throughout the compose documentation and spec they refer to it as "multi-container applications", we should use that: https://docs.docker.com/get-started/08_using_compose/

A group of compose containers is not called a pod.

2023-09-06 15:26 UTC, cdrage commented on website/docs/compose/running-compose.md
> +With Podman Desktop, you can manage multi-container applications defined in Compose files.
usually only one compose file, may flow better saying `defined in a Compose file.`?

2023-09-06 15:26 UTC, cdrage commented on website/docs/compose/running-compose.md
> +- The Podman Desktop **<icon icon="fa-solid fa-cube" size="lg" /> Containers** list displays the containers created by Compose grouped in a Pod with a `(compose)` suffix, such as `flask-redis (compos
remove Pod terminology

2023-09-06 15:26 UTC, cdrage commented on website/docs/compose/setting-up-compose.md
> +1. The Compose engine is in your PATH, therefore, you can display the Compose engine version:
```suggestion
1. The Compose reference implementation is in your PATH, therefore, you can display the Compose engine version:
```

Referring to Compose engine is fine in the other parts of the docs, but now we are talking about the CLI, I think we should be saying reference implementation.

compose-spec.io refers to it as a reference implementation as we should try to reference it as much as possible.

2023-09-06 15:32 UTC, themr0c commented on website/docs/compose/running-compose.md
> +With Podman Desktop, you can manage multi-container applications defined in Compose files.
```suggestion
With Podman Desktop, you can manage multi-container applications defined in a Compose file.
```

2023-09-06 15:33 UTC, themr0c commented on website/docs/compose/running-compose.md
> +- The Podman Desktop **<icon icon="fa-solid fa-cube" size="lg" /> Containers** list displays the containers created by Compose grouped in a Pod with a `(compose)` suffix, such as `flask-redis (compos
```suggestion
- The Podman Desktop **<icon icon="fa-solid fa-cube" size="lg" /> Containers** list displays the containers created by Compose grouped in a container group with a `(compose)` suffix, such as `flask-redis (compose)`.
```

2023-09-06 15:40 UTC, themr0c commented
All suggestions applied, can you have another look @cdrage ?

2023-09-06 15:41 UTC, cdrage commented
Uh oh. Mermaid is not working.

The screenshot is here:
![Screenshot 2023-09-06 at 11 15 41 AM](https://github.com/containers/podman-desktop/assets/6422176/c84b8de2-8f64-4a0c-b78f-747a0fd006b6)


According to the issue: https://github.com/facebook/docusaurus/issues/9032 this is being worked on and planned for the next release (3.0).

So for the time being, can you please take a screenshot of the diagram + add this to the PR?

We should open up an issue for the time being to re-enable mermaid js when docusaurus has a fix.

2023-09-06 15:42 UTC, cdrage submitted a review, later dismissed

2023-09-06 15:42 UTC, cdrage commented
LGTM! Thank you for these changes.

2023-09-07 07:57 UTC, themr0c commented on website/docs/compose/setting-up-compose.md
> +1. Install the Compose engine: in the Podman Desktop status bar, click on **<icon icon="fa-solid fa-download" size="lg" />Compose**, and follow the prompts.
```suggestion
1. Install the Compose engine: in the Podman Desktop status bar, click **<icon icon="fa-solid fa-download" size="lg" />Compose**, and follow the prompts.
```

2023-09-07 07:59 UTC, themr0c commented
mermaid not working on your environment: maybe it is not installed yet on your local environment? Can you double-check by running `yarn install` in the `website` directory?

2023-09-07 17:20 UTC, cdrage commented
> mermaid not working on your environment: maybe it is not installed yet on your local environment? Can you double-check by running `yarn install` in the `website` directory?

it works on my environment but not on netlify, and I'm afraid it'll probably fail when we push it to production as well on github pages.

what we COULD do it possibly merge this in and see what happens. just netlify will not be working for now.

2023-09-08 10:15 UTC, benoitf commented
@themr0c 
you need to check the 'build' mode and not the 'dev' mode

in website folder do

`yarn build`

then

`yarn serve`

2023-09-11 10:45 UTC, themr0c commented
@cdrage @benoitf Using a rendered version of the diagram. Ready to approve and merge.

2023-09-12 17:17 UTC, cdrage approved these changes
LGTM! Docs look great and thank you for being patient with the back-and-forth on reviews and changes.

The link to the actual mermaid render also looks wonderful.

Thanks again!

2023-09-12 17:17 UTC, merged