docs: clarified restricted environment scenario
containers/podman-desktop pull request #3757
Opened 2023-09-04 14:07 UTC by themr0c

### What does this PR do?

docs: clarified restricted environment scenario

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

references #2794

### How to test this PR?

2023-09-06 14:33 UTC, themr0c commented on website/docs/Installation/windows-install/installing-podman-desktop-and-podman-in-a-restricted-environment.md
> +1. Open Podman Desktop and click on the **Install** button to install Podman.
```suggestion
1. Open Podman Desktop and click the **Install** button to install Podman.
```

2023-09-06 15:13 UTC, cdrage requested changes, later dismissed
1 weird nitpick, `Installation` folder is capitalized. Should be just `website/docs/installation`

Otherwise, the docs lgtm!

2023-09-06 15:13 UTC, cdrage commented
There is also vale errors for a broken link

2023-09-06 15:19 UTC, cdrage commented
Uh oh. Mermaid is not working.

The screenshot is here:
![Screenshot 2023-09-06 at 11 15 41 AM](https://github.com/containers/podman-desktop/assets/6422176/c84b8de2-8f64-4a0c-b78f-747a0fd006b6)


According to the issue: https://github.com/facebook/docusaurus/issues/9032 this is being worked on and planned for the next release (3.0).

So for the time being, can you please take a screenshot of the diagram + add this to the PR?

We should open up an issue for the time being to re-enable mermaid js when docusaurus has a fix.

2023-09-06 15:29 UTC, themr0c commented
- That's strange, the mermaid graph worked on my end.

- The `Installation` directory is like that already. It will need  a separate pull request for that. I am not sure yet if it requires rewrites or not.
- Vale error fixed.
- Build error: requires the compose pull request to get merged first.

2023-09-06 15:45 UTC, cdrage commented
LGTM! 

We'll change `Installation` to `installation` in a separate PR, you're right.

And let's get https://github.com/containers/podman-desktop/pull/3716 in so Vale issues are passed.

2023-09-11 09:54 UTC, themr0c commented
Fixed link, please approve and merge.

2023-09-12 17:17 UTC, cdrage approved these changes
LGTM!

2023-09-12 17:17 UTC, merged