feat: add open exposed url to pod details
containers/podman-desktop pull request #3762
Opened 2023-09-05 10:30 UTC by vzhukovs

### What does this PR do?

Adds a button to pod details to open the exposed url.

### Screenshot/screencast of this PR

<img width="1162" src="https://github.com/containers/podman-desktop/assets/1968177/df4e58f0-4091-4080-8fdb-2f567518d163">

### What issues does this PR fix or reference?

#2978 

### How to test this PR?

There is an open url button near refresh button in top right corner of pod details.

2023-09-06 06:20 UTC, benoitf commented on packages/renderer/src/lib/pod/PodActions.svelte
> +          onClick="{() => window.openExternal(url)}"
from my understanding user will see "Open Browser" several times if I have like 4 URLs
but how to differentiate each link if I only see "Open Browser"

also does it mean we will have like 5 icons if I have 5 links ?

2023-09-06 06:20 UTC, benoitf commented on packages/renderer/src/lib/pod/PodDetails.spec.ts
>  });
we're missing the test of checking if we have links to open URLs and verify that if we click on the button we're redirected to the expected link

2023-09-21 06:50 UTC, jeffmaury commented
Tried on a container without port (node) and can see the Open browser link on the infra node

2023-09-21 06:52 UTC, jeffmaury reviewed
See previous comment

2023-10-18 13:55 UTC, vzhukovs commented
@benoitf @jeffmaury can you check it, please. I've provided some updates to the current PR:

Terminated Pod:
![](https://github.com/containers/podman-desktop/assets/1968177/c75dfc6a-7484-4d3a-ab70-0aa1ab5a53fe)

Active Pod:
![](https://github.com/containers/podman-desktop/assets/1968177/97bf9b7e-b258-45ff-b485-06c1491dd241)

Opening Dialogs:
![](https://github.com/containers/podman-desktop/assets/1968177/2c9d981e-053f-4160-8620-4635a6f6e922)
![](https://github.com/containers/podman-desktop/assets/1968177/0f87fdef-0b07-481f-ae69-37fdc9041d66)

Single Port:
![](https://github.com/containers/podman-desktop/assets/1968177/f29b0e33-50aa-4ee6-957c-91e44d5d3931)

2023-10-18 14:45 UTC, deboer-tim commented
The images look good, but could we make the button disabled when the pod is stopped instead of hidden? Otherwise there is some visual movement and the start/stop button changes location.

2023-10-18 15:01 UTC, benoitf commented
maybe a UX question, do we need to display a dropdown/single action when we have only one item rather than just clicking on the button ?

2023-10-18 15:05 UTC, deboer-tim commented
> maybe a UX question, do we need to display a dropdown/single action when we have only one item rather than just clicking on the button ?

+1, I would prefer if there's only one there's no drop-down and we just open it. (or maybe longer term there is a separate drop down to select which port and the button always opens?)

2023-10-19 08:17 UTC, vzhukovs commented
> The images look good, but could we make the button disabled when the pod is stopped instead of hidden? Otherwise there is some visual movement and the start/stop button changes location.

> maybe a UX question, do we need to display a dropdown/single action when we have only one item rather than just clicking on the button ?

There isn't a problem to make it disable and actionable when we have only one exposed ports. Going to update the PR.

2023-10-24 14:12 UTC, vzhukovs commented
@deboer-tim @benoitf I've updated the PR, now the situation with buttons following:

If pod doesn't have exposed port, button will be visible but disabled, the same state either on running or stopped pod:
<img width="1162" src="https://github.com/containers/podman-desktop/assets/1968177/b61c0587-6432-4916-a272-f99ca86bceb5">

If pod has only one exposed port, button will handle openning port if pod started, otherwise button visible, but disabled.
<img width="1162" src="https://github.com/containers/podman-desktop/assets/1968177/e243770e-2ff5-434a-a62f-25114bba0a4e">

If pod has several exposed ports, then on stopped state button will display dropdown with disabled buttons, the opposite situation when pod is started, in this case buttons vill be enabled and handle opening particular port.
<img width="1162" src="https://github.com/containers/podman-desktop/assets/1968177/45e5e124-d7e6-4812-85c5-8f764a7f8b8a">
<img width="1162" src="https://github.com/containers/podman-desktop/assets/1968177/5c810ff8-a513-416d-9432-03c38ce0d71a">

2023-11-14 08:16 UTC, benoitf commented
I tried and it's displaying several times the ports
![image](https://github.com/containers/podman-desktop/assets/436777/deb8c15c-cd30-49d4-b8a4-ab37b463477e)

I created a container using
```
podman run -p 8080:80 -p 8085:80 -p 8086:70 nginx
```

then convert this container to a pod

and then opening the details of the pod

2023-11-15 09:15 UTC, benoitf requested changes
on my side it's not working, I saw several duplicated items

2023-11-16 13:12 UTC, vzhukovs commented
> on my side it's not working, I saw several duplicated items

going to check it

2023-11-17 11:53 UTC, benoitf approved these changes

2023-11-17 12:37 UTC, merged