feat: added context getValue in extension API
containers/podman-desktop pull request #3826
Opened 2023-09-07 22:36 UTC by cdrage

feat: added context getValue in extension API

### What does this PR do?

While implementing the onboarding compose sequence, I noticed that there
is no getValue, despite us having setValue in the extension API.

We actually *test* getValue, but we do not let it be accessible by the
api.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3825

### How to test this PR?

Within `extensions/podman/extension.ts` you can try getting a set value,
for example:

```
extensionApi.context.getValue(USER_MODE_NETWORKING_SUPPORTED_KEY);
```

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-09-07 22:37 UTC, cdrage commented
This is needed to complete part of: https://github.com/containers/podman-desktop/issues/3709 which uses getValue to determine what version we are using as part of the onboarding sequence, see: https://github.com/containers/podman-desktop/commit/5e0dc7448383c7639bc25dc716de516abd9a3983#diff-7327606be194993bf69f195205c8cd4dc49b1cd805ad524caabe1163dcd51b39R85

2023-09-08 05:22 UTC, benoitf requested changes
the no getValue is wanted as it can expose sensitive values


The extension only provides the when clauses

2023-09-08 11:38 UTC, cdrage commented
> the no getValue is wanted as it can expose sensitive values
> 
> The extension only provides the when clauses

Ah, that's unfortunate! I'll have to find a way to store values between steps. The reasoning is that I'd to have one step "pick" which version of Compose to install, and then the next step takes that value.

Do you have any suggestions how we can do that? 

See my code here where I do setValue on the "check" stage to get the latest version: https://github.com/containers/podman-desktop/commit/5e0dc7448383c7639bc25dc716de516abd9a3983#diff-7327606be194993bf69f195205c8cd4dc49b1cd805ad524caabe1163dcd51b39R72

And then I retrieve it when we do install: https://github.com/containers/podman-desktop/commit/5e0dc7448383c7639bc25dc716de516abd9a3983#diff-7327606be194993bf69f195205c8cd4dc49b1cd805ad524caabe1163dcd51b39R85

Is there a way to share values between steps? @lstocchi @benoitf

2023-09-08 11:42 UTC, benoitf commented
I guess that instead of doing
```
      extensionApi.context.setValue('composeInstallVersion', composeLatestVersion, 'onboarding');
```

you just assign the value to a local variable

2023-09-08 12:08 UTC, cdrage commented
> I guess that instead of doing
> 
> ```
>       extensionApi.context.setValue('composeInstallVersion', composeLatestVersion, 'onboarding');
> ```
> 
> you just assign the value to a local variable

Was hoping that we would be able to have it accessible throughout the extensions (so that we can allow the podman extension for example retrieve the install version from compose extension).

I'll change it so it only uses the local variable instead.

2023-09-08 12:08 UTC, closed without merging

2023-09-08 12:19 UTC, lstocchi commented
As Florent said we took this way to prevent possible leaking issues. E.g. If you know that extension X set up a registry and save the psw in the context, another extension could "steal" it. This way we are safe.

If there will be a strong requirement to move infos from one extension to another we should find a way. Maybe we can add a custom tag to a field to declare that it can be read from the outside.

2023-09-08 12:26 UTC, benoitf commented
for extension communicating together, we could expose the value returned from the activation of an extension as well, so an extension can exposed an API as well


but AFAIK here for Charlie he just need the value later in the same extension so it should be kept locally