fix: remove image tag only not the image using id
containers/podman-desktop pull request #3837
Opened 2023-09-08 07:05 UTC by dgolovin

### What does this PR do?

* switches to use name:tag to delete image so only specific tag is deleted not the image itself and all the tags
* run delete commands as a chain to avoid conflicts when deleting different tags of the same image

### Screenshot/screencast of this PR

n/a

### What issues does this PR fix or reference?

Fix #2673

### How to test this PR?

Create different tags for the same image and try to delete them using podman-desktop ui. The selected tag should be deleted, not all the tags of the same image.

2023-09-08 10:20 UTC, benoitf reviewed
I think it's missing test where images have same id but different tags, etc

2023-09-09 03:30 UTC, dgolovin commented
@benoitf I will do that, but that is rather an integration test that should be executed with real podman. I can mock it, but that would not be a correct validation, because I can mock it to work, but it does not mean it does with actual podman. 

All new code seems to be covered with existing tests.

2023-09-13 08:26 UTC, benoitf commented on packages/renderer/src/lib/image/ImageDetails.svelte
> +    detailsPage.close();
I think having the comment that image was deleted was helpful and with the else clause
here with the early return I think it's less readable why it does `detailsPage.close();`

2023-09-13 08:26 UTC, benoitf commented on tests/src/model/pages/images-page.ts
> +    await waitWhile(imageExists, 3000, 900);
this looks unrelated to tests, just some personal preferences so it should be extracted to a separate PR

2023-09-13 08:26 UTC, benoitf commented on tests/src/utility/wait.ts
> +      )}'`;
extract from this PR

2023-09-13 08:26 UTC, benoitf commented on tests/src/utility/wait.ts
>  /**
refactoring should be a separate PR, it's not related to the fix

2023-09-14 07:50 UTC, benoitf approved these changes
nice work 👍

2023-09-14 07:59 UTC, benoitf requested changes
so I was testing again and noticed that there is one usecase where we have a regression

I have some leftover images and I was no longer able to remove these images

I've checked with the main branch and it's working so it's related to this PR

it's for images without a tag

for example do

```
podman pull quay.io/podman/hello
podman untag quay.io/podman/hello
```

then you see an image like
![image](https://github.com/containers/podman-desktop/assets/436777/c893805c-79dc-4862-ab0d-1a4007393752)


and trying to remove it leads to 

![image](https://github.com/containers/podman-desktop/assets/436777/5612b4f2-7c3a-4ada-a2dc-ff759fb1fee5)


then try to remove this image

2023-09-14 15:56 UTC, dgolovin commented
Good catch. I remember I've seen images like this, but did not pay enough attention to it :(.

2023-09-18 07:24 UTC, benoitf approved these changes
now it works as expected 👍 

maybe add a test for the `<none>` usecase as it's not covered by a test, so we might forget about it later

2023-09-20 05:06 UTC, merged