fix(tests): add check for undefined window in TelemetryService
containers/podman-desktop pull request #3967
Opened 2023-09-19 13:07 UTC by odockal

### What does this PR do?
Add check for window object in telemetry service which is occasionally undefined when there is a timeout in renderer unit tests.
### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
#3567 

### How to test this PR?
`yarn test:renderer`

2023-09-19 13:26 UTC, benoitf requested changes
the test should be updated, not the code

2023-09-20 08:09 UTC, odockal commented
@benoitf Various tests fails randomly. I have no idea how to avoid that when I do not know which test will fail.

2023-09-20 08:38 UTC, benoitf commented
@odockal looking at the tests, I saw that there is invalid mocking of telemetryPage object that should return a promise

```diff
diff --git a/packages/renderer/src/lib/image/PullImage.spec.ts b/packages/renderer/src/lib/image/PullImage.spec.ts
index b568af87..28758075 100644
--- a/packages/renderer/src/lib/image/PullImage.spec.ts
+++ b/packages/renderer/src/lib/image/PullImage.spec.ts
@@ -37,7 +37,7 @@ beforeAll(() => {
       func();
     },
   };
-  (window as any).telemetryPage = vi.fn();
+  (window as any).telemetryPage = vi.fn().mockResolvedValue(undefined);
   (window as any).getConfigurationValue = vi.fn();
   (window as any).matchMedia = vi.fn().mockReturnValue({
     addListener: vi.fn(),
diff --git a/packages/renderer/src/lib/kube/KubePlayYAML.spec.ts b/packages/renderer/src/lib/kube/KubePlayYAML.spec.ts
index 49d12a7d..5a892a1b 100644
--- a/packages/renderer/src/lib/kube/KubePlayYAML.spec.ts
+++ b/packages/renderer/src/lib/kube/KubePlayYAML.spec.ts
@@ -78,7 +78,7 @@ beforeAll(() => {
     addListener: vi.fn(),
   });
   (window as any).openFileDialog = vi.fn().mockResolvedValue({ canceled: false, filePaths: ['Containerfile'] });
-  (window as any).telemetryPage = vi.fn();
+  (window as any).telemetryPage = vi.fn().mockResolvedValue(undefined);
   (window as any).kubernetesGetCurrentContextName = vi.fn();
   (window as any).kubernetesGetCurrentNamespace = vi.fn();
   (window as any).kubernetesListNamespaces = vi.fn();

```

2023-09-21 12:12 UTC, odockal commented
@benoitf nice finding. I tried to add a proper mocking function/return values into more places, as when I tried just add `mockReturnValue` into `telemetryPage` objects, it failed elsewhere, ie. at `PreferencesRendering.spec.ts`, where was also another mocking used not aligned with a defined object's return value... so I check mutliple places. I do not think this is all the places that use improper mocking...

2023-09-21 12:15 UTC, benoitf commented
@odockal I think we can fix issues when they come, but at least we had two invalid mocks

2023-09-21 12:24 UTC, benoitf approved these changes

2023-09-21 19:40 UTC, cdrage approved these changes

2023-09-21 19:41 UTC, merged