feat: adding progress to pullImage handle
containers/podman-desktop pull request #4344
Opened 2023-10-14 12:17 UTC by axel7083

### What does this PR do?

Fix #4343 

### Screenshot/screencast of this PR

![image](https://github.com/containers/podman-desktop/assets/42176370/10603262-b345-46c9-b590-0e573bf46180)

2023-10-16 23:58 UTC, dgolovin requested changes

2023-10-16 23:58 UTC, dgolovin commented on packages/main/src/plugin/index.ts
> +            await containerProviderRegistry.pullImage(
There should be try/catch block or failure to pull will leave task running forever

![image](https://github.com/containers/podman-desktop/assets/620330/a884ab04-8522-437c-8b97-72b602f7c678)

2023-10-16 23:58 UTC, dgolovin commented on packages/main/src/plugin/index.ts
> +            progress.report({ increment: -1 });
Not sure if it is really needed, I think it will just show undetermined progress anyway.

2023-10-16 23:58 UTC, dgolovin commented on packages/main/src/plugin/index.ts
> +            notificationImpl.showNotification({ body: `${imageName} pulled.` });
Notifications does not appear for me.

2023-11-15 09:19 UTC, benoitf commented
@axel7083 could you look at @dgolovin requests ?

2023-11-15 20:15 UTC, dgolovin commented on packages/main/src/plugin/index.ts
> +            notificationImpl.showNotification({ body: `${imageName} pulled.` });
Correction, on macOS it does not appear right away. One would have to go and click on date/time part of the tray in upper right corner. On fedora 38 it seems not working at all.

2024-01-02 10:25 UTC, axel7083 commented
Closing as too much internal changes - need to be redone from scratch

2024-01-02 10:25 UTC, closed without merging