chore(tests): adding extension installation verification
containers/podman-desktop pull request #4358
Opened 2023-10-16 15:22 UTC by xbabalov

### What does this PR do?
Integrates e2e tests for general Extension extension installation and verification in Podman Desktop, covering OpenShift Sandbox and OpenShift Local installations in one parametrized test file

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/3340

### How to test this PR?
yarn test:e2e:smoke

2023-10-18 07:05 UTC, jeffmaury reviewed
I'm wondering if these tests should not be into the extension repo

2023-10-18 07:05 UTC, jeffmaury commented on tests/src/extension-installation-smoke.spec.ts
> +async function initializeLocators(extensionType: string) {
async not required here

2023-10-23 15:28 UTC, xbabalov commented
> I'm wondering if these tests should not be into the extension repo

To avoid duplicating and migrating all test files, we could setup a pipeline to run these tests in extension repositories. I created a follow up issue for that matter for OpenShift https://github.com/containers/podman-desktop/issues/4474, and we could merge the test in here. I also added new npm target so the extension test runs separately.

2023-10-30 15:21 UTC, odockal requested changes

2023-10-30 15:21 UTC, odockal commented on tests/src/model/pages/dashboard-page.ts
> +  getOpenShiftStatus(page: Page) {
missing return type. (it does work though, but please use it.)

2023-10-30 15:21 UTC, odockal commented on tests/src/model/pages/dashboard-page.ts
> +  getOpenShiftStatus(page: Page) {
Please also add "Locator" suffix, so it is clear we are not returning some enum or string value. Which could be maybe the case here. If we are aware of the various status the extension can get, we can make it an enum, or at least uses constants to holds variable in.

2023-10-30 15:21 UTC, odockal commented on tests/src/model/pages/dashboard-page.ts
> +  openshiftLocalEnabledStatus: Locator;
Why not readonly?

2023-10-30 15:21 UTC, odockal commented on tests/src/extension-installation.spec.ts
> +async function goToDashboard() {
Cannot this be part of more general functionality util files? I guess we can make us of this elsewhere.

2023-10-30 15:22 UTC, odockal commented
@xbabalov Please also create an follow up issue for adding a check for resources page. (I did not notice them in the test).

2023-11-08 09:18 UTC, xbabalov commented on tests/src/extension-installation.spec.ts
> +async function goToDashboard() {
We can move them when they are used again in another test, maybe?

2023-11-08 12:18 UTC, odockal commented on tests/src/extension-installation.spec.ts
> +async function goToDashboard() {
ok!

2023-11-08 13:30 UTC, odockal approved these changes

2023-11-08 13:31 UTC, merged