feat: add telemetry for podman onboarding (#3793)
containers/podman-desktop pull request #4377
Opened 2023-10-17 12:40 UTC by lstocchi

### What does this PR do?

This PR adds telemetry to the podman onboarding 

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

it is part of #3793

### How to test this PR?

N/A

2023-10-18 07:01 UTC, jeffmaury requested changes

2023-10-18 07:01 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +        telemetryLogger.logUsage('podman.onboarding.podman-not-installed');
I'm wondering about the title that is set in the line above ?

2023-10-18 07:01 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +        telemetryLogger.logUsage('podman.onboarding.podman-already-installed');
Can we also record the version ?

2023-10-18 07:01 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +          error: String(e),
Why don't you pass e as it may leads to [object Object] being recorded

2023-10-18 07:01 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +        telemetryLogger.logError('podman.onboarding.podman-installation', {
I think we should record the action (here installPodman) with data: version, installed (false/true) and error the second one being the only mandatory but in all case the event name should be the same

2023-10-18 07:01 UTC, jeffmaury commented on extensions/podman/src/extension.ts
> +        telemetryLogger.logUsage('podman.onboarding.podman-already-installed');
Also the event name should be checkPodmanInstalled and we should report the status

2023-10-18 07:47 UTC, lstocchi commented on extensions/podman/src/extension.ts
> +        telemetryLogger.logUsage('podman.onboarding.podman-not-installed');
it is just to customize the title shown during the onboarding. If when starting it podman is discovered we show `podman already installed` otherwise it means that is going to be installed and if everything succeed we show "podman successfully installed" in the successful step

2023-10-18 08:00 UTC, lstocchi commented
@jeffmaury i guess i got how to write them now lol. Please check it again

2023-10-19 07:28 UTC, jeffmaury approved these changes
LGTM

2023-10-19 10:15 UTC, benoitf requested changes

2023-10-19 10:15 UTC, benoitf commented on extensions/podman/src/extension.ts
> +        });
we should use logUsage in both case (see some previous comments/issue)
https://github.com/containers/podman-desktop/pull/4407
https://github.com/containers/podman-desktop/issues/4214

2023-10-19 10:15 UTC, benoitf commented on extensions/podman/src/extension.ts
> +        });
also probably need to use the pattern try / catch / finally (and do telemetry in finally block)

2023-10-19 11:04 UTC, benoitf approved these changes

2023-10-19 12:33 UTC, merged