nit: COntianer Path title nitpick
containers/podman-desktop pull request #4381
Opened 2023-10-17 22:59 UTC by cdrage

nit: COntianer Path title nitpick

### What does this PR do?

Small nitpick I noticed.

Should be capitalized similar to other forms

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

N/A

### How to test this PR?

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-10-18 01:06 UTC, deboer-tim approved these changes

2023-10-18 06:39 UTC, jeffmaury requested changes
Unit test needs to be updated

2023-10-19 07:55 UTC, benoitf approved these changes

2023-10-19 07:55 UTC, benoitf commented
@jeffmaury looks like the requested change is fixed now

2023-10-19 09:29 UTC, jeffmaury approved these changes
LGTM

2023-10-19 09:29 UTC, merged