feat: register docker-compose cli for compose extension
containers/podman-desktop pull request #4437
Opened 2023-10-20 01:43 UTC by cdrage

feat: register docker-compose cli for compose extension

### What does this PR do?

Update to https://github.com/containers/podman-desktop/pull/4388

Adds the docker-compose CLI to the list of CLI's available in the CLI
page

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

Related to #3781
Depends on #4197

### How to test this PR?

Check the CLI section within settings and you'll see Compose

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2023-10-20 01:44 UTC, cdrage commented
https://github.com/containers/podman-desktop/pull/4387 MUST be merged before this PR 

No tests added to this PR since this is a simple addition of the CLI extension to the activate section.

2023-10-25 16:13 UTC, cdrage commented
@dgolovin ready for review 👍

2023-10-25 17:21 UTC, dgolovin approved these changes
Added screenshot to description.
LGTM.

2023-10-27 07:52 UTC, feloy approved these changes

2023-10-27 08:01 UTC, benoitf commented on extensions/compose/src/extension.ts
> +const composeDescription = `Compose is a specification for defining and running multi-container applications. We support both [podman compose](https://docs.podman.io/en/latest/markdown/podman-compose
hello, I'm not sure about the part around `docker compose`

For sure you can run `docker-compose` CLI but `docker compose` if you don't have `docker` CLI or compose being at a right place it'll not work

2023-10-27 10:43 UTC, benoitf commented on extensions/compose/src/extension.ts
> +const composeDescription = `Compose is a specification for defining and running multi-container applications. We support both [podman compose](https://docs.podman.io/en/latest/markdown/podman-compose
here I think you should use @mairin text from https://github.com/containers/podman-desktop/pull/4534 ?

2023-10-27 14:32 UTC, benoitf requested changes
please update the compose description

2023-10-27 14:32 UTC, benoitf commented on extensions/compose/src/extension.ts
> +const composeDescription = `Compose is a specification for defining and running multi-container applications. We support both [podman compose](https://docs.podman.io/en/latest/markdown/podman-compose
```suggestion
const composeDescription = `The Compose extension provides optional command line support for [compose files](https://compose-spec.io/) with Podman.\n\nMore information: [Podman Desktop Documentation](https://podman-desktop.io/docs/tags/compose)`;
```

2023-11-02 12:47 UTC, cdrage commented
Blocked on your review, can you please re-approve again @benoitf ?

2023-11-02 12:48 UTC, benoitf approved these changes

2023-11-02 16:49 UTC, merged