chore: add breadcrumbs on troubleshooting and help page
containers/podman-desktop pull request #4457
Opened 2023-10-20 18:15 UTC by jannikbertram

### What does this PR do?

Add breadcrumbs and close button to the "Troubleshooting" and "Help" page.

### Screenshot/screencast of this PR

<img width="735" alt="Screenshot 2023-10-20 at 20 07 08" src="https://github.com/containers/podman-desktop/assets/17082165/8c5b26cc-1904-4d02-b851-d782a65be147">
<img width="737" alt="Screenshot 2023-10-20 at 19 13 42 1" src="https://github.com/containers/podman-desktop/assets/17082165/b1d7f3fe-dc12-49a9-9da0-92b2e7abc882">

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/2878

### How to test this PR?

Visit the "Troubleshooting" and "Help" page

2023-10-20 18:27 UTC, deboer-tim commented
@mairin The original design was no breadcrumbs on these two pages, but it sounds like it's throwing people off. Thoughts?

@jannikbertram If we do go down this route we should remove the property entirely instead of setting it true everywhere, and likely rename Home to Dashboard since I assume that's where it goes 'back' to.

2023-10-20 18:31 UTC, jannikbertram commented
Another option would be to only include the ❌ icon and remove the breadcrumbs. 
I just thought I propose this obvious approach first. 
Just let me know which design is preferred

2023-10-22 00:04 UTC, mairin commented
@deboer-tim @jannikbertram Help and Troubleshooting didn't have breadcrumbs because they sort of belong to the status bar... Neither has a presence on the dashboard (not that they shouldn't, they just don't) so semantically linking back to the Dashboard as a parent in a breadcrumb feels weird.

I do think the X in the upper right is a good idea and may have even been in the original design. I really like how you have it going to the last previously-viewed screen when the user hits the X.

I would say let's try a light touch first and just do the X, and try to side step the 🤯-ness of the breadcrumbs for now?

2023-10-22 12:08 UTC, jannikbertram commented
Thanks for clarifying this @mairin. I added a new commit and updated the PR description.

This is how it looks when you use the X button together with actions and breadcrumbs:

<img width="687" alt="image" src="https://github.com/containers/podman-desktop/assets/17082165/77eabfd0-be65-464d-8876-48083d4e9ed7">

I'm not sure if it should be possible like this. I feel like this really is about small details, so please let me know if you want this to behave differently. I can keep updating this until we find a consistent solution :)

2023-10-22 14:42 UTC, deboer-tim commented
That looks odd to me. I don't think this PR should change the location of the close button on all the other pages (it should remain on the 'breadcrumb bar'), only add a close button to the ones that don't have breadcrumbs.

2023-10-22 20:57 UTC, jannikbertram commented
I updated the PR again

> only add a close button to the ones that don't have breadcrumbs.

now it simply does this ☝️

2023-10-22 22:20 UTC, mairin commented
@jannikbertram this looks great to me, just tested it out :)

2023-10-23 07:32 UTC, jeffmaury requested changes
Fix unit tests

2023-10-24 14:41 UTC, jannikbertram commented
@jeffmaury can you trigger the unit tests again? They should be working now

2023-10-24 15:53 UTC, benoitf approved these changes
thanks @jannikbertram for your contribution

2023-10-24 17:36 UTC, deboer-tim approved these changes
LGTM. @jeffmaury, assuming you're 👍🏼 now.

2023-10-25 10:44 UTC, jeffmaury approved these changes
LGTM. Thanks @jannikbertram for this

2023-10-25 10:44 UTC, merged