fix: light scrollbars and line height
containers/podman-desktop pull request #4826
Opened 2023-11-15 23:57 UTC by deboer-tim

### What does this PR do?

After the PatternFly removal I noticed that the scrollbars on Mac are in light-mode. PF-dark was setting the color-scheme before, setting it again fixes the problem and means we can also remove the explicit text-white. (maybe some of the changes in #4803 too?)

PF was also setting the line height to 0.9. I'm not tied to it, but it makes buttons, multi-line text, and preferences nav items all less tall. Maybe I'm just used to it, but I prefer a smaller window and 0.95 gets most of the way there & uses less space.

### Screenshot/screencast of this PR

1.5.3:
<img width="638" alt="Screenshot 2023-11-15 at 6 55 43 PM" src="https://github.com/containers/podman-desktop/assets/19958075/be46daa5-db9c-4ab4-9f54-68bcd4bc137a">

Post PatternFly:
<img width="638" alt="Screenshot 2023-11-15 at 4 15 15 PM" src="https://github.com/containers/podman-desktop/assets/19958075/ed9c64e7-38ea-43ab-83b0-0ff07c20da61">

This PR:
<img width="638" alt="Screenshot 2023-11-15 at 4 14 40 PM" src="https://github.com/containers/podman-desktop/assets/19958075/2ca3df16-6b43-4442-ba4e-770ce1f74e2b">

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Open dashboard, preferences.

2023-11-16 08:06 UTC, jeffmaury approved these changes
LGTM on Windows

2023-11-16 08:30 UTC, benoitf requested changes
I would not opt-in for this change (color-scheme), it will delay the work to have proper light/dark theme.

For the line-height, I would not follow css approach as well, it's breaking the tailwind flow
as elements are interconnected. It's making harder to have clean stuff.

2023-11-16 13:27 UTC, deboer-tim commented
color-scheme sets the defaults (light=white background, black text, scrollbars colors, etc, dark=black background, white text, etc). I was assuming we'd set it now to fix scrollbars (and anything else like text-white where the default is fine), then future light mode would toggle it. What is the other option? I don't think we want to custom style scrollbars or to use `text-black dark:text-white` in the future when those could already be the default colors.

AFAIK Tailwind doesn't have an equivalent option to globally scale line height. Do you think we should override all the font sizes in config, change scaling/padding in all the affected components individually, or something else?

2023-11-22 20:11 UTC, deboer-tim commented
Light mode fixed via #4910. I will submit separate issues and/or PRs for components affected by change in line height.

2023-11-22 20:11 UTC, closed without merging