chore(test,ci): fix broken e2e test execution
containers/podman-desktop pull request #5003
Opened 2023-11-27 13:53 UTC by ScrewTSW

### What does this PR do?

* Fixes missing playwright dependencies installation

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?
#4983 

### How to test this PR?

* yarn --frozen-lockfile
* yarn run test:e2e:smoke

2023-11-27 14:13 UTC, jeffmaury approved these changes
LGTM

2023-11-27 14:21 UTC, benoitf requested changes
it only needs to be done once, so it should not be done at each run of the test command

2023-11-27 15:16 UTC, odockal commented
@benoitf It does not force overwrite the artifacts, so if it is called twice, it does not do anything if already up to date. 
Before it was part of `yarn install`, now it would be part of `yarn test:e2e:XXX`, which is truly called more than once when running tests, but it is better, imho, than adding this steps to the every workflow.

2023-11-27 15:18 UTC, benoitf commented
> so if it is called twice, it does not do anything if already up to date
yes but it's still not something that we should do there



move it to `postinstall` where it means it should be only done 'once' when dependencies are updated/changed

2023-11-27 15:40 UTC, odockal commented
@benoitf Nice, neat.

2023-11-27 15:42 UTC, odockal requested changes

2023-11-27 15:42 UTC, odockal commented on package.json
> +    "test:e2e": "npm run test:e2e:build && npm run test:e2e:run",
As per discussion on PR, please revert running the install part in tests, and put it into a postinstall.

```
...
"prepare": "husky install",
"postinstall": "npx playwright install webkit ffmpeg"
```

2023-11-27 15:42 UTC, odockal commented on package.json
> +    "test:e2e": "npm run test:e2e:build && npm run test:e2e:run",
@benoitf Like this?

2023-11-27 15:55 UTC, ScrewTSW commented on package.json
> +    "test:e2e": "npm run test:e2e:build && npm run test:e2e:run",
fixed, tested.

2023-11-27 15:56 UTC, odockal approved these changes

2023-11-27 16:49 UTC, benoitf commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
why do we need these extra items ( WebKit and ffmpeg) and not only install ?

2023-11-28 12:12 UTC, odockal commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
`npx playwright install` downloads all default browser, (including chromium, firefox) and it is not necessary, imho.

2023-11-28 14:15 UTC, benoitf commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
@odockal it does require webkit for electron ? AFAIK electron is based on chromium

2023-11-28 20:10 UTC, odockal commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
@benoitf I am not sure about what exactly electron requires, but I tried `webkit + ffmpeg` and `chromium` only (it pulls ffmpeg by default) and both combination works. So I guess we can stick to defaults which could be more general for any OS we will run workflow in.

2023-11-28 20:20 UTC, benoitf commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
@odockal and only ffmpeg ?

2023-11-28 21:15 UTC, odockal commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
@benoitf Well.. maybe, I will let @ScrewTSW to verify.

2023-11-28 21:35 UTC, odockal commented
It is all messy. I have created new issue that this PR directly addresses. It is #5032.
#4983 which I though was to be addressed by this PR will probably not be fixed by this.

2023-11-28 21:52 UTC, ScrewTSW commented on package.json
> +    "postinstall": "npx playwright install webkit ffmpeg"
@benoitf hello, we have reset the requirements to the default ones as they were being downloaded previously

2023-11-28 22:14 UTC, benoitf approved these changes

2023-11-28 22:15 UTC, benoitf commented on package.json
> +    "postinstall": "npx playwright install"
remove npx before merging

2023-11-28 23:30 UTC, ScrewTSW commented on package.json
> +    "postinstall": "npx playwright install"
done.

2023-11-29 01:19 UTC, merged