chore: simplify container/compose actions & callbacks
containers/podman-desktop pull request #5160
Opened 2023-12-06 20:23 UTC by deboer-tim

### What does this PR do?

The same change as #5141, but for containers & compose.

This change just makes the ContainerAction and ComposeAction update their UI objects directly, and then uses a standard dispatch event to notify parents that something changed. ContainerList, ContainerDetails, and ComposeDetails just need an on:update to trigger a Svelte update. Simpler/less code all around and less chance of the UI components having different behaviour.

Compared with pods I noticed and fixed a couple things:
- ComposeActions is updating the containers but not the compose group. Added this so now the group also goes into states like 'starting'.
- ComposeDetails was not listening for changes, so even after the change above there was no change in the UI. Fixed this.
- Both *Actions were frequently using the finally block to set the state after the action is completed. e.g. containers are set to RUNNING after start. In the best case this matches the state update we get from the container engine, so just setting twice. In the worst case the action fails, and we set the state anyway... Fixed.
- The ContainerList wasn't listening for changes to pods [*].

There is still one difference between pods and compose:
- When you start a compose group we set all containers (plus now the group) to STARTING, but for pods we only set the pod. I don't know if this is intentional, but I left it / unrelated for now.

and one unrelated gap [*]:
- The ContainerList passes newly created UI objects to PodActions and ComposeActions, so when those objects change the ContainerList doesn't update until the next notification through the respective store. This is the same problem listed in #5141 - if you start a container and then quickly go to Details it is still stopped. This problem is unrelated to / unaffected by this change.

Like #5141 this shouldn't merge until after 1.6.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Cleanup prior to #4843.

### How to test this PR?

yarn test:renderer or use ContainerList/ContainerDetails/ComposeDetails. As a code simplification chore, there should be no change to behaviour or tests. (although note some minor bugs fixed, e.g. compose groups will show 'starting' when started from compose details)

2023-12-06 22:02 UTC, benoitf approved these changes
note sure if we're not missing some component tests

2023-12-06 22:02 UTC, benoitf commented on packages/renderer/src/lib/compose/ComposeActions.svelte
> +  compose.containers.forEach(container => {
```suggestion
  for (const container of compose.containers) {
```

2023-12-06 22:02 UTC, benoitf commented on packages/renderer/src/lib/compose/ComposeActions.svelte
> +  compose.containers.forEach(container => {
(not a required change)

2023-12-07 10:25 UTC, benoitf requested changes
we're missing some tests there

ContainerActions has no tests
ComposeActions has no tests

2023-12-11 03:58 UTC, deboer-tim commented on packages/renderer/src/lib/compose/ComposeActions.svelte
> +  compose.containers.forEach(container => {
Yes, this is better, updated when I added tests.

2023-12-11 03:58 UTC, deboer-tim commented
Added tests in new commit.

2023-12-11 08:08 UTC, benoitf approved these changes

2023-12-14 23:16 UTC, benoitf commented
PR needs rebase/solving conflicts

2023-12-19 20:15 UTC, benoitf commented
I think it can be merged if conflict is solved

2023-12-20 03:44 UTC, deboer-tim commented
Rebased and merge conflict fixed.

2023-12-20 08:10 UTC, benoitf approved these changes
approving again

2023-12-20 08:15 UTC, feloy approved these changes

2023-12-20 13:25 UTC, merged