website: updated mac docs
containers/podman-desktop pull request #525
Opened 2022-10-06 19:16 UTC by deekay2310

Signed-off-by: Dev Kumar <devskumar99@gmail.com>

### What does this PR do?

### Screenshot/screencast of this PR

<img width="1440" alt="Screen Shot 2022-10-06 at 3 15 35 PM" src="https://user-images.githubusercontent.com/29257773/194399671-7faf1132-f58d-4baa-9f20-24f523da8dd7.png">
<img width="1440" alt="Screen Shot 2022-10-06 at 3 15 40 PM" src="https://user-images.githubusercontent.com/29257773/194399674-d5358981-0a8c-4c64-b265-182f1e997037.png">
<img width="1440" alt="Screen Shot 2022-10-06 at 3 15 45 PM" src="https://user-images.githubusercontent.com/29257773/194399676-6b8055de-8fc8-49b7-9a0c-ed2b4e2b8ecc.png">
<img width="1440" alt="Screen Shot 2022-10-06 at 3 15 48 PM" src="https://user-images.githubusercontent.com/29257773/194399679-9077d9f1-41a1-46a2-9eb5-8a863135d5a6.png">
<img width="1440" alt="Screen Shot 2022-10-06 at 3 15 54 PM" src="https://user-images.githubusercontent.com/29257773/194399681-0454487a-6fc6-4fba-88f6-d154f782d979.png">

### What issues does this PR fix or reference?

### How to test this PR?

2022-10-07 14:26 UTC, slemeur commented
@deekay2310 : Make sure to provide a clear description of the changes you are providing.  Not everybody can understand what has changed just with the screenshots ;).

2022-10-07 14:32 UTC, deekay2310 commented
@slemeur I have provided the same before adding the screenshots. It is available under the question - "What does the PR do?"

2022-10-07 14:34 UTC, benoitf commented on website/docs/Installation/macos-install.md
> +<ol>
we should never use any HTML inside .md files

2022-10-07 14:42 UTC, deekay2310 commented on website/docs/Installation/macos-install.md
> +<ol>
Docusaurus won't process the list otherwise, even image size could not be controlled by any other way.  Any fix for the same?

2022-10-07 14:59 UTC, benoitf commented on website/docs/Installation/macos-install.md
> +<ol>
I tried on the playground and it seems to work

https://stackblitz.com/edit/github-7ahlcu?file=docs%2Fintro.md

![image](https://user-images.githubusercontent.com/436777/194584261-58fc987c-52df-40dc-ac35-ec36db9426c3.png)

2022-10-07 15:13 UTC, deekay2310 commented on website/docs/Installation/macos-install.md
> +<ol>
@benoitf This is the change @slemeur and I pushed - https://github.com/containers/podman-desktop/blob/main/website/docs/Installation/macos-install.md#installation-steps

Here is the output - https://podman-desktop.io/docs/Installation/macos-install#installation-steps

2022-10-07 18:57 UTC, benoitf commented on website/docs/Installation/macos-install.md
> +<ol>
I suppose it's tailwind that is removing the style
So we should look at this but markdown should not be changed

2022-10-11 13:37 UTC, deekay2310 commented
@fbenoit planning to remove img tags in another PR once this is merged; sounds good?

2022-10-12 07:34 UTC, slemeur commented
@deekay2310 : Why can't you remove the img tags in that PRs? this way your PR is clean and don't introduce things that we already know we'll need to remove later on ;) .

2022-10-12 07:47 UTC, slemeur requested changes
PR should not include HTML

2022-10-12 13:10 UTC, deekay2310 commented
@slemeur the documentation won't be as readable as it is now but I can go ahead with it anyway

2022-10-17 13:27 UTC, slemeur approved these changes
LGTM

2022-10-17 14:04 UTC, merged