fix: spontaneous zoom after navigation + resize
containers/podman-desktop pull request #5312
Opened 2023-12-19 04:49 UTC by dgolovin

### What does this PR do?

This fix creates internal http server with OS dfined random port and serves podman-desktop html through it. That fixes spontaneous zoom change in app. In the case when there are problems to start server it resorts to serving from file.

### Screenshot / video of UI

Before fix:

https://github.com/containers/podman-desktop/assets/620330/be2f270b-9cfa-4b0a-9aa0-07ef473749e5

After fix:

https://github.com/containers/podman-desktop/assets/620330/03f9d2cc-1a6e-4fb9-a05f-fd739c79b560

### What issues does this PR fix or reference?

Fix #5265

### How to test this PR?

* pull PR branch
* run `yarn compile:next`
* install podman-desktop from dist folder
* repeat steps from screen-casts above

2023-12-19 04:52 UTC, dgolovin commented
@slemeur FYI

2023-12-19 08:04 UTC, benoitf reviewed
I'm kind of -1 to change the way we load the html files

2023-12-19 08:05 UTC, benoitf commented on package.json
> +    "node-static": "^0.7.11",
we can't introduce this library. It is not maintained and has security issues

2023-12-19 08:09 UTC, benoitf requested changes
node-static library can't be used (5years since last release)

while it helps for investigation, I think other ways should be explored

2023-12-19 09:05 UTC, slemeur commented
I'm indeed not able to reproduce the issue with this PR

2023-12-19 16:34 UTC, dgolovin commented
It can be done with any other server implementation module and for macOS only.

2023-12-20 00:29 UTC, cdrage requested changes
I'm unable to reproduce the original issue (what a weird bug) so in this PR is has been fixed, but I agree that we should not use node-static.

Is it a common way to do this? I'm trying to find examples online with regards to serving an electron app through node-static / http, but I'm unable.

2024-01-05 08:06 UTC, dgolovin commented
After playing with it some more time it seems can be fixed, the way it keep 1.0 ratio when I am switching between pages, but it fails as soon as I change zoom.

Vscode and slack seems to work fine. I have one more trick to test and then the only option what @cdrage suggested.

Another option is create simple app that replicates the bug and open issue for electron.

2024-07-18 00:26 UTC, closed without merging