chore(tests): Registries e2e tests
containers/podman-desktop pull request #5323
Opened 2023-12-19 11:49 UTC by xbabalov

### What does this PR do?
Implements test cases verifying the registries creation, authentication and deletion, including pulling image from the registry. 

### Screenshot / video of UI

### What issues does this PR fix or reference?

<!-- Include any related issues from Podman Desktop 
https://github.com/containers/podman-desktop/issues/4362

### How to test this PR?
npm run test:e2e:smoke

2023-12-19 14:00 UTC, odockal requested changes

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-image-smoke.spec.ts
> +    await pullImagePage.pullImage(fullImageTitle);
I guess you cannot simply call pullImage function since it will throw error inside because Done button simply wont appear. I guess we should create a pullimage function in this test file that will either verify ability to pull image or check expected error message. It will be used here and in the `Pull image from registry` afterward. It should also have some parameters to control the verification for error/pass behavior.

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-image-smoke.spec.ts
> +  test('Create and authenticate registry', async () => {
"Add and authenticate registry" would be better naming.

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-image-smoke.spec.ts
> +  test('Pull image from registry', async () => {
It is possible to pull image from authenticated registry.

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-image-smoke.spec.ts
> +describe('Registry image workflow verification', async () => {
Maybe a bit better naming. Pulling image from authenticated registry workflow verification

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-image-smoke.spec.ts
> +  test('Try pulling unauthentified image', async () => {
Cannot pull image from unauthenticated registry.

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +describe('Registry verification and handling', async () => {
Plural? Registries? Registries handling verification

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +    await playExpect(registryPage.addRegistryButton).isEnabled();
Not sure why it failed on PR

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +  test('Check Registries page components and default registries', async () => {
... and presence of default registry records?

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +  describe('Registry creation verification', async () => {
Add registry workflow verification

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +    test('Verify invalid registry', async () => {
Cannot add invalid registry record?

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +    test('Create valid registry', async () => {
Can(it is possible) to add a new registry.

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +  test('Registry editing availability and invalid credentials verification', async () => {
Can edit registry

2023-12-19 14:00 UTC, odockal commented on tests/src/registry-smoke.spec.ts
> +  test('Remove registry', async () => {
Can remove registry

2024-01-17 15:06 UTC, xbabalov commented
The e2e tests main workflow including both registry tests is passing when ran on my fork now: 
![image](https://github.com/containers/podman-desktop/assets/57829934/61905388-4217-4b36-8f80-161584515695)

2024-01-19 12:21 UTC, odockal requested changes

2024-01-19 12:21 UTC, odockal commented on tests/src/model/pages/registries-page.ts
> + * Copyright (C) 2023 Red Hat, Inc.
New year :)

2024-01-19 12:21 UTC, odockal commented on tests/src/registry-image.spec.ts
> + * Copyright (C) 2023 Red Hat, Inc.
also 2024

2024-01-19 12:21 UTC, odockal commented on tests/src/registry.spec.ts
> +  registryUsername = process.env.REGISTRY_USERNAME
Extract this logic into what you got in setup-files. So it is unified across both tests.

2024-01-19 12:21 UTC, odockal commented on .github/workflows/pr-check.yaml
> +        env:
I would not place this env. to the PR check yet. Please remove it. we will try with e2e-test-main first.

2024-01-26 12:37 UTC, odockal approved these changes

2024-01-26 12:37 UTC, merged

2024-01-30 09:56 UTC, odockal commented
Fixes #4362