Provide ARIA functionality to Podman Machine onboarding
containers/podman-desktop pull request #5652
Opened 2024-01-23 13:29 UTC by ScrewTSW

### What does this PR do?
* Provides ARIA label to Next button in Onboarding dialog
* Fixes naming convention for Cancel Setup aria-label
* Updates tests with said change

### Screenshot / video of UI

### What issues does this PR fix or reference?
#4709 

### How to test this PR?
* yarn --frozen-lockfile
* yarn run test:e2e:smoke

2024-01-23 13:35 UTC, benoitf approved these changes

2024-01-23 14:15 UTC, odockal commented
@ScrewTSW Unit tests are failing on your change.

2024-01-23 14:17 UTC, odockal requested changes
fix unit tests.

2024-01-23 20:08 UTC, ScrewTSW commented
> fix unit tests.

done.

2024-01-23 21:57 UTC, ScrewTSW commented
> fix unit tests.

done.

2024-01-24 11:01 UTC, odockal approved these changes

2024-01-24 16:15 UTC, merged