Copy button - Details page
containers/podman-desktop pull request #5832
Opened 2024-02-05 09:30 UTC by trmendes

### What does this PR do?

It makes usage of the “Copy To Clipboard” component, so the users can copy the title of the details page to the clipboard.

### Screenshot / video of UI
![copy_button_details](https://github.com/containers/podman-desktop/assets/16507629/509627ce-72f2-4d7c-8326-3adebb5ff7f2)

### What issues does this PR fix or reference?

Fixes #4241

### How to test this PR?

1) Open the detail page
2) Click on the copy button
3) Check if the title is present on your clipboard as expected

2024-02-05 09:31 UTC, trmendes commented
Not very happy with the layout of it. Any suggestions and hints for the CSS?

2024-02-05 09:50 UTC, benoitf commented
I think it's around the vertical alignment (I have not looked at the html elements being currently used to give you the proper answer but hints would be around `items-center`, `align-middle`, etc

2024-02-05 22:28 UTC, dgolovin requested changes

2024-02-05 22:28 UTC, dgolovin commented on packages/renderer/src/lib/ui/CopyToClipboard.svelte
> +<div class="mt-1 my-auto truncate {$$props.class || ''}" aria-label="{title} copy to clipboard" title="{title}">
You can modify line 15 to
```
<Tooltip tip="Copy to Clipboard" bottom class="{$$props.class || ''}">
```
so you can control `<span/>` that wraps the `<slot />`

2024-02-05 22:28 UTC, dgolovin commented on packages/renderer/src/lib/ui/DetailsPage.svelte
> +            <div><CopyToClipboard title="{title}" clipboardData="{title}" class="text-xl" /></div>
Then update classes for button to
```suggestion
            <div><CopyToClipboard title="{title}" clipboardData="{title}" class="text-xl inline-block mt-1" /></div>
```

That change wont affect style of the copy button in resources page and fix `Details page` layout

![image](https://github.com/containers/podman-desktop/assets/620330/774ad5a0-5e95-4ded-b65c-0cf975efd79b)

2024-02-06 08:15 UTC, trmendes commented
@dgolovin Thank you do much for your guidance with CSS :)

It looks much better now <3

![copy1](https://github.com/containers/podman-desktop/assets/16507629/937fd9ba-d8c2-46fd-bda8-573c79266d44)

![copy2](https://github.com/containers/podman-desktop/assets/16507629/20ca6ad0-c75b-4819-912a-0657ae088d19)

2024-02-06 08:21 UTC, benoitf commented
I find confusing the clipboard button being in the middle of the line as I'm not sure what it could copy

![image](https://github.com/containers/podman-desktop/assets/436777/975bb917-3a7f-4e28-90e9-cbf496c128a8)

I don't know if we need to move the sha to a newline or think in a different way or just copy the sha and not the image name (so button is at the right)

2024-02-06 08:35 UTC, trmendes commented
@benoitf I completely agree, and I experienced the same feeling of confusion when opening the panel to take the screenshot.

I might be a bit busy with an interview this week, but I will come back to it, do some experiments and post screenshots here as soon as possible. 

Thanks for your comment :)

2024-02-06 08:43 UTC, benoitf commented
@trmendes good stuff anyway

maybe to be less confusing it's to have the icon appearing only on hover and a different background including both the thing to copy and the copy button so we see that it's the 'same unit'

I'll let others comment here

2024-02-06 13:57 UTC, trmendes commented
@benoitf I took a quick look at docker desktop to see how they handle that sort of information, and they actually have a copy button for the hash and not for the object name. They also print the tag along with the name.

What is the primary reason we choose copying the name over hash?

2024-02-06 14:24 UTC, benoitf commented
cc @mairin

2024-02-06 14:43 UTC, axel7083 commented
> cc @mairin

I had something similar open _long time ago_ see @mairin comment on the subject https://github.com/containers/podman-desktop/pull/4242#issuecomment-1765216485

2024-02-06 15:23 UTC, mairin commented
@axel7083 Yep exactly what I was gonna suggest :) Here's a prototype, it's a little hairy but you get the idea:

https://design.penpot.app/#/view/43442e9d-d45f-8169-8003-daff3cb3e0b8?page-id=43442e9d-d45f-8169-8003-daff3cb3e0b9&section=interactions&index=0&share-id=93d0ad32-dfe5-8194-8003-db0444b2c3bf

Recording for convenience:
[Peek 2024-02-06 10-23.webm](https://github.com/containers/podman-desktop/assets/799683/e868c8e0-9f73-437c-8b66-15a9157ce0ab)

2024-02-06 16:06 UTC, feloy commented
> I find confusing the clipboard button being in the middle of the line as I'm not sure what it could copy
> 
> ![image](https://private-user-images.githubusercontent.com/436777/302550209-975bb917-3a7f-4e28-90e9-cbf496c128a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzU2MDAsIm5iZiI6MTcwNzIzNTMwMCwicGF0aCI6Ii80MzY3NzcvMzAyNTUwMjA5LTk3NWJiOTE3LTNhN2YtNGUyOC05MGU5LWNiZjQ5NmMxMjhhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxNjAxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjJmODk3MDE0MGM0ZWNhYjNiZjIyYTMxZGJhMDBmZDE3Y2JjNWUxZjA0ZTA2ZTA5YzA5NDI0Yjc5NWVhZGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0A2TzPqkbSeN9-r_96XxEiMNopd_Pzwrci7vfnb6aRc)
> 
> I don't know if we need to move the sha to a newline or think in a different way or just copy the sha and not the image name (so button is at the right)

I would move the icon closer to the text it copies. Here it is exactly in the middle, the reason why IMO it is confusing.

2024-02-06 17:06 UTC, deboer-tim commented
+1 to design from @mairin. That's a much cleaner look, which means we could use it in far more places (e.g. we don't need to decide between name or hash, both could allow copying without any UI clutter or confusion).

CopyToClipboard is already used in Preferences > Resources page (#5687), I think the question is whether we use it here basically as-is or refactor it to the design first. Since there are multiple comments on placement I'd prefer the latter, also so that we wouldn't add buttons and then 'remove' them later.

2024-02-06 17:25 UTC, feloy commented
> +1 to design from @mairin. That's a much cleaner look, which means we could use it in far more places (e.g. we don't need to decide between name or hash, both could allow copying without any UI clutter or confusion).
> 
> CopyToClipboard is already used in Preferences > Resources page (#5687), I think the question is whether we use it here basically as-is or refactor it to the design first. Since there are multiple comments on placement I'd prefer the latter, also so that we wouldn't add buttons and then 'remove' them later.

My only concern about these popup on which we need to click (not specifically here, but in different apps/websites), is related to accessibility and that you have to be quite precise with your mouse and don't move too much, or the popup disappears before you can click on it. And is it usable with keyboard only?

2024-02-06 17:41 UTC, deboer-tim commented
> My only concern about these popup on which we need to click (not specifically here, but in different apps/websites), is related to accessibility and that you have to be quite precise with your mouse and don't move too much, or the popup disappears before you can click on it.

Agreed, we need to make sure it is not finicky and mouse-over area is generous. Could be other things we could do too, e.g. maybe clicking on the text keeps the popup open?

> And is it usable with keyboard only?

FWIW, I just checked what to me is the 'Mac equivalent': copying a password from the password manager. When you're using the keyboard you never see the popup - when you tab in it auto-selects all the text and a normal Ctrl-C works fine.

2024-02-06 18:11 UTC, mairin commented
@deboer-tim Ah that is what I would suggest for keyboard... just enable ctrl+c on copyable fields on focus.

2024-03-12 17:47 UTC, benoitf commented
converting do draft

2024-08-28 12:27 UTC, benoitf commented
not updated, closing

2024-08-28 12:27 UTC, closed without merging