feat: kubernetes connection store
containers/podman-desktop pull request #5850
Opened 2024-02-05 17:05 UTC by axel7083

### What does this PR do?

The connection status of the current context must be accessible to the frontend. This PR is adding a `kubernetesConnection` store.

### Screenshot / video of UI

### What issues does this PR fix or reference?

Related to https://github.com/containers/podman-desktop/issues/5401

### How to test this PR?

- [x] Unit tests has been added

2024-02-06 04:27 UTC, deboer-tim commented on packages/main/src/plugin/kubernetes-connection.ts
> + * Copyright (C) 2023 Red Hat, Inc.
Nit: 2024

2024-02-06 04:47 UTC, deboer-tim requested changes
+1 to this function, we really need it.

My main concern is that to get the list of contexts or what the current one is you use stores/kubernetes-contexts, but then to get the status of the current context you use another store that also says what the context is. When changing current context it's not clear how in sync these are or whether/how clients would deal with when the connection context isn't the current context.

There's also PR #5329 which overlaps on connection status. The one nice aspect there is that it's a map, so it doesn't duplicate what the current context is and can store connection info for multiple contexts.

Maybe a group chat would help, or you could discuss with @feloy?

2024-02-06 08:40 UTC, jeffmaury commented on packages/renderer/src/stores/kubernetes-connection.ts
> +const windowEvents: string[] = ['kubernetes-context-update', 'kubernetes-connection-update'];
I don't see where kubernetes-connection-update is being sent

2024-02-06 08:40 UTC, jeffmaury commented on packages/main/src/plugin/index.ts
> +      console.log('getConnectionStatus', value);
To be removed

2024-02-22 09:41 UTC, closed without merging

2024-02-22 09:41 UTC, axel7083 commented
Closing in favour of https://github.com/containers/podman-desktop/pull/5917/files#diff-ea47798d4fd89a4b135b3c7c7e1be18d4ba792cb8dd900425946693f0e7a53c9