docs: sidebar improvements / expansion / bolded css
containers/podman-desktop pull request #5881
Opened 2024-02-06 15:17 UTC by cdrage

docs: sidebar improvements / expansion / bolded css

### What does this PR do?

* Adds "2 levels deep" expansion by default
* Reorganizes the categories in a better way. For example, setting up a
  proxy environment and troubleshooting is more at the bottom of the
  documentation rather than the top
* Adds bold css for the category so it's easier to look at / navigate /
  read.

### Screenshot / video of UI

### What issues does this PR fix or reference?

Closes #5388

### How to test this PR?

View the website and expand the pages

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2024-02-06 15:19 UTC, cdrage commented
Note that we still auto-generate the "children" files / folders. But we have to make sure that when we add a new category, we've got to update the sidebar config too.

2024-02-06 18:21 UTC, deboer-tim commented
Can you break this up/focus on just the non-generated sidebar here? I don't love having to keep it in sync, but I think it changes rarely enough and there is minimal duplication, so I'd be ok with it given the benefit.

For styling, notice that the top Introduction title isn't styled, b/c it's not a section. :) I figured this out and could apply the style in another PR.

Reordering might be contentious, I thought someone had said they wanted Troubleshooting last - easier to review and debate if it's separate, and won't hold this up.

2024-02-06 18:32 UTC, cdrage commented
> Can you break this up/focus on just the non-generated sidebar here? I don't love having to keep it in sync, but I think it changes rarely enough and there is minimal duplication, so I'd be ok with it given the benefit.
> 
> For styling, notice that the top Introduction title isn't styled, b/c it's not a section. :) I figured this out and could apply the style in another PR.
> 
> Reordering might be contentious, I thought someone had said they wanted Troubleshooting last - easier to review and debate if it's separate, and won't hold this up.

Done! I've removed the CSS change and moved troubleshooting to the bottom.

2024-02-06 19:28 UTC, deboer-tim commented
Expanding only to second level: working great!

Unfortunately there's something going wrong with the categories: every category that has content is now showing up 'within itself'. e.g. on the live website I can select Installation to see one doc, and it has 3 children (one for each OS). When testing this PR I can't click on Installation, and it has 4 children: one for each OS and a 'second' Installation topic that contains what was in the parent before. Another example: we already had a Containers > Containers entry, but now there are two of them named Containers.

Personally I'd be ok if the categories weren't selectable, but that's likely a far bigger change since it goes down to every level, and we'd have to move each existing topic to be the first child and have a better name...

I also noticed Restricted Environments was the third option before, now it is called Proxy Environment and third-last.

2024-02-06 20:32 UTC, cdrage commented
> Expanding only to second level: working great!
> 
> Unfortunately there's something going wrong with the categories: every category that has content is now showing up 'within itself'. e.g. on the live website I can select Installation to see one doc, and it has 3 children (one for each OS). When testing this PR I can't click on Installation, and it has 4 children: one for each OS and a 'second' Installation topic that contains what was in the parent before. Another example: we already had a Containers > Containers entry, but now there are two of them named Containers.
> 
> Personally I'd be ok if the categories weren't selectable, but that's likely a far bigger change since it goes down to every level, and we'd have to move each existing topic to be the first child and have a better name...
> 
> I also noticed Restricted Environments was the third option before, now it is called Proxy Environment and third-last.

Okay, so after some digging and back and forth I was able to get this to work. The problem was that we were using `index.md` files as a makeshift table of contents / summary page.

Docusaurus has one actually built-in with:

```
      link: {
        type: 'generated-index',
      },
```


I've updated the PR so those index pages are no longer there, as well as update all the "index" pages we used to have which was (with the exception of one file), re-interating what is in the folder.

So instead of this:

![Screenshot 2024-02-06 at 3 32 15 PM](https://github.com/containers/podman-desktop/assets/6422176/6d47318f-b713-4b93-af66-8043b54802a2)

We now have this:

![Screenshot 2024-02-06 at 3 19 46 PM](https://github.com/containers/podman-desktop/assets/6422176/6650861c-f091-4c39-be82-57efde77055c)


Some of the documentation was also out of date, so now it's auto-generated.

Let me know what you think @deboer-tim

2024-02-12 12:09 UTC, themr0c commented
After reading the comments, I understand why all the `index.md` are gone. I would like to see the build!! It might change drastically how to work on #5335, as my first questions for this issue were: 
- How could I display the sections as "cards" rather than a bare list?
- How can it be generated automatically?

2024-02-12 12:36 UTC, themr0c commented on website/sidebars.js
> -      dirName: '.',
Does this mean that we would need to manually add entries to the navigation bar? I'd prefer not :/

2024-02-12 21:36 UTC, cdrage commented
@themr0c Updated! It was indeed an issue, I had to add `slug: `/installation'` for the sidebar config.

As per our meeting, let's get this merged in and then further improve the "category" pages after the PR.

For others, the reasoning why we cannot use a 100% auto-generated sidebar is because docusaurus doesn't allow "expanding only 2 levels deep", and thus we have to create categories and specifically mark them as collapsed: false.

2024-02-12 21:36 UTC, cdrage commented on website/sidebars.js
> -      dirName: '.',
Marking as resolved as fabrice and I talked about this in a meeting, but TLDR is yes we do as docusaurus doesn't allow specifying how "many levels deep" to only expand.

2024-02-13 21:28 UTC, deboer-tim requested changes
I have to be honest - I don't like these pages at all:
<img width="977" alt="Screenshot 2024-02-13 at 4 18 15 PM" src="https://github.com/containers/podman-desktop/assets/19958075/c87c0467-22c3-4fc2-a0ca-04fd69884954">

To me they don't fit in with our website or provide any real visual improvement, and as much as many of the previous index pages were minimal I like them better. I'd prefer we stick with one-change-per-PR, as I'd approve the sidebar change w/o the rest (here, or use a different PR for that part).

2024-02-14 14:07 UTC, cdrage commented
I'm closing this for now as @themr0c is looking to add some new changes to the intro pages. This PR was a nice way to figure out how to get 2-depth expanding working and works well as a reference PR.

2024-02-14 14:07 UTC, closed without merging