[poc] Dialog form for extensions
containers/podman-desktop pull request #5949
Opened 2024-02-11 20:57 UTC by feloy

### What does this PR do?

Proposal for a Form Dialog extension

2024-02-11 22:08 UTC, benoitf requested changes
I don't think we would need yet another custom dialog

We have informationMessage/WarningMessage/ErrorMessage, quickpick and inputbox

2024-02-12 15:20 UTC, cdrage commented
https://github.com/containers/podman-desktop/assets/6422176/e47954c3-ae50-4b50-b15e-2d1f0b941b6c

Awesome work! I believe this would be very beneficial for any extensions that requires to ask the user multiple questions that would exceed what quickpick could do. 

Ex. simple "checkbox", or being able to see what the previous option was / go "back" and change it.

If someone were to create a https://github.com/kubernetes/kompose extension, it would be nice to ask via a form if I would like to use Deployments, as well as checkbox, and whatever else I'd like to add. 

Another point of discussion was a "quadlet" generator tool #5855 and it would beneficial having a form-style input for generating something as complicated as a systemd file.

2024-02-12 15:22 UTC, cdrage commented
My feedback:
* Integration of checkboxes?
* Follow "form" UI style-guide as per UI team mockups
* Clickable icons (perhaps PR in the future?) instead of "select" if I wanted to for example use a Linux icon for Linux, etc.

2024-02-12 15:23 UTC, benoitf commented
I would close this PR as we don't need another way

2024-02-26 07:46 UTC, feloy commented
> I would close this PR as we don't need another way


Closing this PR, as not a priority

2024-02-26 07:46 UTC, closed without merging