chore: reduce impact of Input styling
containers/podman-desktop pull request #6290
Opened 2024-03-06 18:45 UTC by deboer-tim

### What does this PR do?

Changes three things in the Input styling to reduce the changes from 1.7. This is really a judgement call, but to me these were the 3 things that reduced the impact but still kept some of the nicer aspects/improvements in the input design from #3234:

- Changes the bottom border/focus outline (stroke color) from purple to charcoal. (one suggestion was to remove it, but that's both a bigger change and IMHO this still provides some nice minor styling)
- Added a new input-field-bg variable so that you can customize the regular background of the input, and set it to charcoal-800.
- The mouse-over effect was identical to focus (rounded, full border, dark background) and was distracting if you moved the mouse over multiple Inputs. This removes the background change by making the hover effect transparent. This required moving transparent color to our new color palette, and adding a not() so that the hover affect doesn't effect focussed inputs.

### Screenshot / video of UI

1.7:

<img width="978" alt="Screenshot 2024-03-06 at 12 13 52 PM" src="https://github.com/containers/podman-desktop/assets/19958075/7a9adae0-1967-41ab-82aa-847c86916d0c">

After:

<img width="978" alt="Screenshot 2024-03-06 at 12 15 32 PM" src="https://github.com/containers/podman-desktop/assets/19958075/c69bc8cb-4bf1-4cae-9ab7-d012e1e81c63">

### What issues does this PR fix or reference?

Fixes #6220.

### How to test this PR?

Look at all inputs: search bars, preferences, etc., but especially the Run Image form.

- [x] Tests are covering the bug fix or the new feature

2024-03-06 19:42 UTC, cdrage approved these changes
Big 👍 IMHO regarding improvement, not having the backgrounds makes it a lot easier to read.

This is a great in-between / compromise between the two suggestions.

LGTM UI side.

Implementation wise I'm like 80% LGTM, I'm unsure if the `bg-[var(--pd-input-field-bg)]` is okay as I hadn't seen that type of implementation before.

2024-03-07 07:46 UTC, slemeur commented
Nice LGTM

2024-03-07 10:38 UTC, benoitf commented
AFAIK we're missing the highlighted color now.
Clicking in the field should bring the purple color

2024-03-07 10:39 UTC, benoitf requested changes
adding new colors in color-registry needs to be reviewed by UX team first

2024-03-07 15:13 UTC, deboer-tim commented
Updated in response to today's feedback, video in description updated:
- Bring back purple for hover and focus. Turns out we had an unused hover-stroke variable (!) I could use.
- Remove rounding from hover, so it only sets a (purple) bottom border.
- Remove the background again - it's a cleaner look, bg only changes on focus (not hover).

2024-03-07 15:14 UTC, benoitf approved these changes

2024-03-07 15:32 UTC, ekidneyrh approved these changes

2024-03-07 15:51 UTC, merged