feat: switch to using libpodapi for listImages
containers/podman-desktop pull request #6736
Opened 2024-04-09 19:23 UTC by cdrage

feat: switch to using libpodapi for listImages

### What does this PR do?

* Switches to now using podmanListImages for listing images, using the
  libpodapi, falling back to compat if not available
* Adds a configuration value that's hidden that can be easily changed
  if we encounter issues in the future with regards to isManifest.
* Hides any manifest images appearing in the UI, HOWEVER, you can still
  get the manifests with the podman desktop api

### Screenshot / video of UI

N/A, you should not notice any UI change, but instead if you call

window.listImages(), you should get the manifests in the list

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/6676
Closes https://github.com/containers/podman-desktop/issues/6689
Closes https://github.com/containers/podman-desktop/issues/6622

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

You can also test this via:

Building a manifest:

```
podman build --platform linux/arm64,linux/amd64 --manifest testmanifest2 .
```

And then:

1. Going to Images within PD and seeing that your manifest is NOT
   listed.
2. Adding console.log(window.listImages()) somewhere in your code you
   will be able to see that manifests are being returned now in the
   listImages() API call.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2024-04-09 20:43 UTC, dgolovin reviewed
How is this PR fixes #6689? There should be at least a test for it IMO.

2024-04-09 21:13 UTC, benoitf requested changes, later dismissed

2024-04-09 21:13 UTC, benoitf commented on packages/main/src/plugin/container-registry.ts
> +  isUseLibpodApiEnabled(): boolean {
I think the method should be for images also I find it misleading

I explain why
I may think using the method that it is to check if lipodAPI is there or not (like if using a podman connection)

But reality is that we want to use that flag for images purpose

maybe `useLibpodApiForImageList() :boolean {` or `isUsingLibpodForImages`

2024-04-09 21:13 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-init.ts
> +        },
need to add in description it's for image list

2024-04-09 21:13 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-settings.ts
> +  Enable = 'enable',
it's misleading as for example we do use libpodAPI for listing containers and turning off this flag won't change anything

so we need to be more precise saying 'for list images' 'forImageList'

2024-04-09 21:28 UTC, cdrage commented
> How is this PR fixes #6689? There should be at least a test for it IMO.

We do not show manifests in the images by filtering it out in the stores/images.ts

2024-04-09 21:38 UTC, benoitf commented on packages/renderer/src/stores/images.ts
> +  ),
missing test in ` images-spec.ts` file

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/index.ts
> +    libpodapiInit.init();
```suggestion
    const libpodApiInit = new LibpodapiInit(configurationRegistry);
    libpodApiInit.init();
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-init.ts
> +      title: 'Libpodapi',
```suggestion
      title: 'LibpodApi',
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-init.ts
> +          description: 'Enable using libpodapi for image listing instead of compatibility api',
```suggestion
          description: 'Enable using libpod API for image listing instead of compatibility API',
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-settings.ts
> +  SectionName = 'libpodapi',
```suggestion
  SectionName = 'libpodApi',
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-init.ts
> +export class LibpodapiInit {
```suggestion
export class LibpodApiInit {
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-settings.ts
> +export enum LibpodapiSettings {
```suggestion
export enum LibpodApiSettings {
```

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-settings.ts
> +/**********************************************************************
libpod-api-settings.ts

2024-04-10 14:02 UTC, benoitf commented on packages/main/src/plugin/libpodapi-enable/libpodapi-init.ts
> +/**********************************************************************
libpod-api-init.ts

2024-04-10 14:07 UTC, cdrage commented
@benoitf Quickest review I've ever seen 😮 

updated again with the libpodapi -> libpodApi naming changes

2024-04-10 14:20 UTC, cdrage commented
Apologizes for the rebasing, messed up some of the renaming, but I've gone ahead and implemented the changes as well renamed the folder too to `libpod-api-enable` instead of `libpodapi-enable`. @benoitf 

Thanks for the quick reviews!

2024-04-10 15:30 UTC, benoitf approved these changes

2024-04-10 16:17 UTC, dgolovin approved these changes

2024-04-10 16:44 UTC, merged