chore(Modal): use tailwindcss classes instead of css
containers/podman-desktop pull request #7125
Opened 2024-05-07 12:26 UTC by axel7083

### What does this PR do?

Migrating `<style>` content of the Modal to tailwindcss classes before https://github.com/containers/podman-desktop/issues/6906

### Screenshot / video of UI

### What issues does this PR fix or reference?

Related to https://github.com/containers/podman-desktop/issues/6906

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-05-07 12:44 UTC, deboer-tim requested changes
If you're fixing this, let's go all the way! Dialogs are supposed to fade the entire background like MessageBoxes do, and we shouldn't use hardcoded bg-[] color if we can avoid it.

Stealing from MessageBox I think you can change `bg-[#00000099]` to `bg-black bg-opacity-60 bg-blend-multiply z-50`.

Then:
<img width="291" alt="Screenshot 2024-05-07 at 8 34 51 AM" src="https://github.com/containers/podman-desktop/assets/19958075/689b4609-59fb-4e9c-b541-0617b41ca727">
becomes:
<img width="291" alt="Screenshot 2024-05-07 at 8 42 19 AM" src="https://github.com/containers/podman-desktop/assets/19958075/19396be0-8abf-4818-b709-4e1f06ded469">

2024-05-07 13:05 UTC, axel7083 commented
> If you're fixing this, let's go all the way! Dialogs are supposed to fade the entire background like MessageBoxes do, and we shouldn't use hardcoded bg-[] color if we can avoid it.
> 
> Stealing from MessageBox I think you can change `bg-[#00000099]` to `bg-black bg-opacity-60 bg-blend-multiply z-50`.

Maybe `MessageBox;svelte` should use the `Modal.svelte` component, what do you think @deboer-tim

2024-05-07 13:17 UTC, deboer-tim commented
> Maybe `MessageBox;svelte` should use the `Modal.svelte` component, what do you think @deboer-tim 

The original use/implementation was different enough that I don't think it made sense, but you're probably right now and would clean up some duplication - just not in this/one PR. e.g. I would still merge this, then we could clean up anything remaining in Modal/make it reusable, then migrate MessageBox.

2024-05-07 13:52 UTC, deboer-tim approved these changes

2024-05-08 09:40 UTC, lstocchi approved these changes

2024-05-10 04:01 UTC, benoitf approved these changes

2024-05-10 04:01 UTC, merged