Light mode for Images and Volumes table
containers/podman-desktop pull request #7151
Opened 2024-05-10 09:05 UTC by feloy

Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Light mode for Images and Volumes table

### Screenshot / video of UI

### What issues does this PR fix or reference?

Fixes #6890

### How to test this PR?

2024-05-10 09:08 UTC, feloy commented
Hi @ekidneyrh If this can help, I created the colors registry for the table theming, with colors extracted from sources. Feel free to change the names of the colors, and/or rearrange it as your preference.

I have set red/green colors for the light mode, I let you define proper colors instead.

2024-05-10 09:10 UTC, ekidneyrh commented
> Hi @ekidneyrh If this can help, I created the colors registry for the table theming, with colors extracted from sources. Feel free to change the names of the colors, and/or rearrange it as your preference.
> 
> I have set red/green colors for the light mode, I let you define proper colors instead.

thanks!!

2024-05-10 12:15 UTC, deboer-tim commented
The hover color for dark is incorrect. Current:

https://github.com/containers/podman-desktop/assets/19958075/1b577991-089e-481d-ae7d-73d6fc0e56b9

With PR:

https://github.com/containers/podman-desktop/assets/19958075/7bf86dc2-5367-44db-892b-0882417400e1

2024-05-13 08:09 UTC, feloy commented
> The hover color for dark is incorrect. Current:
> 
>  Screen.Recording.2024-05-10.at.8.12.21.AM.mov 
> With PR:
> 
>  Screen.Recording.2024-05-10.at.8.11.31.AM.mov

Yes, this is marked as TODO, as the original value is `zinc-700`, but the zinc color is not defined in the color palette:
```
      dark: colorPalette.charcoal[700], // TODO was zinc[700]
```
@ekidneyrh what do we want to do? Keep zinc-700 (I'll add the zinc color in the palette if so), or change to another color already in the palette?

2024-05-15 09:46 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      dark: colorPalette.charcoal[500], // was zinc[700]
Charcoal 500 is good, and i'd put in purple-200 for light mode

2024-05-15 10:10 UTC, ekidneyrh requested changes
Left comments for the relevant changes! Thanks @feloy :)

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.charcoal[500], // TODO
charcoal-500 is good and i would put in purple-200 for light mode

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.gray[600], // TODO
light mode: charcoal-200

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.charcoal[200], // TODO
light mode: charcoal-300

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.gray[700], // TODO
light mode: charcoal-300

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.gray[300], // TODO
light mode: charcoal-300

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.purple[400], // TODO
dark mode is good for purple-400
light mode: purple-700

2024-05-15 10:10 UTC, ekidneyrh commented on packages/main/src/plugin/color-registry.ts
> +      light: colorPalette.gray[400], // TODO
Light mode: charcoal-200

2024-05-15 12:04 UTC, feloy commented
Thanks @ekidneyrh for the light mode colors. I have added a commit with them.

Here is the result:
<img width="1118" alt="light-mode-images" src="https://github.com/containers/podman-desktop/assets/9973512/fa7993a4-ec9a-478f-ab1c-407758711cec">

The content of the Environment column is remaining. I'm wondering if this is part of this issue, or if this kind of label can be considered as a generic one (at least colorwise). For example, it is very similar to the one displaying the cluster reachability (but for now, the text color slightly differs):
<img width="973" alt="light-mode-env" src="https://github.com/containers/podman-desktop/assets/9973512/66bcada9-3943-4844-807b-8c2cc784f1bd">

<img width="986" alt="light-mode-reachable" src="https://github.com/containers/podman-desktop/assets/9973512/406dd512-ba24-4cba-94d2-561e019d0229">

2024-05-16 12:50 UTC, benoitf approved these changes

2024-05-16 14:32 UTC, ekidneyrh commented
I think it could be left as a generic one - separate ticket, maybe? The text colour can be matched so they are the same, that shouldn't be an issue

2024-05-16 14:32 UTC, ekidneyrh approved these changes

2024-05-16 14:42 UTC, merged