chore: remove test containerfile
containers/podman-desktop pull request #7163
Opened 2024-05-10 15:13 UTC by cdrage

chore: remove test containerfile

### What does this PR do?

Removes an old bootc container file that is no longer needed / should
not be referenced (uses an old FROM, as well as very insecure RUN
command)

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

N/A

### How to test this PR?

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2024-05-10 15:18 UTC, deboer-tim approved these changes

2024-05-10 15:21 UTC, cbr7 requested changes
Why are you removing all three files? Only the bootable-containerfile should be removed, the other two are in use in tests.

2024-05-10 15:22 UTC, cdrage commented
> Why are you removing all three files? Only the bootable-containerfile should be removed, the other two are in use in tests.

Woops, I removed the directory instead of just the single file by mistake. Updated

2024-05-10 15:37 UTC, cbr7 approved these changes

2024-05-11 10:48 UTC, benoitf approved these changes

2024-05-12 15:52 UTC, merged