chore(ci): switch workflows that runs e2e and standard tests to use u…
containers/podman-desktop pull request #7266
Opened 2024-05-21 12:21 UTC by odockal

…buntu-2404 beta runner

### What does this PR do?
Switches ubuntu runner from 22.04 to 24.04 for workflows that run tests
### Screenshot / video of UI

### What issues does this PR fix or reference?
#7234 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-05-21 12:32 UTC, benoitf approved these changes

2024-05-21 12:35 UTC, deboer-tim approved these changes

2024-05-21 15:26 UTC, odockal commented
There is some problem with running an alpine container on ubuntu 24.04. Thus containers-smoke test is failing with: 
`sd-bus call: Interactive authentication required.: Permission denied`.
On my local ubuntu VM all works. so it might be a runner configuration.

2024-05-27 10:16 UTC, jeffmaury requested changes, later dismissed
Seems to me that crun cannot run containers in this configuration

2024-05-27 11:56 UTC, odockal commented
> Seems to me that crun cannot run containers in this configuration

Yes. I would like to take closer look on the problem with debugging the podman on the machine.

2024-08-28 12:30 UTC, benoitf commented
closing as no activity

2024-11-14 08:09 UTC, odockal commented
@jeffmaury @benoitf I have reopened the PR as I got some ideas how to fix the problem. This is all about switching to new beta runner for e2e tests workflows. Next step/PR is to install Podman 5.2.5 via kubic repos. I have tested it all together, but I decided to create smaller PRs for each change that will follow.

2024-11-14 08:33 UTC, cbr7 approved these changes

2024-11-14 08:39 UTC, benoitf approved these changes

2024-11-14 08:54 UTC, merged