feat: add k8s age column to ingress / routes
containers/podman-desktop pull request #7312
Opened 2024-05-27 18:34 UTC by cdrage

feat: add k8s age column to ingress / routes

### What does this PR do?

* Adds the age column for ingress / services k8s page
* Added simple test

### Screenshot / video of UI

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/5978

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

Open up ingress / routes and see age has been added.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2024-05-27 19:41 UTC, deboer-tim requested changes
Code looks good and UI works well - but linter error and UI always says '16 hours' for me. I would have expected a change in ingress-route-utils.ts to set `created` so I suspect there is a change missing from the commit. :)

2024-05-27 22:37 UTC, cdrage commented
> Code looks good and UI works well - but linter error and UI always says '16 hours' for me. I would have expected a change in ingress-route-utils.ts to set `created` so I suspect there is a change missing from the commit. :)

Updated!

2024-05-28 12:32 UTC, axel7083 approved these changes
LGTM Codewise

2024-05-28 13:17 UTC, deboer-tim approved these changes

2024-05-28 16:06 UTC, merged