website: updating troubleshooting guide
containers/podman-desktop pull request #769
Opened 2022-11-03 15:10 UTC by deekay2310

Signed-off-by: Dev Kumar <devskumar99@gmail.com>

### What does this PR do?
Added a section pertaining to Podman Engine in the troubleshooting guide

### Screenshot/screencast of this PR

<img width="1440" alt="Screen Shot 2022-11-03 at 11 08 59 AM" src="https://user-images.githubusercontent.com/29257773/199759146-a8d045fb-ad54-4d6f-b7f2-ffb71877700f.png">
![Screen Shot 2022-11-03 at 11 09 09 AM](https://user-images.githubusercontent.com/29257773/199759147-b43cf91c-4d63-4dbb-9c8d-35481b53cd7d.png)
![Screen Shot 2022-11-03 at 11 09 21 AM](https://user-images.githubusercontent.com/29257773/199759148-e52ac028-c4fe-4c5f-9850-dafdeeffbc17.png)

### What issues does this PR fix or reference?

### How to test this PR?

2022-11-03 17:37 UTC, slemeur requested changes

2022-11-03 17:37 UTC, slemeur commented on website/docs/troubleshooting.md
> +This section of documentation provides way to troubleshoot problems with Podman Desktop.
```suggestion
If you cannot find your issue here or in the documentation, please fill an issue on our [repository](https://github.com/containers/podman-desktop/issues). You can also explore the [discussions](https://github.com/containers/podman-desktop/discussions) and do a search on similar issues on the [repository](https://github.com/containers/podman-desktop/issues).
```

2022-11-03 17:37 UTC, slemeur commented on website/docs/troubleshooting.md
> +### Getting Started
```suggestion
### Unable to see any image or container after downloading Podman Desktop
```

2022-11-03 17:37 UTC, slemeur commented on website/docs/troubleshooting.md
> +### Getting Started
Are you sure that's really the case? 
Is this not something handled by pre-flight checks?

2022-11-07 14:50 UTC, deekay2310 commented on website/docs/troubleshooting.md
> +### Getting Started
I used the verbatim that existed previously on the guide. Is it subject to change?
<img width="848" alt="Screen Shot 2022-11-07 at 9 50 02 AM" src="https://user-images.githubusercontent.com/29257773/200339740-28ef6651-d62d-4ab7-996c-55e3a803aef5.png">

2022-11-14 17:39 UTC, slemeur approved these changes
LGTM

2022-11-15 13:20 UTC, merged