feat: Add more options when creating containers
containers/podman-desktop pull request #773
Opened 2022-11-04 08:49 UTC by benoitf

### What does this PR do?
Until now we could only specify port binding

Now it includes several options including volumes, env variables, some more advanced options, networking and security options

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/199931036-9101384f-b732-460e-8ece-f20fa732e4fa.mp4

### What issues does this PR fix or reference?

#375 

### How to test this PR?

Select an image and tries to start a custom container

2022-11-04 12:51 UTC, slemeur commented
Love it. There are things in the UI we could improve, but it's really strong! 

cc @rhatdan you should see this!

2022-11-04 13:09 UTC, benoitf commented
Missing things:
- [ ] https://github.com/containers/podman-desktop/issues/777
- [ ] https://github.com/containers/podman-desktop/issues/778

2022-11-07 15:07 UTC, cdrage requested changes
Minor UI changes submitted!

Code-wise it's amazing and I had no problem creating a three separate containers.

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Container Name:</label>
```suggestion
                  >Container name:</label>
```

This is capitalized, but other parts (like "Environment variables") isn't. I think the form shouldn't have capitalization.

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  class="pt-4 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Port Mapping:</label>
```suggestion
                  class="pt-4 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Port mapping:</label>
```

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Use tty:</label>
```suggestion
                  >Use TTY:</label>
```

TTY is an acronym and should be capitalized.

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Auto Removal of containers:</label>
```suggestion
                  >Auto removal of container:</label>
```

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  Automatically remove the container when the container's process exits
```suggestion
                  Automatically remove the container when the process exits
```

You repeat container twice, should be shortened

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Restart Policy. Behaviour when container is exiting:</label>
```suggestion
                  >Restart policy:</label>
```

I feel like this could be shortened to just `Restart policy:`

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                    >Policy Name:</span>
```suggestion
                    >Policy name:</span>
```

remove capitalization so it's same elsewhere

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                    placeholder="The hostname to use for the container, as a valid RFC 1123 hostname."
```suggestion
                    placeholder="Must be a valid RFC 1123 hostname"
```

We already describe "container hostname" in title, it's already implied were entering it.

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Custom DNS servers to use for this container:</label>
```suggestion
                  >Custom DNS server(s):</label>
```

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Add extra hosts (to /etc/hosts file):</label>
```suggestion
                  >Add extra hosts (appends to /etc/hosts file):</label>
```

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  Turn off security<i class="fas fa-exclamation-triangle"></i>
Add spacing to triangle to the left? `pl-1` maybe?

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  class="pt-4 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Read Only:</label>
```suggestion
                  class="pt-4 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Read only:</label>
```

2022-11-07 15:07 UTC, cdrage commented on packages/renderer/src/lib/image/RunImage.svelte
> +                  >Security Options (security-opt):</label>
```suggestion
                  >Security options (security-opt):</label>
```

2022-11-07 15:47 UTC, cdrage approved these changes
Lint / format failing, but these changes LGTM!

2022-11-07 16:00 UTC, benoitf commented
yes I'll fix formatting after applying your suggested changes and looking at icon's suggestion

2022-11-08 13:03 UTC, cdrage commented
LGTM!

2022-11-08 13:03 UTC, cdrage approved these changes

2022-11-08 19:41 UTC, merged