chore: adds missing colors for modal dropdown element
containers/podman-desktop pull request #8437
Opened 2024-08-13 05:33 UTC by gastoner

### What does this PR do?
Adds missing colors for modal dropdown element

Reference:
https://github.com/user-attachments/files/16070597/Modal.Dialog.pdf

### What issues does this PR fix or reference?
One of two PRs for 8411 "Light Mode: Input boxes (changing kube-context) still using dark theme when in Light Mode"

- [x] Tests are covering the bug fix or the new feature

2024-08-13 07:37 UTC, axel7083 approved these changes
LGTM

2024-08-13 13:48 UTC, deboer-tim requested changes
We have dropdown (select controls) in many places - preferences, deploying pods to kube, etc.

We really need a consistent component (#6199) and to reuse it in most of these places, and reuse the colors where we can't. I'm good with fixing this as a 'one off', but I think we should define the colors as we would use them in a component - i.e. separately in an initDropdown() vs colors specific to a dropdown in a modal.

2024-08-14 12:49 UTC, gastoner commented
@deboer-tim So, do I get it right that I should move it to initDropdown? Or should I use existing colors, which are already there?

2024-08-14 18:00 UTC, deboer-tim commented
> @deboer-tim So, do I get it right that I should move it to initDropdown? Or should I use existing colors, which are already there?

Sorry, I didn't realize there was an existing initDropdown() - but yes, you should be able to use colors from there (we shouldn't have different colors for dropdown in modal vs dropdown elsewhere), or edit/add to that function.

2024-08-20 11:25 UTC, ekidneyrh commented
I might be looking at the wrong place but I cant see the changes. Would I be able to see a screenshot? Or is just change in the code rather than a visual change?

2024-08-22 05:50 UTC, gastoner commented
> I might be looking at the wrong place but I cant see the changes. Would I be able to see a screenshot? Or is just change in the code rather than a visual change?

@ekidneyrh So far it is just change in the code, I would add the visual changes in the next PR. 
Issue ref. https://github.com/containers/podman-desktop/issues/8411
Colors: https://github.com/user-attachments/files/16070597/Modal.Dialog.pdf

2024-08-26 07:27 UTC, gastoner commented
@deboer-tim PR updated!

2024-08-26 08:29 UTC, ekidneyrh approved these changes
LGTM :) Thanks Evzen!

2024-09-03 21:09 UTC, deboer-tim reviewed
Just back from PTO. Thanks for making the changes, but it still looks to me like the code is implying that dropdowns in modals are going to be different from other dropdowns. Is this actually the case (why?) or could we keep the prefixes consistent with just `${dropdown}`?

2024-09-04 08:40 UTC, gastoner commented
> Just back from PTO. Thanks for making the changes, but it still looks to me like the code is implying that dropdowns in modals are going to be different from other dropdowns. Is this actually the case (why?) or could we keep the prefixes consistent with just `${dropdown}`?

@deboer-tim 
Honestly, I don't know why it is called the dropdown in the first place, It seems to me like a totally different component with different behavior (e.g. can be indexed by arrows, and have input to filer-out some contexts). But yes it shows the options in the dropdown.

2024-09-05 19:30 UTC, deboer-tim approved these changes

2024-09-05 20:16 UTC, cdrage approved these changes

2024-09-05 20:16 UTC, merged