Pretty display command in image layer
containers/podman-desktop pull request #8535
Opened 2024-08-21 14:11 UTC by feloy

Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Display the command used to create an image layer with formatting, and displaying only the first 2 lines, with a `show more`/`show less` link helping displaying the full command 
 
### Screenshot / video of UI

https://github.com/user-attachments/assets/3ea1fe1a-b1e2-4975-abf9-008decf81c45

### What issues does this PR fix or reference?

Fixes #8156 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-08-21 14:14 UTC, benoitf requested changes
👍 but it's missing tests

2024-08-21 14:18 UTC, feloy commented
> 👍 but it's missing tests

Wanted to be sure the design is ok before to write the tests. I'll work on them

2024-08-21 17:18 UTC, benoitf approved these changes

2024-08-22 07:58 UTC, lstocchi approved these changes
LGTM, nice job 🚀

2024-08-22 07:59 UTC, merged