feat: default_action_for_Containers_empty_state
containers/podman-desktop pull request #8651
Opened 2024-08-29 11:16 UTC by gastoner

### What does this PR do?
Adds button to Container empty state screen 
=> User can use button/command to do the same action

### Screenshot / video of UI

![image](https://github.com/user-attachments/assets/43314b0b-5cd4-4c97-98d2-10ad4af1924b)

### What issues does this PR fix or reference?

Closes #8568 

### How to test this PR?

-Delete all Containers
-Assert that you see the button (TODO: hide button on Running/Stopped tab)

- [ ] Tests are covering the bug fix or the new feature

2024-08-29 11:29 UTC, feloy commented
I think that the user will want some feedback between the time it clicks the button and the time the container is started, to understand that the operation is in progress. For example setting the button in progress mode?

2024-08-29 11:54 UTC, feloy commented on packages/renderer/src/lib/container/ContainerEmptyScreen.svelte
> +      const image = (await listImages).find(item => item.RepoTags?.includes(helloImage));
```suggestion
      const listImages = await window.listImages();
      const image = listImages.find(item => item.RepoTags?.includes(helloImage));
```

2024-08-29 11:54 UTC, feloy commented on packages/renderer/src/lib/container/ContainerEmptyScreen.svelte
> +        console.error(`Could not find ${helloImage} in images`);
you could use a dialog box, as the logs won't appear to the /normal/ user

2024-08-29 11:54 UTC, feloy commented on packages/renderer/src/lib/container/ContainerEmptyScreen.svelte
> +    console.error(`Error while executing ${commandLine}: ${String(err)}`);
same here

2024-08-29 14:28 UTC, feloy commented
At the beginning, the EmptyScreen component was very constrained, with only icon/title/message/detail/commandline.

After, has been introduced the default slot (free form) placed at the bottom of the component.

With these changes, we are adding a named slot, to add its (free form) content between the title and the detail.

To add more consistency to the component, I would consider:
- either making an inventory of the usages we do of the component, and find an abstraction to keep it constrained as it was at the beginning
- or making it mostly completely free-form, with only an icon/title as parameters

@slemeur @jeffmaury @ekidneyrh

2024-08-30 07:08 UTC, gastoner commented
> At the beginning, the EmptyScreen component was very constrained, with only icon/title/message/detail/commandline.
> 
> After, has been introduced the default slot (free form) placed at the bottom of the component.
> 
> With these changes, we are adding a named slot, to add its (free form) content between the title and the detail.
> 
> To add more consistency to the component, I would consider:
> 
>     * either making an inventory of the usages we do of the component, and find an abstraction to keep it constrained as it was at the beginning
> 
>     * or making it mostly completely free-form, with only an icon/title as parameters
> 
> 
> @slemeur @jeffmaury @ekidneyrh

Thanks Philippe! Personally I would suggest the second option, make it free form with icon and title as parameters

2024-09-02 10:30 UTC, jeffmaury approved these changes
LGTM but I think the slot should be named differently as it's more that a button

2024-09-02 10:31 UTC, jeffmaury commented
Maybe a tooltip on the button saying that it's will put quay.io/podman/hello and start it would be good

2024-09-02 11:46 UTC, gastoner commented
@jeffmaury e.g. "Pull quay.io/podman/hello:latest image and start container" and slot could be named "upperContent"?

2024-09-03 11:25 UTC, feloy requested changes

2024-09-03 11:25 UTC, feloy commented on packages/preload/vite.config.js.timestamp-1725005385529-5571b54447365.mjs
> +// .electron-vendors.cache.json
I suppose this file should be removed

2024-09-03 11:30 UTC, gastoner commented on packages/preload/vite.config.js.timestamp-1725005385529-5571b54447365.mjs
> +// .electron-vendors.cache.json
@feloy removed!

2024-09-03 11:31 UTC, feloy approved these changes
LGTM

2024-09-03 12:51 UTC, merged

2024-09-16 07:19 UTC, benoitf commented
looking at another PR linking this one, I see that no unit tests were provided for this new feature while it should