feat: allow to set a zoom level
containers/podman-desktop pull request #8747
Opened 2024-09-04 14:27 UTC by benoitf

### What does this PR do?
user can define a zoom to get bigger fonts/UI elements inside Podman Desktop

### Screenshot / video of UI

https://github.com/user-attachments/assets/4b0ef3e0-5a36-4219-aff2-e28ada06f8ec

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/8640

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

2024-09-04 14:39 UTC, axel7083 commented on packages/main/src/plugin/appearance-settings.ts
> +
```suggestion
```

2024-09-04 14:41 UTC, gastoner reviewed
I got some unexpected inc/dec steps (only in zoom level)



https://github.com/user-attachments/assets/1cc2672f-1198-496f-8bb7-73d05a88ad52

2024-09-04 14:44 UTC, benoitf commented
@gastoner the PR wasn't including https://github.com/containers/podman-desktop/pull/8705

I rebased the PR, so please retry

2024-09-04 14:44 UTC, axel7083 commented
> I got some unexpected inc/dec steps (only in zoom level)

Facing the same issue 

https://github.com/user-attachments/assets/c8c9700d-db83-419a-9ba8-2490d8d005e3

2024-09-04 14:44 UTC, benoitf commented
also anyway it's not related to this PR

2024-09-04 14:51 UTC, axel7083 approved these changes
LGTM the only element I would notice is the delay, but I suppose this is expected due to the event architecture.

2024-09-04 15:24 UTC, gastoner approved these changes
Same as Axel

2024-09-04 19:34 UTC, dgolovin requested changes, later dismissed
This PR mess up with Ctrl +/- zoom in different ways. 

1. If I set it up with Ctrl +/- and restart podman desktop it going to reset to zoom level in settings, not one I had in previous session.
2. If I set zoom with Ctrl +/- and switch to Appearance prefernces it resets is right away to zoom level stored in preferences

This fix should probably write/read window zoom level directly rather then store it in preferences.

Another option listen to window zoom level and update value saved in preferences.

2024-09-04 19:38 UTC, benoitf commented
There is no listener / event AFAIK for the shortcuts, only for mouse scroll

2024-09-04 20:12 UTC, dgolovin commented
There is https://github.com/electron/electron/blob/main/docs/api/web-contents.md#event-zoom-changed 'zoom-changed' event, but I have not tested it.

2024-09-04 20:13 UTC, benoitf commented
Emitted when the user is requesting to change the zoom level using the mouse wheel.

2024-09-04 20:14 UTC, benoitf commented
I'll investigate other ways of intercepting

2024-09-05 17:06 UTC, dgolovin commented
The 'resize' event is triggered every time I zoom in/out. ResizeObserver can be used on always visible element, nav for example, to detect zoom change. 

```
diff --git a/packages/renderer/src/AppNavigation.svelte b/packages/renderer/src/AppNavigation.svelte
index 0eaada6f88..b8349d81da 100644
--- a/packages/renderer/src/AppNavigation.svelte
+++ b/packages/renderer/src/AppNavigation.svelte
@@ -25,10 +25,13 @@ let authActions = $state<AuthActions>();
 let outsideWindow = $state<HTMLDivElement>();
 
 const iconSize = '22';
-
+const resizeObserver = new ResizeObserver(() => {
+  console.log('zoom detected');
+})
 onMount(async () => {
   const commandRegistry = new CommandRegistry();
   commandRegistry.init();
+  resizeObserver.observe(document.getElementById('navigation') as Element);
 });
 
 function clickSettings(b: boolean) {
@@ -41,7 +44,7 @@ function clickSettings(b: boolean) {
 </script>
 
 <svelte:window />
-<nav
+<nav id="navigation"
   class="group w-leftnavbar min-w-leftnavbar flex flex-col hover:overflow-y-none bg-[var(--pd-global-nav-bg)] border-[var(--pd-global-nav-bg-border)] border-r-[1px]"
   aria-label="AppNavigation">
   <NavItem href="/" tooltip="Dashboard" bind:meta={meta}>
~
```

the test above prints 'zoom detected' when window size or zoom changed.

2024-09-05 17:10 UTC, benoitf commented
@dgolovin it seems it's not the case on some os ( I found some items on GitHub issues or stack overflow when implementing this PR)

I switched then to https://github.com/containers/podman-desktop/pull/8760

where we'll define our shortcuts ( and then can handle when user is calling it) and it'll also fix issues where zoom in/out shortcuts are not working on Windows or Linux as expected

2024-09-06 13:46 UTC, benoitf commented
removing previous reviews as I reworked the entire stuff

new actions to perform `zoom in` , `zoom out` or `zoom reset`

and using shortcuts should persist the value of the configuration property

2024-09-06 15:17 UTC, axel7083 reviewed
https://github.com/user-attachments/assets/a1318f15-4d28-491a-a3de-4f09ef9a25cf

If I zoom on the preference page, I don't see the value being updated directly, otherwise everything seems to be working great

2024-09-07 05:41 UTC, dgolovin requested changes
Tested it and noticed couple issues:
1. When I am using key combination to zoom in/out if I do it multiple times back and forth the zoom value is getting values like `1.0000000003` very quickly
2. When zooming with key combination if I get value over 3 and then switch to appearance settings the zoom resets to 0.

2024-09-07 05:59 UTC, dgolovin commented
From usability point of view showing zoom level in % would be much better. Firefox shows it in % too 

![image](https://github.com/user-attachments/assets/94a0eee1-35d9-4601-86f6-776c6bff9ec1)

2024-09-07 16:37 UTC, benoitf commented
https://github.com/containers/podman-desktop/pull/8793 and https://github.com/containers/podman-desktop/pull/8795 would at least need to be merged

2024-09-09 08:43 UTC, benoitf commented
rebased to include two fixes that have been merged

2024-09-09 09:12 UTC, axel7083 reviewed
https://github.com/user-attachments/assets/cd06cfeb-2996-4b4b-ab38-c755229667d6

Everything seems to be working well, except a weird flickering when using `ctrl + num0` (from numpad) to reset the zoom.

As visible in the video, weird behavior

2024-09-10 05:15 UTC, dgolovin approved these changes
LGTM

There are minor glitches that does not really affect user experience.
1. After start change zoom and go to preferences page and try to use +/- button and and the value is not updated on the page, then it suddenly starts to work (hard to replicate)
2. I also could not to set value to 1 using +/i values, then it started to work

2024-09-11 09:42 UTC, benoitf commented
ok, no other reviews since a couple of days, 2 approvals and no required changes, will merge

2024-09-11 11:29 UTC, merged