Implement E2E test scenario to cover Nodes Page
containers/podman-desktop pull request #8761
Opened 2024-09-05 13:32 UTC by amisskii

### What does this PR do?

introduces E2E test scenario to cover Nodes Page

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/8649

2024-09-09 14:19 UTC, cdrage approved these changes
Renderer section fine by me! Will need another approval by QE team regarding the playwright section, but otherwise LGTM.

2024-09-10 08:42 UTC, odockal requested changes

2024-09-10 08:42 UTC, odockal commented on tests/playwright/src/specs/kubernetes.spec.ts
> +    await playExpect.poll(async () => node).toBeTruthy();
Please improve expects to be more precise regarding found row.

2024-09-10 08:42 UTC, odockal commented on tests/playwright/src/model/workbench/navigation.ts
> +      await expect(this.kubernetesButton).toBeEnabled();
maybe consider check for expanded/collapsed?

2024-09-10 08:42 UTC, odockal commented on tests/playwright/src/model/pages/kubernetes-resources-page.ts
> +  async getRowFromTableByName(name: string): Promise<Locator | undefined> {
This function can be simplified, since the table contains elements with:
```
role='row' and aria-label='node-name'
```

2024-09-10 12:53 UTC, cbr7 commented on tests/playwright/src/model/pages/kubernetes-resource-page.ts
> +  }
This method doesn't need to be async, it returns a Locator object.

```suggestion
  getResourceRowByName(resourceName: string): Locator {
    return this.content.getByRole('row', { name: resourceName });
  }
```

2024-09-10 12:54 UTC, cbr7 commented on tests/playwright/src/model/pages/kubernetes-resource-page.ts
> +    await resourceRowName.click();
This should be checked for clickablity before clicking on it, or at least that it exists.

2024-09-10 12:57 UTC, cbr7 commented on tests/playwright/src/specs/kubernetes.spec.ts
> +    const nodesPage = await navigationBar.openKubernetesResources(KubernetesResources.Nodes);
You should validate the page navigation after this line.

2024-09-10 12:58 UTC, cbr7 commented on tests/playwright/src/specs/kubernetes.spec.ts
> +    await playExpect(nodeRow).toBeVisible();
```suggestion
    await playExpect(nodesPage.getResourceRowByName(KIND_NODE)).toBeVisible();
```

2024-09-10 12:59 UTC, cbr7 commented on tests/playwright/src/specs/kubernetes.spec.ts
> +    const nodeDetails = await nodesPage.openResourceDetails(KIND_NODE);
Validate navigation after this line.

2024-09-10 13:00 UTC, cbr7 commented on tests/playwright/src/utility/operations.ts
> +      },
```suggestion
      async () =>  await getVolumeNameForContainer(page, containerName),
```

2024-09-10 13:21 UTC, cbr7 approved these changes

2024-09-10 14:14 UTC, odockal approved these changes

2024-09-10 14:15 UTC, odockal commented
@amisskii good work. check linter/formatter problem in PR check jobs.

2024-09-11 08:58 UTC, merged