fix: allow to show Open DevTools menu items for extensions and webviews
containers/podman-desktop pull request #8889
Opened 2024-09-14 17:12 UTC by dgolovin

### What does this PR do?

The fix allows to show Open DevTools menu for webviews without checking if webview is loaded. 
If it is not loaded then menu selection does nothing.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fix #8752

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-09-16 05:12 UTC, feloy approved these changes

2024-09-16 06:33 UTC, jeffmaury approved these changes
LGTM

2024-09-16 07:21 UTC, benoitf requested changes
no unit tests

2024-09-17 06:49 UTC, benoitf approved these changes
thanks

2024-09-17 06:50 UTC, benoitf commented on packages/main/src/mainWindow.ts
> +import * as developmentItemsMenuBuilder from './development-menu-builder.js';
can we just import the function ?

2024-09-17 15:16 UTC, merged