fix: redirect kube page to pods page
containers/podman-desktop pull request #8899
Opened 2024-09-16 11:21 UTC by deboer-tim

### What does this PR do?

window.history.go doesn't work, just goto the pods page since that is the only page the play kube button is available from and equivalent to what we do on some other forms.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes #8652.

### How to test this PR?

Go to Pods page and click Play Yaml, play a valid yaml file and then confirm clicking Done works.

2024-09-16 11:24 UTC, axel7083 commented on packages/renderer/src/lib/kube/KubePlayYAML.svelte
> +  router.goto('/pods');
import { handleNavigation } from '/@/navigation';
handleNavigation({
  page: NavigationPage.PODS,
});

2024-09-16 11:29 UTC, deboer-tim commented on packages/renderer/src/lib/kube/KubePlayYAML.svelte
> +  router.goto('/pods');
Fixed.

2024-09-16 11:55 UTC, axel7083 commented on packages/renderer/src/lib/kube/KubePlayYAML.svelte
> +  router.goto('/pods');
Missing push ?

2024-09-16 12:20 UTC, deboer-tim commented on packages/renderer/src/lib/kube/KubePlayYAML.svelte
> +  router.goto('/pods');
Yes, fixed now 😆

2024-09-16 13:05 UTC, axel7083 approved these changes
LGTM :rocket:

2024-09-16 13:36 UTC, benoitf requested changes
Code LGTM but missing unit tests

2024-09-17 09:22 UTC, axel7083 approved these changes
LGTM

2024-09-17 10:15 UTC, benoitf approved these changes

2024-09-17 10:35 UTC, merged