feat: add default actions for Pods empty state
containers/podman-desktop pull request #8963
Opened 2024-09-19 05:37 UTC by dgolovin

### What does this PR do?

Adds button 'Start my first pod' to Pods page empty screen

### Screenshot / video of UI

https://github.com/user-attachments/assets/5092922c-060f-4711-afe2-9ecc33f75142

### What issues does this PR fix or reference?

Fix #8570.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-09-19 05:43 UTC, feloy requested changes

2024-09-19 05:43 UTC, feloy commented on packages/renderer/src/lib/pod/PodEmptyScreen.spec.ts
> + * Copyright (C) 2023-2024 Red Hat, Inc.
```suggestion
 * Copyright (C)2024 Red Hat, Inc.
```

2024-09-19 05:43 UTC, feloy commented on packages/renderer/src/lib/pod/PodEmptyScreen.spec.ts
> +import { afterEach } from 'node:test';
```suggestion
import { afterEach } from 'vitest';
```

2024-09-20 05:50 UTC, feloy approved these changes
LGTM

I don't find very demonstrative to start a pod with only the infra container. I think it would be better to start a pod with some payload

2024-09-20 07:14 UTC, dgolovin commented
> LGTM
> 
> I don't find very demonstrative to start a pod with only the infra container. I think it would be better to start a pod with some payload

Sounds good to me, because without payload even terminal cannot function. Will look into it.

2024-09-23 10:21 UTC, benoitf commented
setting draft mode as there will be changes

2024-09-24 07:20 UTC, feloy approved these changes
LGTM
Thanks for adding the hello container

2024-09-24 15:41 UTC, merged