chore: reduce size of kubernetes navigation
containers/podman-desktop pull request #9090
Opened 2024-09-25 14:11 UTC by cdrage

chore: reduce size of kubernetes navigation

### What does this PR do?

* Reduces the size of the navigation menu to 'mini' version that's passed
into SubmenuNavigation.
* Adds "mini" version which is just a reduced width version of the
  submenu

Font improvements in the future (if needed) for the "mini" version which
may come in handy with other submenu components in the future that need
that whitespace.

### Screenshot / video of UI

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/8771

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2024-09-25 14:40 UTC, benoitf requested changes
This issue was not planned for this sprint. (It is not planned until 1.14)
UX team needs to provide first the proper design, it's still under exploration.

2024-09-25 14:51 UTC, cdrage commented
> This issue was not planned for this sprint. (It is not planned until 1.14) UX team needs to provide first the proper design, it's still under exploration.

No problem, I'll close for now, was exploring what we should do. 

Issue https://github.com/containers/podman-desktop/issues/8771 was in backlog for this current sprint and not marked for 1.14 so thought to bring it up.

Should we mark it 1.14 and switch to next sprint?

2024-09-25 14:52 UTC, closed without merging

2024-09-25 15:05 UTC, benoitf commented
@cdrage anyway thanks for the exploration but yes AFAIK it was not planned, it's not yet 1.14 as the goals are not yet fully fixed

Also it'll need to work with AI Lab that is using the same layout.

2024-09-25 15:43 UTC, cdrage commented
> @cdrage anyway thanks for the exploration but yes AFAIK it was not planned, it's not yet 1.14 as the goals are not yet fully fixed
> 
> Also it'll need to work with AI Lab that is using the same layout.

Yup I agree, they will be using the same layout with the submenu, so it'll be good to have that as a "mini" boolean option.

Either way, we'll coordinate with @ekidneyrh

2024-10-04 12:10 UTC, ekidneyrh commented
@cdrage I dont like that the categories spill over onto two lines instead of one. A reduction on the font size, a step down of what it is atm, would work and then have the padding be equal on the right and left of the categories - it'll matter most on the longest category. This will make it not look as squashed and be more breathable. 

We could alternatively have an icon assigned to each category and have an option to only show the icons in the mini menu if the user wishes for more room. This could be something we could bring to AI Lab too if the menu concern is also there @axel7083 

Or a collapsible menu that the user can hide?