fix: proxy settings state not updating on change
containers/podman-desktop pull request #9442
Opened 2024-10-17 12:37 UTC by FrCornaire

Signed-off-by: Francis CORNAIRE <francis.cornaire@axa.fr>

### What does this PR do?

Fix Proxy Settings state not being updated when the UI state changed

### Screenshot / video of UI

Current behavior
![theProblem](https://github.com/user-attachments/assets/50bd41e1-6a6b-4e84-862c-10bbf08ccc69)

The fix
![theFix](https://github.com/user-attachments/assets/6b877141-7937-475d-8f3e-a241b3b8e371)

### What issues does this PR fix or reference?

#9379

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-10-17 13:17 UTC, axel7083 commented
Hi @FrCornaire thanks for the pull request and the fix!

With the fix you are providing, the inputs are often visible, often not. This is because of the following line

https://github.com/containers/podman-desktop/blob/109741f9571b67989a5226d4d6201e98874bbef0/packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte#L88

where we only display the proxy inputs if the config exists, but as you are updating it, we may need to add a condition:

```diff
- {#if proxySettings} 
+ {#if proxySettings && proxyState === ProxyState.PROXY_MANUAL} 
``` 

This would make the proxy inputs only visible if we selected the `PROXY_MANUAL` manual state. Do you think you can make the change ?

2024-10-17 13:38 UTC, FrCornaire commented
Sure!

2024-10-17 13:54 UTC, jeffmaury commented
> Hi @FrCornaire thanks for the pull request and the fix!
> 
> With the fix you are providing, the inputs are often visible, often not. This is because of the following line
> 
> https://github.com/containers/podman-desktop/blob/109741f9571b67989a5226d4d6201e98874bbef0/packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte#L88
> 
> where we only display the proxy inputs if the config exists, but as you are updating it, we may need to add a condition:
> 
> ```diff
> - {#if proxySettings} 
> + {#if proxySettings && proxyState === ProxyState.PROXY_MANUAL} 
> ```
> 
> This would make the proxy inputs only visible if we selected the `PROXY_MANUAL` manual state. Do you think you can make the change ?

We need to change the test as if system is in place (default) proxySettings may be undefined in case nothing is configured on system level. That would be the only required change

2024-10-17 13:57 UTC, jeffmaury requested changes
Thank you for the collaboration but this breaks the existing logic has everythink is collected locally and configuration is changed only when user clicks the Update button

2024-10-17 14:00 UTC, FrCornaire commented
> Thank you for the collaboration but this breaks the existing logic has everythink is collected locally and configuration is changed only when user clicks the Update button

Well my first approach was to save every time the state changed but it might be a bit too much .

2024-10-17 17:16 UTC, slemeur commented
Thanks for the PR, very nice @FrCornaire !

2025-03-14 09:28 UTC, benoitf commented
outdated

2025-03-14 09:28 UTC, closed without merging