chore: remember last child page visited for kubernetes and preferences pages
containers/podman-desktop pull request #9451
Opened 2024-10-17 22:11 UTC by SoniaSandler

### What does this PR do?
This PR adds stores to keep track of the last pages visited in Kubernetes and preferences pages, so that when leaving and coming back, the user will come back to the last page they visited in the same section (Kubernetes or preferences for now)

### Screenshot / video of UI

[Screencast from 2024-10-17 16-41-03.webm](https://github.com/user-attachments/assets/cd47c559-7c0f-4f0d-b3dc-b1b102b90863)

### What issues does this PR fix or reference?
Closes https://github.com/containers/podman-desktop/issues/9057

### How to test this PR?
Enter the preferences page, go to one of the other pages in preferences (e.g. Proxy), exit to some other page in PD that is not in preferences, and then go back to preferences. You should be back in your last visited preferences page (e.g. Proxy)

- [X] Tests are covering the bug fix or the new feature

2024-10-17 22:15 UTC, SoniaSandler commented
@deboer-tim I wasn't sure how specific we want the last visited page to be, so for now it is the very last one (could be summary/details page in kubernetes, or `create new` pages in preferences), but if needed, I can change it to just keep track of the last general section visited (Nodes, Deployments, Services, Preferences, CLI Tools, etc.)

2024-10-18 06:25 UTC, gastoner approved these changes
LGTM, works well!

2024-10-18 14:16 UTC, deboer-tim requested changes
This change seems very hard-coded, i.e. every time we add or change a submenu we also need to update App, Route, breadcrumb, and associated tests. I haven't looked at the code, but is there something we could do that is more generic / based on NavigationRegistryEntry submenus? Settings likely isn't a submenu today but could be (and that part could be a separate PR)

I was hoping for something along the lines of:
- enter submenu for first time -> pick first page
- navigate within submenu -> store path for next entry

Failing tests need to be fixed.

2024-10-18 14:39 UTC, SoniaSandler commented
@deboer-tim since settings is not yet a submenu, should I keep the changes for it or remove them and just update the submenu?

2024-10-18 20:24 UTC, deboer-tim commented
> @deboer-tim since settings is not yet a submenu, should I keep the changes for it or remove them and just update the submenu?

I'd suggest checking if we can do something simpler/less hard-coded for submenus first. If so then yes I'd break it up, otherwise we can re-evaluate.

2024-10-21 04:46 UTC, SoniaSandler commented
@deboer-tim I've changes the PR to work for submenus and removed the changes for the preferences section, but now the last page visited is less specific. For example, when coming back to the nodes page, it will go to the node list page, even if the last visited Kubernetes page was a specific node, but I can modify it to be more specific if needed

2024-10-21 15:29 UTC, cdrage commented
Silly question, but with this PR, unsure if this should be done within this PR or as a follow-up, but what about remembering sections in extensions that use SubmenuNavigation imported? (ex bootc extension)

2024-10-21 16:49 UTC, SoniaSandler commented
@cdrage I looked in the bootc repo, and it looks like it only uses `SettingsNavItem` from this PR. I think that for extensions we'll have to update their navigation files manually to also remember last child page.
TBH, I'm not sure if there is a way for me to generalize it more so that it would also automatically include extensions' submenus. 
For now, this PR should work for all submenus created/rendered with `SubmenuNavigation.svelte`, but I can explore the topic of the extension submenus more if needed.

2024-10-22 10:03 UTC, benoitf commented on packages/renderer/src/SubmenuNavigation.svelte
> +}
AFAIK we can't have anything here related to kubernetes

2024-10-23 15:33 UTC, benoitf approved these changes

2024-10-23 15:53 UTC, deboer-tim approved these changes
Thank you for the changes, this commit is much better and works well in testing.

2024-10-23 16:16 UTC, cdrage approved these changes
Works well for me! LGTM and great work.

2024-10-23 16:17 UTC, merged