chore: use dropdown component in Kube terminal
containers/podman-desktop pull request #9510
Opened 2024-10-21 19:56 UTC by deboer-tim

### What does this PR do?

Switches the select in the Kube terminal to a Dropdown.

The select control automatically selects the first value if none is provided. Dropdown wasn't doing that so I added the appropriate line, hoping it is small enough to justify including it here.

Remove redundant aria-labelledby (label already points to control).

### Screenshot / video of UI

<img width="385" alt="Screenshot 2024-10-21 at 3 36 06 PM" src="https://github.com/user-attachments/assets/ab387b3e-c8b2-4d53-a2c8-c8aadd2404a6">

### What issues does this PR fix or reference?

Part of #6199.

### How to test this PR?

Deploy a pod to Kubernetes with more than one container, go to pod's Terminal tab.

- [x] Tests are covering the bug fix or the new feature

2024-10-22 10:01 UTC, benoitf requested changes
the PR is not only using the dropdown in Kube terminal but changing the behavior of the dropdown


--> needs to be in a separate PR

2024-10-22 15:41 UTC, deboer-tim commented
> the PR is not only using the dropdown in Kube terminal but changing the behavior of the dropdown
> 
> --> needs to be in a separate PR

👍🏼. Broke out #9537 and will rebase this on top.

2024-10-23 19:31 UTC, benoitf approved these changes

2024-10-23 19:34 UTC, deboer-tim commented
Rebased on main and down to only the one change, ready for re-review.

2024-10-24 07:23 UTC, jeffmaury approved these changes
LGTM

2024-10-24 21:37 UTC, merged