fix: proxy settings page stuck
containers/podman-desktop pull request #9524
Opened 2024-10-22 08:16 UTC by jeffmaury

Fixes #9379

### What does this PR do?

Update the Proxies preference page

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#9379 

### How to test this PR?

Go to the proxies preference page and change to either manual or disabled

- [ ] Tests are covering the bug fix or the new feature

2024-10-22 08:27 UTC, axel7083 requested changes
![image](https://github.com/user-attachments/assets/e21504af-1a24-48d7-a47e-a95540bc8e09)

The page crash on my machine

![image](https://github.com/user-attachments/assets/b72de00a-d952-43b8-8752-4e992aea2604)

Because this is not the real type

2024-10-22 08:27 UTC, axel7083 commented on packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte
> +    {#if proxyState !== ProxyState.PROXY_SYSTEM}
if I have selected `manual` then switch back to system, I will not see the update button, therefore I will not be able to update the settings ?

2024-10-22 08:28 UTC, axel7083 requested changes
![image](https://github.com/user-attachments/assets/e21504af-1a24-48d7-a47e-a95540bc8e09)

The page crash on my machine

![image](https://github.com/user-attachments/assets/b72de00a-d952-43b8-8752-4e992aea2604)

Because this is not the real type
https://github.com/containers/podman-desktop/blob/cd668fe99f28d75c4029f5479e581db212c0ed8f/packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte#L12C5-L12C18

it is `let proxySettings: ProxySettings | undefined;` and we are reading the value of undefined for the inputs

2024-10-22 12:25 UTC, axel7083 approved these changes
If we are in a hurry to release this is an acceptable solution 👍 , and we could do follow up PR to improve the design.

We have a dedicated issue for testing https://github.com/containers/podman-desktop/issues/9525

## UX remark

![image](https://github.com/user-attachments/assets/a9d1d2b1-7570-43ad-a378-1106d09f8d78)

The `Update` button is always active, but should be disabled after we save: if we have nothing to update , the button should be disabled, this is missleading to always see it visible.

I still believe that disabled and system should hide the inputs and automatically save through the select on:change property. Avoiding the user to have to click on update after  setting to system or disabled.

2024-10-22 13:43 UTC, jeffmaury commented
> If we are in a hurry to release this is an acceptable solution 👍 , and we could do follow up PR to improve the design.
> 
> We have a dedicated issue for testing #9525
> ## UX remark
> 
> ![image](https://private-user-images.githubusercontent.com/42176370/378835915-a9d1d2b1-7570-43ad-a378-1106d09f8d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDQ3NDcsIm5iZiI6MTcyOTYwNDQ0NywicGF0aCI6Ii80MjE3NjM3MC8zNzg4MzU5MTUtYTlkMWQyYjEtNzU3MC00M2FkLWEzNzgtMTEwNmQwOWY4ZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEzNDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzQ4ZTA4ZTFjMTY1MzM2ZDMyZmM5ZGNiOTM1NTI4MGQyNzNmMDFkNDk3OTAyOTM1NmYxYzA4ZDY0MjQ4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gQz5jfTApiflMMGwlxWkuB-xVi2GYdhLVq-BLw7TR5E)
> 
> The `Update` button is always active, but should be disabled after we save: if we have nothing to update , the button should be disabled, this is missleading to always see it visible.
> 
> I still believe that disabled and system should hide the inputs and automatically save through the select on:change property. Avoiding the user to have to click on update after setting to system or disabled.

That is to be discussed and out of scope of this PR.

2024-10-23 06:01 UTC, gastoner approved these changes
LGTM

2024-10-23 13:32 UTC, merged