fix: check for Virtual Machine only for WSL
containers/podman-desktop pull request #9557
Opened 2024-10-23 14:23 UTC by jeffmaury

Fixes #9177

### What does this PR do?

Check for VirtualMachine presence only for WSL

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#9177 

### How to test this PR?

1. Remove podman
2. Virtual Machine
3. Check that preflights are ok

- [x] Tests are covering the bug fix or the new feature

2024-10-23 16:27 UTC, benoitf reviewed
codewise LGTM but I'm on macOS

2024-10-24 07:49 UTC, benoitf approved these changes
forgot to approve when commenting

2024-10-24 11:16 UTC, odockal commented
I would like to verify on Windows after testing.

2024-10-25 11:20 UTC, odockal approved these changes
From the issue perspective, we can now install podman when having a hyperv only enabled. I have opened a follow up issue to tackle other problem I have discovered: https://github.com/containers/podman-desktop/issues/9610

2024-10-25 14:54 UTC, odockal requested changes
Sorry, I have changed my mind: I have tried again and specified what will happen if we will merge this issue: https://github.com/containers/podman-desktop/issues/9610. 
Basically, now we would be forcing user to open pd with admin right when he has no hyperv or WSL enabled yet, just to tell him he needs hyperV. We need to improve the workflow when doing requirements check.

2024-10-25 16:56 UTC, jeffmaury commented
> Sorry, I have changed my mind: I have tried again and specified what will happen if we will merge this issue: #9610. Basically, now we would be forcing user to open pd with admin right when he has no hyperv or WSL enabled yet, just to tell him he needs hyperV. We need to improve the workflow when doing requirements check.

I updated so that we return the first check that failed (WSL in that case). It needs another follow up PR as we should inform that both WSL and HyperV are not valid but needs discussion so not for 1.14

2024-10-30 09:11 UTC, odockal approved these changes

2024-10-30 10:34 UTC, merged