fix: use `utf16le` ecoding in powershell call for Virtual Machine Pltform detection
containers/podman-desktop pull request #9594
Opened 2024-10-24 17:15 UTC by dgolovin

### What does this PR do?

Uses default encoding for powershell execution similar to https://github.com/containers/podman-desktop/pull/4918 to find string in powershell output.

### Screenshot / video of UI

### What issues does this PR fix or reference?

#7414.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

2024-10-24 17:22 UTC, benoitf approved these changes
we already had this issue in the past and fixed using 'utf16le' in podman

this PR works for me but I think we need a follow-up having a powerShell helper in podman extension where we always pass the encoding to not forget it

suggestion: we had a wslHelper, could we have a powershellHelper

todo: there is a missing unit test before merging

2024-10-24 22:48 UTC, dgolovin commented
Bad news, it does not work as expected. I am not sure about #4918 ether, because I am not sure it was tested on real OS and the test is not actually testing the case.

With powershell it is even worse, because we are running powershell and ask it to execute a script. Will try to replicate the problem first.

2024-10-29 02:49 UTC, dgolovin commented
Added command to set output encoding to match encoding we set on stdout.

Added test to verify encoding option is passed to the process.exec.

2024-11-04 10:33 UTC, benoitf approved these changes
approving for the code but needs to be checked on windows

cc @containers/podman-desktop-qe-reviewers

2024-11-11 06:34 UTC, gastoner approved these changes
Tried to create a machine on Windows ✅ , not sure what else should I try out

2024-11-12 15:54 UTC, dgolovin commented
> approving for the code but needs to be checked on windows
> 
> cc @containers/podman-desktop-qe-reviewers

@gastoner Could you try to go through onboarding for podman? That is when the code is going to be executed to check for VirtualMachinePlatform is installed.

2024-11-13 14:19 UTC, gastoner commented
@dgolovin 

https://github.com/user-attachments/assets/1247cb96-c25d-4f00-86ca-87c3c09f37f5

Should be OK

2024-11-14 09:44 UTC, odockal commented
> @dgolovin
> Screen.Recording.2024-11-13.151619.mp4
> 
> Should be OK (this step should contain the check for VirtualMachinePlatform right?)

Nope, it is when you do not have podman installed, then you can either go through onboarding ( on fresh start up of podman desktop or via Settings -> Resources -> Setup Podman to run the requirements check for podman installation) or via dashboard (Install Podman).

2024-11-14 13:14 UTC, odockal requested changes
I cannot get through the WSL2 version check:
![wsl-requirements-check](https://github.com/user-attachments/assets/5434150f-97fe-499a-992e-1230d8085546)

2024-11-14 13:56 UTC, odockal commented
But it might not be related to this PR at all. 1.14.1 behaves the same. I am doing a clean up of the PC.

2024-11-14 14:00 UTC, odockal approved these changes
Finally, I managed to actually get `wsl --install --no-distribution` applied. Hence everything works fine. 

Problem might have been that there was a hanging windows update. I updated and all works normally.

2024-11-14 19:11 UTC, merged