fix: proxy settings do not take effect when switched
containers/podman-desktop pull request #9627
Opened 2024-10-26 09:48 UTC by Indekkusu545

### What does this PR do?

Fixes proxy settings do not take effect when switched to system or disabled

### Screenshot / video of UI

### What issues does this PR fix or reference?
Fixes #9625 

### How to test this PR?

- [ x] Tests are covering the bug fix or the new feature

2024-10-26 10:03 UTC, Indekkusu545 commented on packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte
> -  if (proxyState !== ProxyState.PROXY_SYSTEM) {
Note that this condition was added by @jeffmaury a while ago to fix #9379.

This condition causes the proxy configuration not to be updated when the proxy configuration is switched to System. When I deleted this condition, the test did not find any errors.

I am not sure why this condition was added, maybe further discussion is needed.

2024-10-28 08:46 UTC, axel7083 approved these changes
Thanks @Indekkusu545 for the fix, the change LGTM, waiting for @jeffmaury confirmation

2024-10-28 09:31 UTC, jeffmaury requested changes

2024-10-28 09:31 UTC, jeffmaury commented on packages/main/src/plugin/proxy.ts
> +      newProxy = {} as ProxySettings;
Should be undefined as we are preventing use of empty proxy setting

2025-03-14 09:28 UTC, benoitf commented
outdated

2025-03-14 09:28 UTC, closed without merging