feat: adding port forwarding actions to kube container details
containers/podman-desktop pull request #9643
Opened 2024-10-28 14:58 UTC by axel7083

### What does this PR do?

Add the `Forward` action for Kubernetes **pods**, in the Summary page.

### Screenshot / video of UI

![image](https://github.com/user-attachments/assets/94eea2bc-ce78-40fd-b924-9781a5ae45e4)

![image](https://github.com/user-attachments/assets/01db6ae6-6fe2-4655-aca1-f7fda299eee5)

### What issues does this PR fix or reference?

Need rebase after https://github.com/containers/podman-desktop/pull/9642
Fixes https://github.com/containers/podman-desktop/issues/9273

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

**Testing manually**

1. assert __be connected to a k8s cluster__
2. deploy a K8S pod with exposed port(s)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
spec:
  containers:
    - image: nginx
      name: web
      ports:
        - containerPort: 80
          name: web
          protocol: TCP
```

3. Go to `pod` summary
4. Assert `Forward...` next to container ports

![image](https://github.com/user-attachments/assets/a43eddcd-39d0-4ad5-a435-254f799fc2f7)

5. Forward valid port (E.g. 80)

![image](https://github.com/user-attachments/assets/094a1e7f-2dae-4fd7-b914-efc3c71430e3)

6. assert new actions available (open, remove)
7. click on `open`

![image](https://github.com/user-attachments/assets/50257812-65f9-45a7-a12a-4bbbaecf116c)

8. assert browser open with nginx page visible
9. return to podman desktop
10. remove forward

![image](https://github.com/user-attachments/assets/7144521e-ba90-48fa-9201-83209567251a)

11. assert `Forward...` button is back
12. refresh browser 
13. assert connection should lost/timeout

2024-10-28 15:26 UTC, slemeur commented
👍

2024-10-28 16:27 UTC, deboer-tim commented
Tested quickly. Function was working really nicely, but I'm getting the following error periodically on this branch - can't confirm if it's actually related yet: 

<img width="269" alt="Screenshot 2024-10-28 at 12 16 09 PM" src="https://github.com/user-attachments/assets/1c4ee290-1983-4b44-b9bc-b2facecb797d">

nit: I'd like to see the local port number in the UI. Maybe Open button should be a URL link instead?

question: I'm also wondering if it's clear enough after you've forwarded that's what you're looking at, i.e. should we say 'forwarded port' or 'local port', or is that glaringly obvious?

2024-10-28 16:40 UTC, axel7083 commented
> Tested quickly. Function was working really nicely, but I'm getting the following error periodically on this branch - can't confirm if it's actually related

I don't know :thinking: this is only the UI, but there some chances that the backend implementation has some flaw, as it was pretty complicated to tests, I have not had the same error as you for now, will try again...

> question: I'm also wondering if it's clear enough after you've forwarded that's what you're looking at, i.e. should we say 'forwarded port' or 'local port', or is that glaringly obvious?

I don't know... I find it clear, but that's because I did the implementation lol, I can update the button title of open

2024-10-28 18:47 UTC, cdrage commented
https://github.com/user-attachments/assets/5cb707e0-56f8-41ac-b0d2-cb7531a9e69c

I'm getting weird port opening issues as well as issues when there are two ports but one is TCP and the other UDP. (22000 TCP and 22000 UDP opened).

2024-10-28 18:51 UTC, deboer-tim commented
Confirmed I get the Javascript error only when testing this branch. This time it happens immediately when I open a port, but functionally seems to work afterward.

2024-10-28 18:54 UTC, cdrage requested changes, later dismissed
I do not see port forwarding on services or deployment summary pages
![Screenshot 2024-10-28 at 2 53 49 PM](https://github.com/user-attachments/assets/a2cda604-fcfa-47a2-bb05-fe9f39083b07)
![Screenshot 2024-10-28 at 2 53 43 PM](https://github.com/user-attachments/assets/ff7891b5-6e3d-465a-96df-a4477a16a572)

2024-10-28 19:31 UTC, axel7083 commented
> I do not see port forwarding on services or deployment summary pages

@cdrage this is out of scope of this PR, only the pod's containers are covered.

2024-10-28 19:36 UTC, axel7083 commented
> I'm getting weird port opening issues as well as issues when there are two ports but one is TCP and the other UDP. (22000 TCP and 22000 UDP opened).

This is a backend issue, might be related to https://github.com/containers/podman-desktop/issues/9640.

The big problem here is probably that the backend is trying to reach on the given port when it opens it, might not have been made for UDP ( cc @jeffmaury @vzhukovs )

2024-10-28 19:37 UTC, axel7083 commented
> Confirmed I get the Javascript error only when testing this branch. This time it happens immediately when I open a port, but functionally seems to work afterward.

This is definitely not a problem that the frontend can fix.

2024-10-28 19:39 UTC, cdrage commented
> > I do not see port forwarding on services or deployment summary pages
> 
> @cdrage this is out of scope of this PR, only the pod's containers are covered.

The issue linked in the PR lists deployments and services though, maybe we split this into different issues / PR's for deployment and service implementation? https://github.com/containers/podman-desktop/issues/9273

2024-10-28 19:49 UTC, axel7083 commented
> The issue linked in the PR lists deployments and services though, maybe we split this into different issues / PR's for deployment and service implementation? https://github.com/containers/podman-desktop/issues/9273

Oh yeah you are right, will split tomorrow

2024-10-29 10:04 UTC, axel7083 commented
Following our discussion here is the new look of the Port Forwarding List page

![image](https://github.com/user-attachments/assets/bdc35bde-aaf4-4087-9664-5e2449b5c3a4)

2024-10-30 08:29 UTC, gastoner approved these changes
LGTM

2024-10-30 10:47 UTC, jeffmaury commented
> Tested quickly. Function was working really nicely, but I'm getting the following error periodically on this branch - can't confirm if it's actually related yet:
> <img alt="Screenshot 2024-10-28 at 12 16 09 PM" width="269" src="https://private-user-images.githubusercontent.com/19958075/380799878-1c4ee290-1983-4b44-b9bc-b2facecb797d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODU0MDcsIm5iZiI6MTczMDI4NTEwNywicGF0aCI6Ii8xOTk1ODA3NS8zODA3OTk4NzgtMWM0ZWUyOTAtMTk4My00YjQ0LWI5YmMtYjJmYWNlY2I3OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEwNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTg2OTRiYWRlZjhlNjM1NmQ5NDMzOWRkNDc5ZTA4YzhmY2JjZTk0YTY3MzlmMjk1NjdmNTM0Y2Y1ZjI5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nTrYEW5CJ9igtJZFk3bI1lA1rZBltXw3VBI4OTfEOjM">
> 
> nit: I'd like to see the local port number in the UI. Maybe Open button should be a URL link instead?
> 
> question: I'm also wondering if it's clear enough after you've forwarded that's what you're looking at, i.e. should we say 'forwarded port' or 'local port', or is that glaringly obvious?

Having the same on main

2024-10-30 10:50 UTC, jeffmaury commented
> > I'm getting weird port opening issues as well as issues when there are two ports but one is TCP and the other UDP. (22000 TCP and 22000 UDP opened).
> 
> This is a backend issue, might be related to #9640.
> 
> The big problem here is probably that the backend is trying to reach on the given port when it opens it, might not have been made for UDP ( cc @jeffmaury @vzhukovs )

UDP port forwarding is not supported by K8S: https://github.com/kubernetes/kubernetes/issues/47862

2024-10-30 10:51 UTC, jeffmaury approved these changes
LGTM. Maybe rename Remove by Stop ?

Could be great if we can prevent port forwarding for UDP ports as it's not supported by K8S

2024-10-30 10:54 UTC, axel7083 commented
> Could be great if we can prevent port forwarding for UDP ports as it's not supported by K8S

I created https://github.com/containers/podman-desktop/issues/9676

2024-10-30 10:54 UTC, merged